### ISSUE TITLE
好评，出的太快了，想提一些小建议

### ISSUE THREAD

**Issue by pythone1** [yatengLG/ISAT_with_segment_anything#1]
可以在右边点击添加类，比如“person”，然后在左击进行分割，把分割的内容直接添加到该类，这样更便捷一些

**Comment by pythone1** [comment]
1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些
2、可以添加一键预测的功能，然后对结果进行归类
3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩
        points_per_side: Optional【int】 = 32,
        points_per_batch: int = 64,
        pred_iou_thresh: float = 0.88,
        stability_score_thresh: float = 0.95,
        stability_score_offset: float = 1.0,
        box_nms_thresh: float = 0.7,
        crop_n_layers: int = 0,
        crop_nms_thresh: float = 0.7,
        crop_overlap_ratio: float = 512 / 1500,
        crop_n_points_downscale_factor: int = 1,
        point_grids: Optional[List【np.ndarray】] = None,
        min_mask_region_area: int = 0,
        output_mode: str = "binary_mask",
非常期待新的版本

**Comment by yatengLG** [comment]
> 1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些 2、可以添加一键预测的功能，然后对结果进行归类 3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩 points_per_side: Optional【int】 = 32, points_per_batch: int = 64, pred_iou_thresh: float = 0.88, stability_score_thresh: float = 0.95, stability_score_offset: float = 1.0, box_nms_thresh: float = 0.7, crop_n_layers: int = 0, crop_nms_thresh: float = 0.7, crop_overlap_ratio: float = 512 / 1500, crop_n_points_downscale_factor: int = 1, point_grids: Optional[List【np.ndarray】] = None, min_mask_region_area: int = 0, output_mode: str = "binary_mask", 非常期待新的版本

首先，非常感谢您能喜欢这个工具，对于您提的建议，我也会好好考虑的ʕ̯•͡˔•̯᷅ʔ

这里先对您提的建议进行一下回复：
1. 右侧直接点击类别，的确会简化特别多的操作，但是对于一些需要标注中添加额外信息的工作，就不太友好了。
2. 一键预测功能，有考虑过。但这个功能存在非常大的局限性，只能针对特定的一些类别进行分类，如果预测错误，后续进行修改的话，工作量会比直接标注要大得多。
3. 结果不稳定的问题，项目中是通过多次点击进行结果调整的。 鼠标左键点击感兴趣区域、右键点击不感兴趣区域，通过多次点击来完善mask。另外为了方便，可以通过【退格】的方式（有退格按钮与快捷键），返回上一次点击前的mask状态。
4. 显存这块儿，的确是非常有必要添加的，T.Th模型在这个样例数据上，显存占用已经达到8G+了。如果图片再大点儿，就抛不开了T.T。


另外，项目也在持续更新，b站最近也是刚上传了演示视频，https://www.bilibili.com/video/BV1Lk4y1J7uB/。
欢迎继续支持，多提建议。ʕ̯•͡˔•̯᷅ʔ

**Comment by pythone1** [comment]
> > 1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些 2、可以添加一键预测的功能，然后对结果进行归类 3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩 points_per_side: Optional【int】 = 32, points_per_batch: int = 64, pred_iou_thresh: float = 0.88, stability_score_thresh: float = 0.95, stability_score_offset: float = 1.0, box_nms_thresh: float = 0.7, crop_n_layers: int = 0, crop_nms_thresh: float = 0.7, crop_overlap_ratio: float = 512 / 1500, crop_n_points_downscale_factor: int = 1, point_grids: Optional[List【np.ndarray】] = None, min_mask_region_area: int = 0, output_mode: str = "binary_mask", 非常期待新的版本
> 
> 首先，非常感谢您能喜欢这个工具，对于您提的建议，我也会好好考虑的ʕ̯•͡˔•̯᷅ʔ
> 
> 这里先对您提的建议进行一下回复：
> 
> 1. 右侧直接点击类别，的确会简化特别多的操作，但是对于一些需要标注中添加额外信息的工作，就不太友好了。
> 2. 一键预测功能，有考虑过。但这个功能存在非常大的局限性，只能针对特定的一些类别进行分类，如果预测错误，后续进行修改的话，工作量会比直接标注要大得多。
> 3. 结果不稳定的问题，项目中是通过多次点击进行结果调整的。 鼠标左键点击感兴趣区域、右键点击不感兴趣区域，通过多次点击来完善mask。另外为了方便，可以通过【退格】的方式（有退格按钮与快捷键），返回上一次点击前的mask状态。
> 4. segment anything模型参数部分的配置界面，已经在计划内了，coming soon。
> 5. 显存这块儿，的确是非常有必要添加的，h模型在这个样例数据上，显存占用已经达到8G+了。如果图片再大点儿，就跑不开了T.T。
> 
> 另外，项目也在持续更新，b站最近也是刚上传了演示视频，[https://www.bilibili.com/video/BV1Lk4y1J7uB/。](https://www.bilibili.com/video/BV1Lk4y1J7uB/%E3%80%82) 欢迎继续支持，多提建议。ʕ̯•͡˔•̯᷅ʔ

B站过来的，已三连，回复好快
您说的1.标注中添加额外信息的工作，可能我没遇到过，因此就忽略了，之前标注用过飞浆的EISEG和其他的，都喜欢那种标完狂点F下一张的感觉，感觉很快，忽然需要标完再点击分类，就感觉标注变的慢了下来
![image](https://user-images.githubusercontent.com/101239008/233833559-c4fda98f-2bb0-4a55-9eff-2f52d36694a7.png)
您说的2.是对的，我没有考虑后续的删除和修正标签，3.我感觉已经挺好的，都比较适应
然后4,应该我需要的划分效果要求比较高，不去调points_per_side这个参数，可能会存在小块的东西分不出来这个情况，比如这里的坑塘
![image](https://user-images.githubusercontent.com/101239008/233833112-9e204ddd-e47f-4e8d-86fd-8d7bbac05ad2.png)
实现细分，要调points_per_side这个参数（或者对图像本身进行上采样），最终才能实现细分到块的效果，默认参数直接去点击提取就变成了一整块,所以很期待出调参的版本，提高标注精度
![企业微信截图_16817965212040](https://user-images.githubusercontent.com/101239008/233833143-6648fcd3-8a96-48a9-a95b-12e3185a33ff.png)

最后感谢回复

**Comment by wuzhin** [comment]
提一个小建议，mask太挡视线了，建议加几个快捷键：按住alt显示原图，ctrl+z撤回上一个添加的点

**Comment by yatengLG** [comment]
> 提一个小建议，mask太挡视线了，建议加几个快捷键：按住alt显示原图，ctrl+z撤回上一个添加的点

退格按钮（快捷键Z）撤销上一个添加的点（对于segment anything与 手动添加多边形均有效）

**Comment by yatengLG** [comment]
> > > 1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些 2、可以添加一键预测的功能，然后对结果进行归类 3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩 points_per_side: Optional【int】 = 32, points_per_batch: int = 64, pred_iou_thresh: float = 0.88, stability_score_thresh: float = 0.95, stability_score_offset: float = 1.0, box_nms_thresh: float = 0.7, crop_n_layers: int = 0, crop_nms_thresh: float = 0.7, crop_overlap_ratio: float = 512 / 1500, crop_n_points_downscale_factor: int = 1, point_grids: Optional[List【np.ndarray】] = None, min_mask_region_area: int = 0, output_mode: str = "binary_mask", 非常期待新的版本
> > 
> > 
> > 首先，非常感谢您能喜欢这个工具，对于您提的建议，我也会好好考虑的ʕ̯•͡˔•̯᷅ʔ
> > 这里先对您提的建议进行一下回复：
> > 
> > 1. 右侧直接点击类别，的确会简化特别多的操作，但是对于一些需要标注中添加额外信息的工作，就不太友好了。
> > 2. 一键预测功能，有考虑过。但这个功能存在非常大的局限性，只能针对特定的一些类别进行分类，如果预测错误，后续进行修改的话，工作量会比直接标注要大得多。
> > 3. 结果不稳定的问题，项目中是通过多次点击进行结果调整的。 鼠标左键点击感兴趣区域、右键点击不感兴趣区域，通过多次点击来完善mask。另外为了方便，可以通过【退格】的方式（有退格按钮与快捷键），返回上一次点击前的mask状态。
> > 4. segment anything模型参数部分的配置界面，已经在计划内了，coming soon。
> > 5. 显存这块儿，的确是非常有必要添加的，h模型在这个样例数据上，显存占用已经达到8G+了。如果图片再大点儿，就跑不开了T.T。
> > 
> > 另外，项目也在持续更新，b站最近也是刚上传了演示视频，[https://www.bilibili.com/video/BV1Lk4y1J7uB/。](https://www.bilibili.com/video/BV1Lk4y1J7uB/%E3%80%82) 欢迎继续支持，多提建议。ʕ̯•͡˔•̯᷅ʔ
> 
> B站过来的，已三连，回复好快 您说的1.标注中添加额外信息的工作，可能我没遇到过，因此就忽略了，之前标注用过飞浆的EISEG和其他的，都喜欢那种标完狂点F下一张的感觉，感觉很快，忽然需要标完再点击分类，就感觉标注变的慢了下来 ![image](https://user-images.githubusercontent.com/101239008/233833559-c4fda98f-2bb0-4a55-9eff-2f52d36694a7.png) 您说的2.是对的，我没有考虑后续的删除和修正标签，3.我感觉已经挺好的，都比较适应 然后4,应该我需要的划分效果要求比较高，不去调points_per_side这个参数，可能会存在小块的东西分不出来这个情况，比如这里的坑塘 ![image](https://user-images.githubusercontent.com/101239008/233833112-9e204ddd-e47f-4e8d-86fd-8d7bbac05ad2.png) 实现细分，要调points_per_side这个参数（或者对图像本身进行上采样），最终才能实现细分到块的效果，默认参数直接去点击提取就变成了一整块,所以很期待出调参的版本，提高标注精度 ![企业微信截图_16817965212040](https://user-images.githubusercontent.com/101239008/233833143-6648fcd3-8a96-48a9-a95b-12e3185a33ff.png)
> 
> 最后感谢回复

对于第4点，添加参数部分，这里进行下反馈：

刚看了代码，您这边说的应该是全图自动分割的代码，也就是segment anything项目中的automatic_mask_generator.py接口。
这个接口是自动对整张图像进行分割的，所以需要调整点的数量与间隔，用来对全图生成分割区域。

本项目中，目的是对单个目标进行分割，通过鼠标单击的方式，来提示模型感性兴趣区域。具体的调用接口是segment anything项目中的perdictor.py，可以通过多次点击方式来提供点的数量与位置。因而不存在这里所说的参数问题。

**Comment by yatengLG** [comment]
> 1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些 2、可以添加一键预测的功能，然后对结果进行归类 3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩 points_per_side: Optional【int】 = 32, points_per_batch: int = 64, pred_iou_thresh: float = 0.88, stability_score_thresh: float = 0.95, stability_score_offset: float = 1.0, box_nms_thresh: float = 0.7, crop_n_layers: int = 0, crop_nms_thresh: float = 0.7, crop_overlap_ratio: float = 512 / 1500, crop_n_points_downscale_factor: int = 1, point_grids: Optional[List【np.ndarray】] = None, min_mask_region_area: int = 0, output_mode: str = "binary_mask", 非常期待新的版本

显存需求会随着图片大小以及模型变化，不好确定显存需求。但最近的更新添加了实时的显存占用显示，在软件右下角显示。

欢迎提新建议哦，多谢支持ʕ̯•͡˔•̯᷅ʔ

**Comment by LSH9832** [comment]
> > > 1、可以在右边点击添加类，比如“person”，然后在左侧单击进行分割，把分割的内容直接添加到该类，这样更便捷一些 2、可以添加一键预测的功能，然后对结果进行归类 3、GUI界面可以添加调参，points_per_side/batch等这些比较重要的参数设置成可改的，特别是points_per_side，对结果影响挺大的，再加一个显存提醒，不然程序容易崩 points_per_side: Optional【int】 = 32, points_per_batch: int = 64, pred_iou_thresh: float = 0.88, stability_score_thresh: float = 0.95, stability_score_offset: float = 1.0, box_nms_thresh: float = 0.7, crop_n_layers: int = 0, crop_nms_thresh: float = 0.7, crop_overlap_ratio: float = 512 / 1500, crop_n_points_downscale_factor: int = 1, point_grids: Optional[List【np.ndarray】] = None, min_mask_region_area: int = 0, output_mode: str = "binary_mask", 非常期待新的版本
> > 
> > 
> > 首先，非常感谢您能喜欢这个工具，对于您提的建议，我也会好好考虑的ʕ̯•͡˔•̯᷅ʔ
> > 这里先对您提的建议进行一下回复：
> > 
> > 1. 右侧直接点击类别，的确会简化特别多的操作，但是对于一些需要标注中添加额外信息的工作，就不太友好了。
> > 2. 一键预测功能，有考虑过。但这个功能存在非常大的局限性，只能针对特定的一些类别进行分类，如果预测错误，后续进行修改的话，工作量会比直接标注要大得多。
> > 3. 结果不稳定的问题，项目中是通过多次点击进行结果调整的。 鼠标左键点击感兴趣区域、右键点击不感兴趣区域，通过多次点击来完善mask。另外为了方便，可以通过【退格】的方式（有退格按钮与快捷键），返回上一次点击前的mask状态。
> > 4. segment anything模型参数部分的配置界面，已经在计划内了，coming soon。
> > 5. 显存这块儿，的确是非常有必要添加的，h模型在这个样例数据上，显存占用已经达到8G+了。如果图片再大点儿，就跑不开了T.T。
> > 
> > 另外，项目也在持续更新，b站最近也是刚上传了演示视频，[https://www.bilibili.com/video/BV1Lk4y1J7uB/。](https://www.bilibili.com/video/BV1Lk4y1J7uB/%E3%80%82) 欢迎继续支持，多提建议。ʕ̯•͡˔•̯᷅ʔ
> 
> B站过来的，已三连，回复好快 您说的1.标注中添加额外信息的工作，可能我没遇到过，因此就忽略了，之前标注用过飞浆的EISEG和其他的，都喜欢那种标完狂点F下一张的感觉，感觉很快，忽然需要标完再点击分类，就感觉标注变的慢了下来 ![image](https://user-images.githubusercontent.com/101239008/233833559-c4fda98f-2bb0-4a55-9eff-2f52d36694a7.png) 您说的2.是对的，我没有考虑后续的删除和修正标签，3.我感觉已经挺好的，都比较适应 然后4,应该我需要的划分效果要求比较高，不去调points_per_side这个参数，可能会存在小块的东西分不出来这个情况，比如这里的坑塘 ![image](https://user-images.githubusercontent.com/101239008/233833112-9e204ddd-e47f-4e8d-86fd-8d7bbac05ad2.png) 实现细分，要调points_per_side这个参数（或者对图像本身进行上采样），最终才能实现细分到块的效果，默认参数直接去点击提取就变成了一整块,所以很期待出调参的版本，提高标注精度 ![企业微信截图_16817965212040](https://user-images.githubusercontent.com/101239008/233833143-6648fcd3-8a96-48a9-a95b-12e3185a33ff.png)
> 
> 最后感谢回复

我也是B站过来的哈哈，太强了。我把这位大佬的代码改了一些

你说的快速标注的问题，我通过增设几个快捷键加快了相同类型目标的标注速度，然后支持了半精度推理，显存占用直接缩小了差不多一半，然后还有一些其他的优化

如果感兴趣的话可以看一下[我魔改的版本](https://github.com/LSH9832/SAMLabeler)

**Comment by yatengLG** [comment]
> 

欢迎支持，这就是开源的魅力ʕ̯•͡˔•̯᷅ʔ
