### ISSUE TITLE
使用命令 pip install -r requirements.txt时 一直在报错

### ISSUE THREAD

**Issue by JiXiangY** [yatengLG/ISAT_with_segment_anything#10]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/17586372/235077540-43e2af06-28c1-4323-a01a-c3f5b89a8a5f.png">
因为conda 装 3.8的环境 也报错 所以装的3.9.6的版本 
然后这个PyQt5 也装不上

**Comment by JiXiangY** [comment]
M1 的 mac的原因么

**Comment by pythone1** [comment]
这个requirements写的是参考的包，有些指定了版本，python版本和环境都可能导致装不上，先把segme anything环境搭起来，在补装一些包就可以了
