### ISSUE TITLE
Does anyone know how to stop mark?

### ISSUE THREAD

**Issue by Darrenpig** [yatengLG/ISAT_with_segment_anything#101]
<img width="1080" alt="屏幕截图 2023-11-25 230440" src="https://github.com/yatengLG/ISAT_with_segment_anything/assets/121377489/f3d1dc32-4226-484b-9451-411459fd91e6">

**Comment by yatengLG** [comment]
https://github.com/yatengLG/ISAT_with_segment_anything#1%E6%A0%87%E6%B3%A8

**Comment by yatengLG** [comment]
https://www.bilibili.com/video/BV1or4y1R7EJ/?vd_source=49530ddbeee52d761a9b71fac81e004a

**Comment by Darrenpig** [comment]
Thanks a lot!
