### ISSUE TITLE
选择源码运行，无法打开文件夹

### ISSUE THREAD

**Issue by tsqt2023** [yatengLG/ISAT_with_segment_anything#102]
我选择用pycharm运行  main.py  出来的界面无法选择文件夹打开 
NotADirectoryError: [Errno 20] 不是目录: '/run/user/1000/doc/a60256ae/00051009.jpg'
NotADirectoryError: [Errno 20] 不是目录: '/run/user/1000/doc/a60256ae/00051009.jpg'

**Comment by tsqt2023** [comment]
是不是ubuntu20.04不支持这个工具，我无法选择我的文件夹，只能选择打开图片。

**Comment by yatengLG** [comment]
问题解决了嘛？

**Comment by tsqt2023** [comment]
没有呢，只能打开图片，直接略过文件夹了

**Comment by yatengLG** [comment]
你拉最新的代码试一下，你这个问题你是第一个提的。T.T 我一时也不知道你这个是啥情况

**Comment by 983632847** [comment]
ubuntu上测试也遇到同样的问题，选择文件夹时默认跳过文件夹，只能选择里面的一张图像，点open然后程序闪退

**Comment by yatengLG** [comment]
![Image](https://github.com/user-attachments/assets/7dd6f595-9695-4f4d-96ea-d4e4adb0dc71)

/run/user/1000/doc的权限问题。
