### ISSUE TITLE
显示窗口最大化后自动退出

### ISSUE THREAD

**Issue by ChangxingYang37** [yatengLG/ISAT_with_segment_anything#103]
您好，工具非常棒，使用很方便！
但是在使用的时候出现了一个问题，将显示窗口最大化后会自动退出（显示器分辨率1920x1080），
我尝试改了下“MainWindow.resize(1280, 764)”这行代码，依旧会退出，请问是不是还有其他部分需要修改，谢谢！

**Comment by yatengLG** [comment]
不会啊，一直没遇到过这个问题。应该是你电脑或者环境的问题。

如果是源码运行的，可以看一下报错，查一下原因。
