### ISSUE TITLE
关于软件开发思路

### ISSUE THREAD

**Issue by Qingsi999** [yatengLG/ISAT_with_segment_anything#104]
请问下，在软件开发交互过程中，关于图层等方面的推荐学习方向是否有

**Comment by yatengLG** [comment]
图层方面就是基础的qt

主要就是通过Item实现的，比如你可以看下面两个类，一个是顶点类，一个是多边形类:https://github.com/yatengLG/ISAT_with_segment_anything/blob/df144a7c7285ab9a97f1b43bcf683bcc1568ea2c/ISAT/widgets/polygon.py#L26

https://github.com/yatengLG/ISAT_with_segment_anything/blob/df144a7c7285ab9a97f1b43bcf683bcc1568ea2c/ISAT/widgets/polygon.py#L97

图层的高低就简单通过 item类的zValue就可以实现。例如你可以参考本软件的图层移动方式:

https://github.com/yatengLG/ISAT_with_segment_anything/blob/df144a7c7285ab9a97f1b43bcf683bcc1568ea2c/ISAT/widgets/canvas.py#L351
