### ISSUE TITLE
如何把标注的mask覆盖在原始图片上？

### ISSUE THREAD

**Issue by zidddd9527** [yatengLG/ISAT_with_segment_anything#105]
我用标注了一组图片中的两类（A和B），并且把json格式的标注文件和图片保存在一个文件夹下，我想把我的标注mask覆盖在原始图片上，并且把A的mask设置为黄色，B的mask颜色设置为绿色。如何实现呢？

**Comment by yatengLG** [comment]
你是想转png单通道图嘛？

如果是的话，你可以这么操作：
1. 打开软件，菜单栏-工具-转换
2. 选择VOC页面，打开isat保存的json文件夹，指定png的导出文件夹，点击转换即可。
3. 需要注意，如果想导出 实例分割的png图片（每一个目标一个颜色）需勾选“实例分割”按钮；如果想导出语义分割（每一类一个颜色）则不需要勾选
4. **导出的png图片的颜色，现在不是指定，你在使用时，直接读取像素值即可。（导出的png图片是单通道的，实例分割png中，每个像素值为实例id，如1， 2， 3之类；导出的语义分割png中，每个像素值为类别id，在导出时会保存一份classification.txt，类别id0对应第一行类别，id 1对应第二行，以此类推）**

**Comment by zidddd9527** [comment]
不是，我是要把标注的mask覆盖在原图，方便展示标注的效果。

**Comment by yatengLG** [comment]
如果只是本地展示，那你用软件再次打开不就好了嘛T.T

如果你是要把mask标在图像上，直接展示。那去百度找个脚本吧，随便啥格式的都可以，毕竟软件已经提供了转换各种格式的工具。 毕竟这个需求和软件没关系了已经
