### ISSUE TITLE
如何单键触发实现多个子功能，例如W=ESD+Q

### ISSUE THREAD

**Issue by Vincent-ZHQ** [yatengLG/ISAT_with_segment_anything#106]
多图片编辑时，需要Q Segment Anything, 然后图上选择掩码，E完成, S保存，D下一张，几千张图片下来，手累的不行，能不能把这常用操作集合到一个键位，比如Shift(或者W)=E+S+D+Q，一个键位实现四个键位的功能顺序触发，每次掩码勾选好后自动进入下一张图片的待掩码状态

**Comment by yatengLG** [comment]
这个主要不好实现。

你这个例子是，每个图一个目标，所以可以Q,点击,E,S,D
如果你有多个目标需要标注，就会是 Q,点击,E,Q,点击,E,....,S,D
如果你在标注过程中，单次提示mask效果不好，你就需要Q,点击,点击,...,E,Q,点击,,E,....,S,D
如果你在标注过程中，想不想修改，那就不能点S，需要Z回退，或者直接跳过。
如果目标，sam分割不了，还可能需要C去手动标注。
还有其他各种情况，所以必须把操作都单出来O(∩_∩)O

另外，本软件应该是市面上，操作量最少的标注软件了/(ㄒoㄒ)/~~

**Comment by Vincent-ZHQ** [comment]
确实不错，我已经用它标注几千张了，给大佬点赞，不过大多时候无脑操作ESD+Q，手真的很难受，请问本地临时修改怎么弄呀，QT代码我没看太明白，不需要很大修改，只是暂时增加一个键位满足顺序执行四个键位的触发功能就行

**Comment by yatengLG** [comment]
我中午有点事儿，下午回复你哈

**Comment by Vincent-ZHQ** [comment]
好滴，还剩20K图片呢，确实需要简化下操作

**Comment by yatengLG** [comment]
你自己修改吧，代码功能我已经测试过了


1. 以下代码添加到 widgets/mainwindows.py最后
```python
def add_extra_shortcut(self):
        self.extra_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("X"), self) # 这个X是快捷键，自己可以随便改，别和软件快捷键冲突就行
        self.extra_shortcut.setContext(QtCore.Qt.ApplicationShortcut)
        self.extra_shortcut.activated.connect(self.extra_func)

    def extra_func(self):
        self.scene.finish_draw() # E
        self.save()# S
        self.next_image() # D
        self.scene.start_segment_anything() # Q
```
2. 在widgets/mainwindows.py的__init__函数最后，添加
```python
        self.add_extra_shortcut()
```

**Comment by Vincent-ZHQ** [comment]
能用，就是这个效果，无比感恩

**Comment by zhouyang986** [comment]
用鼠标宏不是更容易…

**Comment by 258692011** [comment]
> 你自己修改吧，代码功能我已经测试过了
> 
> 1. 以下代码添加到 widgets/mainwindows.py最后
> 
> ```python
> def add_extra_shortcut(self):
>         self.extra_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("X"), self) # 这个X是快捷键，自己可以随便改，别和软件快捷键冲突就行
>         self.extra_shortcut.setContext(QtCore.Qt.ApplicationShortcut)
>         self.extra_shortcut.activated.connect(self.extra_func)
> 
>     def extra_func(self):
>         self.scene.finish_draw() # E
>         self.save()# S
>         self.next_image() # D
>         self.scene.start_segment_anything() # Q
> ```
> 
> 2. 在widgets/mainwindows.py的__init__函数最后，添加
> 
> ```python
>         self.add_extra_shortcut()
> ```

widgets/mainwindows.py的def __init__ 函数有很多个，
self.add_extra_shortcut() 我添加到 class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow): 类里面的 def __init__ 函数下面，不知道对不对，但是也可以正常使用

![QQ20240929-200150](https://github.com/user-attachments/assets/2b74abc3-4c88-4ade-bf3a-f84e330c388b)

**Comment by 258692011** [comment]
> 你自己修改吧，代码功能我已经测试过了
> 
> 1. 以下代码添加到 widgets/mainwindows.py最后
> 
> ```python
> def add_extra_shortcut(self):
>         self.extra_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("X"), self) # 这个X是快捷键，自己可以随便改，别和软件快捷键冲突就行
>         self.extra_shortcut.setContext(QtCore.Qt.ApplicationShortcut)
>         self.extra_shortcut.activated.connect(self.extra_func)
> 
>     def extra_func(self):
>         self.scene.finish_draw() # E
>         self.save()# S
>         self.next_image() # D
>         self.scene.start_segment_anything() # Q
> ```
> 
> 2. 在widgets/mainwindows.py的__init__函数最后，添加
> 
> ```python
>         self.add_extra_shortcut()
> ```

widgets/mainwindows.py的def __init__ 函数有很多个，
self.add_extra_shortcut() 我添加到 class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow): 类里面的 def __init__ 函数下面，不知道对不对，但是也可以正常使用

![QQ20240929-200447](https://github.com/user-attachments/assets/1a3195ff-78db-4ec1-8ec1-017b4350fe3c)
