### ISSUE TITLE
pyqt5版本

### ISSUE THREAD

**Issue by l-cr** [yatengLG/ISAT_with_segment_anything#109]
想请问一下pyqt5用的什么版本

> Traceback (most recent call last):
  File "ISAT_with_segment_anything/ISAT/widgets/switch_button.py", line 76, in paintEvent
    self.drawSlider(evt, painter)
  File "ISAT_with_segment_anything/ISAT/widgets/switch_button.py", line 123, in drawSlider
    sliderRect = QRect((self.startX + self.space), (self.space), sliderWidth, sliderWidth)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'

**Comment by yatengLG** [comment]
我这边用的  5.17.5

**Comment by yatengLG** [comment]
另外，这个报错是因为这一行
https://github.com/yatengLG/ISAT_with_segment_anything/blob/f0d4dbf71d0143eec81831fb421677bb3131ad98/ISAT/widgets/switch_button.py#L123


如果换了版本还是无法解决，或者懒得换版本了，直接改成下面代码，应该也可以解决
```python
 sliderRect = QRect(int(self.startX + self.space), int(self.space), int(sliderWidth), int(sliderWidth)) 
```

**Comment by l-cr** [comment]
> 另外，这个报错是因为这一行
> 
> https://github.com/yatengLG/ISAT_with_segment_anything/blob/f0d4dbf71d0143eec81831fb421677bb3131ad98/ISAT/widgets/switch_button.py#L123
> 
> 如果换了版本还是无法解决，或者懒得换版本了，直接改成下面代码，应该也可以解决
> 
> ```python
>  sliderRect = QRect(int(self.startX + self.space), int(self.space), int(sliderWidth), int(sliderWidth)) 
> ```

好的，谢谢，问题解决了
