### ISSUE TITLE
关于单通道图片读取问题

### ISSUE THREAD

**Issue by Lucky-hqj** [yatengLG/ISAT_with_segment_anything#11]
大佬，你好！我是一个语义分割的小白，我想请问一下你说的标注单通道图片，在程序中应该用什么读取，我用cv读取不也是三通道的图片吗

**Comment by Lucky-hqj** [comment]
不太理解，如何读出像素值，我读出来的都是三通道的？

**Comment by yatengLG** [comment]
> 不太理解，如何读出像素值，我读出来的都是三通道的？

cv2会默认把图片转成三通道

```python
from PIL import Image
import numpy as np

file = 'example/instance/000000000113.png'
image = np.array(Image.open(file))
print(image.shape)

import cv2
image_cv2 = cv2.imread(file)
print(image_cv2.shape)

>>>(640, 416)
>>>(640, 416, 3)
```

**Comment by yatengLG** [comment]
> > 不太理解，如何读出像素值，我读出来的都是三通道的？
> 
> cv2会默认把图片转成三通道
> 
> ```python
> from PIL import Image
> import numpy as np
> 
> file = 'example/instance/000000000113.png'
> image = np.array(Image.open(file))
> print(image.shape)
> 
> import cv2
> image_cv2 = cv2.imread(file)
> print(image_cv2.shape)
> 
> >>>(640, 416)
> >>>(640, 416, 3)
> ```

软件保存的png你也看出来了，是彩图，但的确是单通道保存的。
图片文件里面，有一个像素矩阵，[h, w]，另外还有一个保存每个像素对应颜色的字段，可以理解为有一个颜色对应的字典，比如像素值2，在字典里面对应的颜色是(0， 128， 0)，所以可以使用单通道表示彩图。

cv2读取的时候，会把这个直接转换成三通道图[h, w, 3]

**Comment by wxmchgithub** [comment]
cv2要以灰度图的形式读取，才是单通道

**Comment by Lucky-hqj** [comment]
> > > 不太理解，如何读出像素值，我读出来的都是三通道的？
> > 
> > 
> > cv2会默认把图片转成三通道
> > ```python
> > from PIL import Image
> > import numpy as np
> > 
> > file = 'example/instance/000000000113.png'
> > image = np.array(Image.open(file))
> > print(image.shape)
> > 
> > import cv2
> > image_cv2 = cv2.imread(file)
> > print(image_cv2.shape)
> > 
> > >>>(640, 416)
> > >>>(640, 416, 3)
> > ```
> 
> 软件保存的png你也看出来了，是彩图，但的确是单通道保存的。 图片文件里面，有一个像素矩阵，[h, w]，另外还有一个保存每个像素对应颜色的字段，可以理解为有一个颜色对应的字典，比如像素值2，在字典里面对应的颜色是(0， 128， 0)，所以可以使用单通道表示彩图。
> 
> cv2读取的时候，会把这个直接转换成三通道图[h, w, 3]

明白了，谢谢大佬，我搞清楚了。大佬，如果我用了这个软件进行标注，在论文里如何引用呀？
