### ISSUE TITLE
客户端运行时，置顶or置底mask的时候，有存在闪退的可能，已经遇到5-6次

### ISSUE THREAD

**Issue by zidddd9527** [yatengLG/ISAT_with_segment_anything#110]
客户端运行时，置顶or置底mask的时候，有存在闪退的可能，已经遇到5-6次

**Comment by yatengLG** [comment]
打包的exe嘛？

**Comment by zidddd9527** [comment]
> 打包的exe嘛？

是的

**Comment by yatengLG** [comment]
打包的exe，版本比较旧了。

建议跑源码或者pip安装，这个问题已经被修复了

**Comment by zidddd9527** [comment]
exe方便，我的源码版本是老版本，更新的话要重新配置（之前更新的时候，变成cpu运行，和您反应过，我又重新配置pytorch解决，这一通折腾还挺麻烦）

**Comment by yatengLG** [comment]
直接拉最新的代码就可以了，依赖基本没动。

上次那是因为自动装了pytorch的cpu版本，windows需要手动安装pytorch，pip默认安装的是cpu版本。

**Comment by zidddd9527** [comment]
试了一下。。。。又要重新配置pytorch，算了，谢谢您
