### ISSUE TITLE
参数格式错误

### ISSUE THREAD

**Issue by BoFan-tunning** [yatengLG/ISAT_with_segment_anything#111]
python main.py
Traceback (most recent call last):
  File "F:\yolo\ISAT_with_segment_anything\ISAT\widgets\switch_button.py", line 78, in paintEvent
    self.drawText(evt, painter)
  File "F:\yolo\ISAT_with_segment_anything\ISAT\widgets\switch_button.py", line 85, in drawText
    painter.drawText(0, 0, self.width() / 2 + self.space * 2, self.height(), Qt.AlignCenter, self.textOn)
TypeError: arguments did not match any overloaded call:
  drawText(self, p: Union[QPointF, QPoint], s: Optional[str]): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, flags: int, text: Optional[str]): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRect, flags: int, text: Optional[str]): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, text: Optional[str], option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, p: QPoint, s: Optional[str]): argument 1 has unexpected type 'int'
  drawText(self, x: int, y: int, width: int, height: int, flags: int, text: Optional[str]): argument 3 has unexpected type 'float'
  drawText(self, x: int, y: int, s: Optional[str]): argument 3 has unexpected type 'float'

**Comment by yatengLG** [comment]
https://github.com/yatengLG/ISAT_with_segment_anything/issues/109

**Comment by yatengLG** [comment]
你也可以拉最新的代码，现在实现上更严谨了。
