### ISSUE TITLE
请问为什么转换成labelme格式后，软件界面显示转换完成但结果却什么都没有啊？

### ISSUE THREAD

**Issue by zr905642583** [yatengLG/ISAT_with_segment_anything#113]

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-3Q3BG2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/37298267-5b67-4a62-b944-8ee26d1368e2)
![gnome-shell-screenshot-GZODG2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/1fa8b8a2-35db-49ae-a56f-3876c41f4d52)

**Comment by yatengLG** [comment]
我这边是没问题的，如果你那边还有问题，可以排查下。

如果解决不了，也可以直接用转换脚本，这里有使用例子https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/example/convert/convert.ipynb
