### ISSUE TITLE
标注后转COCO的json格式包含了所有类别

### ISSUE THREAD

**Issue by DIANSLEE** [yatengLG/ISAT_with_segment_anything#115]
观察过代码本身是不应该包含所有类别的，应该是只有标注过的类别，在实际转换过程中时而包含所有类别，时而包含标注的类别。搞半天搞不清楚了，手动把不需要的类别都删了...不清楚怎么回事

**Comment by yatengLG** [comment]
和你保存标注的文件夹下的isat.yaml有关。

**Comment by DIANSLEE** [comment]
我是23年10月12号下载的，还没有这个converter_dialog.py, 但是但看这个isat to coco看不出来哈哈我很菜，可能应该更新下、
![1](https://github.com/yatengLG/ISAT_with_segment_anything/assets/71864438/54930128-e7c3-4bd2-b52c-12da441d9208)

**Comment by yatengLG** [comment]
可以watch这个项目，持续更新中，更新了会自动发通知。

**Comment by yatengLG** [comment]
> 我是23年10月12号下载的，还没有这个converter_dialog.py, 但是但看这个isat to coco看不出来哈哈我很菜，可能应该更新下、 ![1](https://private-user-images.githubusercontent.com/71864438/294121884-54930128-e7c3-4bd2-b52c-12da441d9208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNTc4MDQsIm5iZiI6MTcwNDM1NzUwNCwicGF0aCI6Ii83MTg2NDQzOC8yOTQxMjE4ODQtNTQ5MzAxMjgtZTdjMy00YmQyLWI1MmMtMTJkYTQ0MWQ5MjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA4MzgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MmU4MDliNTU3Mzc3YWVmOGQwZjNhZGZmODRkODFkY2M3NjQzOTI3NGM0NGM2ZDQ2N2NhYTcyNDI4OTNjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8QzgXGO7a18d4n8tudAEOq0bcy910MMYSB5jzqfyHQ)

这个是之前的版本，后面更新了新的转换界面。添加了coco,yolo,labelme与isat相互转换的功能，也添加了其他一些转换功能。后面还会持续更新，降低显存占用以及提升计算速度等。

**Comment by DIANSLEE** [comment]
感谢回复
