### ISSUE TITLE
SAM not support the image

### ISSUE THREAD

**Issue by Joneedhome** [yatengLG/ISAT_with_segment_anything#116]
![20240104151555](https://github.com/yatengLG/ISAT_with_segment_anything/assets/39737773/0538adee-4979-47c8-8f64-02fd1f116104)

这是什么原因

**Comment by yatengLG** [comment]
提示是，输入的tensor维度不对。

应该和你输入的图像维度有关。你先确认下你图像维度。
sam只支持三通道图片

**Comment by TianchouYin** [comment]
> 提示是，输入的tensor维度不对。
> 
> 应该和你输入的图像维度有关。你先确认下你图像维度。 sam只支持三通道图片

sam不止支持三通道，在sam官网试了单通道灰度图可以分割，但是在isat里不行

**Comment by TianchouYin** [comment]
> ![20240104151555](https://private-user-images.githubusercontent.com/39737773/294111183-0538adee-4979-47c8-8f64-02fd1f116104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTY5ODIsIm5iZiI6MTcwODQxNjY4MiwicGF0aCI6Ii8zOTczNzc3My8yOTQxMTExODMtMDUzOGFkZWUtNDk3OS00N2M4LThmNjQtMDJmZDFmMTE2MTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA4MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOGI0NTE2NDI4YjI2ZmQzMzczNTczYWFkMjU0NDBlNDNiMzc2NjMyOGE3ODkwNzNjNGM5MTMxYzdjYTFhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8UU6ZxlQiribyd4yPp326P7WU5iB31xWi7ZkMjyp4B8)
> 
> 这是什么原因

怎么解决啊，灰度图就不能标注了吗
