### ISSUE TITLE
目前软件提供了模型管理界面，由于sam-hq与mobile-sam的权重链接需要科学上网才可以访问。因而管理界面下载这两类模型会经常失败。有能提供国内比较好用的大文件托管服务，可以与我联系。

### ISSUE THREAD

**Issue by ZS-YANG** [yatengLG/ISAT_with_segment_anything#118]
可以考虑使用百度的[飞桨AI Studio](https://www.baidu.com/link?url=q9eH5s1zVmnHN1rFunVPHUAppt9sdCK2laT35mQiqSx0VGN7ob_k4y6oAsLlcYtb5az69y0edYjUQCaeFj3jNq&wd=&eqid=e07d0d79004187a900000005659e2f2d)平台进行数据集存储。
这个平台免费且不限速。
例如SAM-HQ预训练权重  https://aistudio.baidu.com/datasetdetail/250434

**Comment by yatengLG** [comment]
非常感谢O(∩_∩)O，后续我更新下下载链接

**Comment by ZS-YANG** [comment]
要是方便的话可以引用下我的这个链接：https://aistudio.baidu.com/datasetdetail/250434 给我增加以下积分，哈哈哈😁

**Comment by yatengLG** [comment]
> 要是方便的话可以引用下我的这个链接：https://aistudio.baidu.com/datasetdetail/250434 给我增加以下积分，哈哈哈😁

会优先把你这个链接放第一位的，但是为了保证软件下载没问题，也会补第二下载链接。O(∩_∩)O

**Comment by yatengLG** [comment]
这个不太行，需要那种不登录可以直连下载的。

这个需要登录后才可以T.T

**Comment by ZS-YANG** [comment]
wget https://bj.bcebos.com/v1/ai-studio-online/f61e8f8e7356431eaa26c023e21f516b835ad0f1671a4e6b8d091bfaf4aeb2c2?responseContentDisposition=attachment%3B%20filename%3Dsam_hq_vit_tiny.pth
 你试下这个链接可以下载吗
 链接是从这里右键复制下载链接得到的
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/52490943/5d8b6f2f-34ea-42ca-93e2-4d295636bc5c)
但是不知道这个链接的有效期是多久

**Comment by ZS-YANG** [comment]
或者试下魔塔 https://www.modelscope.cn/home

**Comment by yatengLG** [comment]
> 或者试下魔塔 https://www.modelscope.cn/home

魔塔没问题，在新版代码中已经添加了魔塔的链接。现在国内也可以直接通过界面下载模型了

**Comment by ZS-YANG** [comment]
thx，效率真高🚀
