### ISSUE TITLE
GPU识别不到

### ISSUE THREAD

**Issue by caixiongjiang** [yatengLG/ISAT_with_segment_anything#12]
我用的是RTX3060(12G),每次运行项目都显示是cpu。是否是pytroch版本太低的缘故？

**Comment by yatengLG** [comment]
先确定看下torch能不能调用gpu。window下，默认安装的是cpu版本的torch

**Comment by caixiongjiang** [comment]
解决了，我的Cuda版本是10.2，不支持RTX3060，升级到11.1就可以了
