### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute 'seganythread'

### ISSUE THREAD

**Issue by ImcwjHere** [yatengLG/ISAT_with_segment_anything#121]
原版代码，直接运行main.py，打开图片文件夹后报错如下：

(py311) D:\ISAT>python main.py
Traceback (most recent call last):
  File "D:\ISAT\ISAT\widgets\mainwindow.py", line 453, in open_dir
    self.seganythread.wait()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'seganythread'

**Comment by yatengLG** [comment]
实在不好意思，最近的一次更新出的bug。
现在已经修复了，拉取最新的代码即可。
