### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by wst2003** [yatengLG/ISAT_with_segment_anything#124]
报错信息：
(base) C:\Users\33044\AppData\Roaming\Python\Python311\Scripts>isat-sam
Traceback (most recent call last):
  File "C:\Users\33044\AppData\Roaming\Python\Python311\site-packages\ISAT\widgets\switch_button.py", line 78, in paintEvent
    self.drawText(evt, painter)
  File "C:\Users\33044\AppData\Roaming\Python\Python311\site-packages\ISAT\widgets\switch_button.py", line 85, in drawText
    painter.drawText(0, 0, self.width() / 2 + self.space * 2, self.height(), Qt.AlignCenter, self.textOn)
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRect, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, QPoint, str): argument 1 has unexpected type 'int'
  drawText(self, int, int, int, int, int, str): argument 3 has unexpected type 'float'
  drawText(self, int, int, str): argument 3 has unexpected type 'float'

**Comment by yatengLG** [comment]
1. 这个是pyqt的报错，drawText这个输入的参数应该是int，但是输入了float。
     应该是qt版本造成的。
2. 这个问题之前就已经修复过了，你拉取最新的代码就好了
