### ISSUE TITLE
可否增加对一些医学SAM的支持

### ISSUE THREAD

**Issue by waynesun2023** [yatengLG/ISAT_with_segment_anything#128]
在B站看过UP的视频，这个软件做的非常好。官方基于H5，或者streamlit，gradio的实际是没法用来当生产力工具的，你这个可以。但是专业领域的模型是否可以考虑支持，比如医学分割，https://github.com/OpenGVLab/SAM-Med2D，我看论文里模型加了一些adapter结构，不知是否可以实现，谢谢！

**Comment by yatengLG** [comment]
你可以star了本项目，然后等后续更新，更新以后我也会第一时间回复本issue。

你推荐的这个医学sam模型，我需要下载调试完才能添加，等我下载完checkpoint后，应该很快就可以更新的。

**Comment by waynesun2023** [comment]
感谢回复！大神给力！

**Comment by yatengLG** [comment]
> 感谢回复！大神给力！

他这代码也太乱了，很多没有必要的更改。。。没法直接集成进去，暂时没时间改他代码。

你可以自己尝试添加：
1. 将你推荐的这个项目的sam代码，复制到ISAT文件夹下
2. 在ISAT/segment_any中，导入项目对应的sam_model_registry和SamPredictor
3. sam的特征提取逻辑在 ISAT/widgets/mainwindow.py中，第43行，你需要把你推荐的这个项目的处理，还原为原始sam的实现。具体代码在segment_anything_med2d/predictor_sammed.py的第19行开始（改的太乱了，但是什么也没做，我也不知道一个数据增强为什么要改这么复杂。T.T 你需要做的就是保留他resize和减均值除方差的基础上，是还原到原始sam的处理流程即可）

**Comment by yatengLG** [comment]
> 感谢回复！大神给力！

你拉最新的代码吧，已经添加了。

**Comment by yatengLG** [comment]
> > 感谢回复！大神给力！
> 
> 你拉最新的代码吧，已经添加了。

**Comment by waynesun2023** [comment]
辛苦了，非常感谢！
