### ISSUE TITLE
无法打开jpg图片

### ISSUE THREAD

**Issue by shiwangyan** [yatengLG/ISAT_with_segment_anything#130]
大佬你好，我尝试了源码和pip安装两种方式运行
两种方法运行后，都无法打开图片格式为jpg的文件夹，也没有任何的报错
其他格式比如png可以打开

**Comment by yatengLG** [comment]
你可以把遇到的问题，和解决方式在这里简单说明一下。
这样其他人遇到这个问题就可以参照你的解决方式处理了。


O(∩_∩)O，如果遇到其他问题或者其他一些建议，欢迎随时联系。

**Comment by shiwangyan** [comment]
问题已解决
把下载的源码删掉，重新下载一遍就好了了

**Comment by shiwangyan** [comment]
重新试了一下，问题出在运行方式上
如果打开pycharm运行main.py，可以正常打开jpg图片
如果在cmd中输入 `python main.py` 运行，就无法打开jpg图片

**Comment by shiwangyan** [comment]
我是打开代码文件夹，然后在路径输入 `cmd` 打开系统自带的命令行，然后输入 `python main.py` ，程序可以运行，但是不能打开jpg图片
我试了一下anaconda的cmd，可以正常打开jpg图片
