### ISSUE TITLE
有无增加bounding box 作为标注prompt的更新计划？

### ISSUE THREAD

**Issue by lichen14** [yatengLG/ISAT_with_segment_anything#131]
作者您好，我试用了ISAT，很赞，但是没有找到bounding box 的标注prompt，请问近期有无对它的更新计划？
我们有一批数据集，只有box的label，希望能用您这个工具实现分割。

**Comment by yatengLG** [comment]
使用bounding box作为提示的标注方式，暂时不考虑添加，主要原因是这样的：
1. 从交互的方面来讲，点提示会比框提示更方便。点提示可以多次点提示修正当前mask，框提示与语言提示不具备这个特性。
2. 框提示与语言提示，更适用于做一个自动脚本。即使软件添加了框提示的功能，使用本软件，您也得手动重新绘制bounding box来生成mask。

对于您这个需求，近期我可以更新一个功能：输入图像目录与标签目录（例如目标检测voc格式的xml），自动转换为isat格式的json。自动转换后的mask可能会存在问题，然后您使用ISAT进行检查与修改。您看这个功能是否更符合您的需求？

**Comment by lichen14** [comment]
感谢您及时的回复！
对于您回复的1&2，我们非常认同，点提示的优势无与伦比。

对于您回复的更新功能，我理解的意思是：我准备好图像&VOC格式的bounding box标签xml，然后软件会转换为isat格式的json，并自动分割得到mask？虽然这个mask可能存在问题，需要人工再检查一遍？
如果是这个意思的话，我们非常乐意看到您对此的更新！
谢谢

此外，针对点提示的分割结果，我目前仍是右键点击去消除误分割的区域，有无类似“橡皮擦”的功能去范围性的擦除错误区域？

**Comment by yatengLG** [comment]
准备更新的功能是和您的理解一致，大概这周就可以更新这个功能。

对于点提示的错误区域，现阶段只能通过右键去进行负提示。
"橡皮擦"功能之前有过这方面的准备，但最终没有使用。主要是考虑到如过添加这个功能的话，就需要在交互式标注工作流中添加一个额外的操作，但是这个操作并不常用。

对于常见情况，多次提示就可以获得较好的mask；另外选用合适的模型也可以提高mask质量；对于极端情况，软件也提供了手动框选多边形的功能。

**Comment by yatengLG** [comment]
基于bounding box的自动分割功能已经添加了。

你可以在菜单栏-工具-自动分割 打开界面使用。

需要注意的是，最终的效果分割效果和两个功能有关：1. 轮廓模式，这个影响最终哪些轮廓会被转换为多边形，建议选择【只保存外轮廓]；2. use_polydp，这个功能可以简单理解为最终多边形顶点的密度。

1. 轮廓模式 在[菜单栏]-[模式]中选择
2.  use_polydp 在[工具栏]-[approx polygon] 进行切换

**Comment by lichen14** [comment]
收到，我这就尝试一下，感谢快速回复更新 [赞👍]

**Comment by lichen14** [comment]
您好，我git了 最新release的版本，有几个问题跟您反馈一下

1. 新版本更新的功能《菜单栏-工具-自动分割》，会报错Sam error when encoding image: CUDA error: CUBLAS STATUS NOT SUPPORTED when calling 'cublasGemmStridedBatchedExFix……'，我这里上传的是官方的VOC 2012数据集，数据格式应该没错~
![1710385573719](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/cd33f187-de9f-4f33-95d4-552655a0b89f)

2. 新版本不用“自动分割”功能时，也有点问题，我打开一张图片，不论是jpg或是Png，均会报错，如下图所示，我使用的是repo里自带的example
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/147f8e4b-3085-469e-8d9e-4d42ad040d96)

还是感谢您的回复和更新 👍

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-KS3PK2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/147172e3-97c9-44fd-9441-47042e5eb77a)


我这边不论是源码还是pip包，都没有问题。

应该是环境的问题。

**Comment by yatengLG** [comment]
![](https://private-user-images.githubusercontent.com/31759824/309777946-e9acba67-55d6-4139-a472-4ad4ede02309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODg4MzAsIm5iZiI6MTcxMDM4ODUzMCwicGF0aCI6Ii8zMTc1OTgyNC8zMDk3Nzc5NDYtZTlhY2JhNjctNTVkNi00MTM5LWE0NzItNGFkNGVkZTAyMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTg2NTc4NmYxMTk2NmQ1MGQ1YWI1ZjgwNzk0YWQ4OWQyMDg4MjY4NzgxY2M5NjA5YzZmYTk0ZDI0ZmI3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9FuQbOxe3Br5iNDpdfwY_8ze7HNTNcs3cRX0ycHs1E)

这个是我的conda环境

**Comment by lichen14** [comment]
> ![](https://private-user-images.githubusercontent.com/31759824/309777946-e9acba67-55d6-4139-a472-4ad4ede02309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODg4MzAsIm5iZiI6MTcxMDM4ODUzMCwicGF0aCI6Ii8zMTc1OTgyNC8zMDk3Nzc5NDYtZTlhY2JhNjctNTVkNi00MTM5LWE0NzItNGFkNGVkZTAyMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzNTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTg2NTc4NmYxMTk2NmQ1MGQ1YWI1ZjgwNzk0YWQ4OWQyMDg4MjY4NzgxY2M5NjA5YzZmYTk0ZDI0ZmI3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9FuQbOxe3Br5iNDpdfwY_8ze7HNTNcs3cRX0ycHs1E)
> 
> 这个是我的conda环境

conda环境列表没显示 😂

**Comment by yatengLG** [comment]
解决了嘛？

你现在这个报错大概率是因为torch和cuda版本不兼容导致的。需要检查下安装的cuda版本与torch的cuda版本是否一致。

因为只是添加了功能，不会改之前的代码的。从git记录里面也可以看出来，只是添加了一些自动分割的代码，并把原先sam的box提示部分修改了一行，其余都没动。

**Comment by lichen14** [comment]
谢谢解答，我还在尝试中。
cuda版本与torch的cuda版本不一致的话，我使用2天前的版本就没报错😂，这是为什么呢

**Comment by lichen14** [comment]
您好，我重新调整了torch和cuda版本，1.12.0+cu113，这二者应该是兼容的了。
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/b39747e4-5490-4829-bed8-66c0a7db8182)

但是仍然是原来的报错：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/7c392755-a349-491e-8609-116c244c42fe)


不过我看您提供的requirement是要求torch>=2.1.1，您看是否有必要？

**Comment by lichen14** [comment]
您好，我重新调整了torch和cuda版本，1.12.0+cu113，这二者应该是兼容的了。
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/b39747e4-5490-4829-bed8-66c0a7db8182)

但是仍然是原来的报错：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/7c392755-a349-491e-8609-116c244c42fe)


不过我看您提供的requirement是要求torch>=2.1.1，您看是否有必要？

**Comment by lichen14** [comment]
WOW，感谢回复，实测“在模型管理界面，有个use_bfloat16功能，把那个关了试一下”有效！
再次感谢作者的耐心回复
