### ISSUE TITLE
无法保存图片

### ISSUE THREAD

**Issue by miemieshizuka** [yatengLG/ISAT_with_segment_anything#135]
大佬您好！
我试用了ISAT，前几天没有问题一切都很完美。
但是突然数据转换不能用了。
我操作了数据转换后提示是下面这样
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/69880386/dc02a18e-11a4-490b-bd88-fa9132a1d95c)
然后只输出了一个空的classfication.txt，其他没有任何文件输出到我选择的路径里
请问这是什么问题？该如何解决?
谢谢大佬

**Comment by yatengLG** [comment]
大概率是使用问题，你看下你第一个json文件夹下，有没有ISAT的json啊。0.0

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-OLWKK2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/83cfd348-c15a-46a0-9546-c84aa83b0b79)

如果正常情况，会打印进度。

先读取目录下的ISAT 格式json，然后再转换为png。你这个流程就是没有发现json导致的，所以就是文件夹选择错误了。

**Comment by miemieshizuka** [comment]
原来如此。
第一个路径是保存了ISAT json文件的路径的意思，
我以为是要输出JSON文件。
完美解决了，谢谢大佬！！！鞠躬！

**Comment by yatengLG** [comment]
> 原来如此。 第一个路径是保存了ISAT json文件的路径的意思， 我以为是要输出JSON文件。 完美解决了，谢谢大佬！！！鞠躬！

你可以把界面转成中文的，我记得有说明的。

菜单栏-帮助-语言-中文
