### ISSUE TITLE
问题：在SAM标注模式下，无法一次性保存同一个分组的mask

### ISSUE THREAD

**Issue by zhudongming** [yatengLG/ISAT_with_segment_anything#136]

**Comment by zhudongming** [comment]
在SAM标注模式下，对于很多不连续的物体，例如一个被其他物体遮挡的人，通过点提示可以很高效的检测出属于同一个group的多个mask，但是在点击快捷键E表示标注完成时，却只保存了这一组mask的其中1个mask，如果想加入改分组的其他mask，需要多次提示标注，并手动修改group id。这样标注效率会大大的降低。

**Comment by yatengLG** [comment]
菜单栏-模式-轮廓模式 中有轮廓保存选项，可以完美解决你的问题。

有的问题可以查之前的issue，基本都有解答，毕竟大半年的软件了，遇到的问题基本就是使用问题或者环境问题了。
然后如果好用的话，可以给一个star，谢谢。

**Comment by zhudongming** [comment]
太感谢了！

**Comment by zhudongming** [comment]
这是我使用过的效率最高的半自动化标注工具
