### ISSUE TITLE
可以提供一个圆形标注吗？

### ISSUE THREAD

**Issue by pcycccccc** [yatengLG/ISAT_with_segment_anything#138]
首先很感谢大佬提供该项目，我在使用的过程中很明显感觉加快了我标注的速度，但我有个小小的提议，不知道大佬能否在后续中考虑这方面的优化。实际视觉的项目中，一般是对直线、直角、圆形进行标注，大部分项目是对销钉、or圆孔（也就是圆形的物体）进行识别，在边缘对比度很高的情况下，使用该分割工具能很快进行分割标注，但是很多边缘对比度不高的需要我们手动去画点标注，人为手动画点标注出来的圆形是比较没那么规整的，即便能够近似圆，这也是比较费时费力的事情，如果您这边能够提供画圆形（or椭圆）的分割，相信对很多有这方面分割需求的人来说是锦上添花。

**Comment by yatengLG** [comment]
暂时不考虑添加这个功能，主要关注的方向不一样。
