### ISSUE TITLE
Can't run under GPU

### ISSUE THREAD

**Issue by ZKY6662017** [yatengLG/ISAT_with_segment_anything#14]
While running the main.py, there always shows 'CPU' under the window, I tried to reinstall the torch, but it still is under 'CPU' mode. It's running slow in this mode. How could I switch to GPU mode?

**Comment by yatengLG** [comment]
please insure torch can be used with GPU.

```python
torch.cuda.is_available()
```

**Comment by yatengLG** [comment]
If you system platform is windows, you should install torch by 'https://pytorch.org/get-started/locally/', rather than ```pip install torch```

**Comment by ZKY6662017** [comment]
Thanks for your replay. The issue is still there, I used that link to install the troch , the cuda.is_available() is still 'False'

**Comment by yatengLG** [comment]
Maybe you should check the cuda version to match your GPU.
