### ISSUE TITLE
Pyinstaller打包exe问题

### ISSUE THREAD

**Issue by lichen14** [yatengLG/ISAT_with_segment_anything#140]
作者您好，我在终端使用python main.py能够正常使用ISAT的标注功能。
在使用`pyinstaller -F main.py -w`，能够正常打包exe：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/2a33efb0-260c-4df5-91e5-43471bc1a8a8)

但是打开exe文件后报错：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/25859465/a0d9bbc6-2306-41f0-9383-1ce3f61b0e57)

另外，还想请教一下，此版本打包的exe文件很大，2.5G，有无办法让我缩减一下大小？我是新建的conda环境了，应该没有多余的无关的包。

谢谢作者！

**Comment by yatengLG** [comment]
一个torch就2.5G了，没办法。

另外，pyinstaller用-D，因为会有需要的配置文件等，还有资源文件，还有翻译文件等等等。用-F即使打成一个exe，还得做一个目录放，不如直接-D打包成文件夹。

至于贴图里的问题，就是没找到配置文件。打包过程中应该还会遇到其他缺python包问题，缺啥加啥就行。

**Comment by suren1986** [comment]
> 作者您好，我在终端使用python main.py能够正常使用ISAT的标注功能。 在使用`pyinstaller -F main.py -w`，能够正常打包exe： ![image](https://private-user-images.githubusercontent.com/25859465/313899906-2a33efb0-260c-4df5-91e5-43471bc1a8a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTE2NjgsIm5iZiI6MTcxMzc5MTM2OCwicGF0aCI6Ii8yNTg1OTQ2NS8zMTM4OTk5MDYtMmEzM2VmYjAtMjYwYy00ZGY1LTkxZTUtNDM0NzFiYzFhOGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEzMDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjQ4ZThjNTM5ODc1NTZjMzNlNDMzODNlYzk0NzU0NDRiNWMwZTQ4NTA3ZGYxN2JkYjYyODVkMWY4Zjg3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULpF-wmpEGvyAnuG_nGzMeOwEIEoqy9QoI17yro98VA)
> 
> 但是打开exe文件后报错： ![image](https://private-user-images.githubusercontent.com/25859465/313899959-a0d9bbc6-2306-41f0-9383-1ce3f61b0e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTE2NjgsIm5iZiI6MTcxMzc5MTM2OCwicGF0aCI6Ii8yNTg1OTQ2NS8zMTM4OTk5NTktYTBkOWJiYzYtMjMwNi00MWYwLTkzODMtMWNlM2Y2MWIwZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEzMDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMzZlNDA1MGUyNWZkNDE4Zjg1YTYxNDk3MDA2Yjg4OGNlMWY4MWJjZmNhYmJiZjllN2YxMzljMTQ0NzcxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AHoPng5V5m7q2YEzInCQSIeYXvqIVIrevJbaJQPe46s)
> 
> 另外，还想请教一下，此版本打包的exe文件很大，2.5G，有无办法让我缩减一下大小？我是新建的conda环境了，应该没有多余的无关的包。
> 
> 谢谢作者！

./ISAT/下有 2 个文件 `isat.yaml` 和 `software.yaml`，复制到 dist/main/_internal/ISAT 下就行了

**Comment by zhouyang986** [comment]
torch就挺大的了啊哈哈

想要缩小体积可以考虑用onnxruntime推理？
不过.onnx总感觉不如torch的.pth文件准确😂
