### ISSUE TITLE
批量修改标签

### ISSUE THREAD

**Issue by Wazxcvb** [yatengLG/ISAT_with_segment_anything#141]
你好，想请问一下批量修改标签的操作应该如何实现？
![1710834708275](https://github.com/yatengLG/ISAT_with_segment_anything/assets/43949204/e4df65fe-3ed7-4b9f-82e3-97f77e957904)

**Comment by yatengLG** [comment]
category_edit_dialog.py自己改吧。

顺便好用的话给个star，谢谢
