### ISSUE TITLE
sam使用cuda推理时程序奔溃 

### ISSUE THREAD

**Issue by 1qingfeng-1** [yatengLG/ISAT_with_segment_anything#146]
报 floating point exception (core dumped)
debug 显示Mainwindow->show_image() 第626行奔溃
```py
if self.use_segment_anything and self.can_be_annotated:
    self.segany.reset_image()
    self.seganythread.index = index
    self.seganythread.start()     // 断点 626行这一行奔溃
    self.SeganyEnabled()
```
如果使用CPU，屏蔽GPU export CUDA_VISIBLE_DEVICES=""
运行程序是正常的，你能请修复这个错误，或者提供一些线索

最新，定位到奔溃点 mainwidow.py->sam_encoder
```py
features = self.mainwindow.segany.predictor_with_point_prompt.model.image_encoder(input_image)
```

**Comment by yatengLG** [comment]
你打开 [菜单栏] - [sam] - [模型管理]，把use_bfloat16关闭试一下（取消勾选）。

**Comment by 1qingfeng-1** [comment]
没有运气，提示
Error: GET was unable to find an engine to execute this computation

**Comment by yatengLG** [comment]
环境问题，这个和软件代码没关系。
你新建一个conda环境跑应该就解决了。

另外，这种torch库的报错，很多都可以百度找到的。

**Comment by 1qingfeng-1** [comment]
> 环境问题，这个和软件代码没关系。 你新建一个conda环境跑应该就解决了。
> 
> 另外，这种torch库的报错，很多都可以百度找到的。
使用torch1.9.0，正常推理
```python
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```
