### ISSUE TITLE
exe安装的问题

### ISSUE THREAD

**Issue by FyeSJTU** [yatengLG/ISAT_with_segment_anything#147]
首先感谢作者提供代码！
我想用第三种方法安装在我的笔记本上（Windows）, 百度网盘下载好后是3个文件。
分别是ISAT_with_segment_anything_exe.zip.001， ISAT_with_segment_anything_exe.zip.002，ISAT_with_segment_anything_exe.zip.003
这三个文件后续如何操作呢？
我理解是把这三个文件分别解压缩到同一个文件下，但是002和003说压缩包不完整无法解压缩。
能讲一下具体的操作嘛？

**Comment by yatengLG** [comment]
如果要使用已经发布的exe，直接解压第一个压缩文件就好了（三个文件是分块打包的，其余两个会自动解压）。

目前的exe版本特别旧，很多功能缺失。建议使用源码会pip安装。
下月底应该会发布正式版本1.0.0，到时候会重新打包一个exe发布，欢迎关注本项目。

**Comment by beihai233** [comment]
您好，我是按照第一种方法安装的，是用GPU运行的。环境也配置好了，运行main文件出现的交互式界面，选择图片文件夹后，图片不在页面显示，您看我的交互式界面。这个问题该怎么解决？可以帮助一下吗？谢谢！
![BUG界面](https://github.com/user-attachments/assets/e1e8d77f-e17e-4640-b49e-60f6714ca8f0)

**Comment by yatengLG** [comment]
> 您好，我是按照第一种方法安装的，是用GPU运行的。环境也配置好了，运行main文件出现的交互式界面，选择图片文件夹后，图片不在页面显示，您看我的交互式界面。这个问题该怎么解决？可以帮助一下吗？谢谢！ ![BUG界面](https://private-user-images.githubusercontent.com/192427103/397933913-e1e8d77f-e17e-4640-b49e-60f6714ca8f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MjAwMjYsIm5iZiI6MTczNDkxOTcyNiwicGF0aCI6Ii8xOTI0MjcxMDMvMzk3OTMzOTEzLWUxZThkNzdmLWUxN2UtNDY0MC1iNDllLTYwZjY3MTRjYThmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwMjA4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGFhZjdlNWMyMGJlOWIwN2IzMmRjYjFkZDcyYmU2MDUwYTdkMmUxMmYzZWUxYTU2Y2Y2MjQzNGJiYjZiY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2I_VLSX0HuZQQXIl7_OM0gaA0VBgreY7NCaP18WKMo0)

应该是数据问题吧。
你先用提供的 数据测试下？  在example文件夹里面
