### ISSUE TITLE
保存单通道图像时没有保留原有空洞的问题

### ISSUE THREAD

**Issue by aitangbodan** [yatengLG/ISAT_with_segment_anything#15]
您好，现有保存的分割图像会自动填充有空洞的部分，但是在一些场景下要保留这些孔洞部分，比如
![youyong21f](https://user-images.githubusercontent.com/54161139/236407299-d19d2a79-c9aa-4b0f-8f69-295ccbb3e2a5.jpg)

可以更新下吗？谢谢！

**Comment by yatengLG** [comment]
需要镂空部分标一个背景，置于最顶层即可。

不会按照这个需求更新，原因如下:
1. 软件可以满足这种情况的标注需求，只需标注镂空部分为背景类即可。
2. 转多边形时，保留内部镂空区域是很简单的事情，但是多边形嵌套的区分会比较麻烦。
3. 如果按照你的需求改，当SAM分割完一个目标时，会转成多个多边形，对后续的检查与修改会带来极大的工作量。
4. 作为一个通用的标注工具，这样的修改会为其他标注工作带来额外的工作量。

如果你没有后续的修改需求，可以尝试更改如下部分的代码
https://github.com/yatengLG/ISAT_with_segment_anything/blob/f6f985b72c964d296e822f423c10d9c596eb5caa/widgets/canvas.py#LL164C17-L164C17

**Comment by TianchouYin** [comment]
> 您好，现有保存的分割图像会自动填充有空洞的部分，但是在一些场景下要保留这些孔洞部分，比如 ![youyong21f](https://user-images.githubusercontent.com/54161139/236407299-d19d2a79-c9aa-4b0f-8f69-295ccbb3e2a5.jpg)
> 
> 可以更新下吗？谢谢！

请问你是如何让isat支持灰度图的啊，我的不支持
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/63798894/0e5cac9a-b334-435f-8d7c-7d3c9b7db6e7)
