### ISSUE TITLE
RuntimeError: "upsample_bilinear2d_out_frame" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by kbqn20** [yatengLG/ISAT_with_segment_anything#151]
请问使用GPU跑的时候出现RuntimeError: "upsample_bilinear2d_out_frame" not implemented for 'BFloat16'的报错怎么办

**Comment by yatengLG** [comment]
应该是torch版本问题。

【菜单栏】-【模型管理】-【use bfloat16】关闭就好了

**Comment by kbqn20** [comment]
感谢！

**Comment by yatengLG** [comment]
> 感谢！

客气O(∩_∩)O
