### ISSUE TITLE
categories

### ISSUE THREAD

**Issue by cuigw1** [yatengLG/ISAT_with_segment_anything#152]
当标注时如果不是所有的类别都有标注，会出现问题，类别字典中不会包含所有的类别。但实际情况中可能出现没有某类标注的情况。之前是直接从isat.yaml中读取的，没有这个问题。

**Comment by yatengLG** [comment]
你说的这个问题应该也是数据转换相关的。

之前的确是从isat.yaml中直接读取的类别，现在是从标注中直接提取。
相比较之下，现在的方式更易使用，也可以尽可能的减少bug。
