### ISSUE TITLE
数据转换中json文件中标注数据累积问题

### ISSUE THREAD

**Issue by cuigw1** [yatengLG/ISAT_with_segment_anything#153]
如将isat标签转换为coco标签时，第一次选择目录后生成json文件没有问题，但是后续选择其它目录生成的json文件包含之前的结果，怀疑是之前的结果没有清除。在load_from_isat函数下添加self.annos.clear()可以避免这个问题。

**Comment by yatengLG** [comment]
非常感谢O(∩_∩)O

已经修复。
