### ISSUE TITLE
不能正确分割

### ISSUE THREAD

**Issue by littlebearsama** [yatengLG/ISAT_with_segment_anything#162]
![2024-05-13 22-42-31屏幕截图](https://github.com/yatengLG/ISAT_with_segment_anything/assets/14980666/0b0f02eb-4612-49ea-acb5-972ebbf32b94)

不能正确分割，这个是错误吗

环境：
1080TI
cuda12.1

**Comment by Alias-z** [comment]
> ![2024-05-13 22-42-31屏幕截图](https://private-user-images.githubusercontent.com/14980666/330100024-0b0f02eb-4612-49ea-acb5-972ebbf32b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTk2MjcsIm5iZiI6MTcxNTYxOTMyNywicGF0aCI6Ii8xNDk4MDY2Ni8zMzAxMDAwMjQtMGIwZjAyZWItNDYxMi00OWVhLWFjYjUtOTcyZWJiZjMyYjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE2NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3OGVlOWM2MTgwMjhhNWMzM2QzZWVkN2MzMjhjYzIwNmJjNzYyNGUzZGI5Nzk2NzcyNmJjODMzNzg4ZTNiZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CM5Mx7t4GMIaizO9owZYEiboXMtJ5LQmzgpcfaY03fU)
> 
> 不能正确分割，这个是错误吗
> 
> 环境： 1080TI cuda12.1

你好像打了三个点在车上作为正目标，试试右键几个背景点作为负目标呢 另外sam_vit_l不行可以试试sam_hq_vit_h的权重 可以用你的现存应该够的 不然用fp16模式运行

**Comment by yatengLG** [comment]
> ![2024-05-13 22-42-31屏幕截图](https://private-user-images.githubusercontent.com/14980666/330100024-0b0f02eb-4612-49ea-acb5-972ebbf32b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDk4MjIsIm5iZiI6MTcxNTY0OTUyMiwicGF0aCI6Ii8xNDk4MDY2Ni8zMzAxMDAwMjQtMGIwZjAyZWItNDYxMi00OWVhLWFjYjUtOTcyZWJiZjMyYjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAxMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZDZiMzljMmZjN2MzNmUyN2QwMTc1M2YxYWYxOTQyZmE1ZDM5ZTgzMTc5Mzg5OWRkY2Q5YmM2N2E2ZTNjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBpPPS8-h42UDceVTkAEhx7sI_KQWznNMlhUKu8F_xE)
> 
> 不能正确分割，这个是错误吗
> 
> 环境： 1080TI cuda12.1

环境问题，检查torch,cuda,cudnn的版本关系，这个网上可以自己查到的。
