### ISSUE TITLE
请问支持png格式转json吗？

### ISSUE THREAD

**Issue by Wst-sd** [yatengLG/ISAT_with_segment_anything#163]
有一种需求是直接将别的地方得到的png标签进行微调修改，但是没有json文件，请问软件有办法处理吗？

**Comment by yatengLG** [comment]
你这个需求是可以实现的，但软件暂时没有这个功能。

**Comment by Wst-sd** [comment]
已收到邮件，谢谢！

**Comment by zhouyang986** [comment]
我在尝试用Photoshop标注的时候，也想把png格式转json，然后失败了，哈哈。
但是你可以搜关键词，png转coco标注，什么的。
