### ISSUE TITLE
The possibility of separation of front and back ends

### ISSUE THREAD

**Issue by XZRRRRRR** [yatengLG/ISAT_with_segment_anything#17]
Since the project has large requirements for GPU and my server cannot use the graphical interface, I hope to separate the business and the graphical interface. Can the separation of the front and back ends be achieved? If so, what constructive comments would you have?Thanks for your open source.

**Comment by yatengLG** [comment]
ISAT can run without GPU, SAM must need GPU.

You can deploy SAM to GPU, the predict code on the line 371 of widgets/canvas.py
When you prompt by click mouse, calculate mask by GPU and return to ISAT for display(from line 372 to 389 of widgets/canvas.py).

Also you need set_image for SAM, the code on line 39 of widgets/canvas.py, there you need send image data to SAM for calculating mask

You can use HTTP for communication.

**Comment by XZRRRRRR** [comment]
Thanks for your help！
