### ISSUE TITLE
可以支持tif影像吗

### ISSUE THREAD

**Issue by jhrcws** [yatengLG/ISAT_with_segment_anything#170]

**Comment by yatengLG** [comment]
你可以邮件发我一张图片嘛，我可以试一下。

**Comment by jhrcws** [comment]
老师您好，附件是我的几张TIF影像，烦请您试下。我目前用的软件不支持tif。

另，我的目的是对水稻田中的正常水稻和受病水稻进行分割，当然无人机影像中还有水体、建筑、道路、林地等其他地物，请问，如果可以识别TIF的话，可以对影像中的这么多中地物进行分割吗？

麻烦您了




-----原始邮件-----
发件人:yatengLG ***@***.***>
发送时间:2024-06-04 11:13:24 (星期二)
收件人: yatengLG/ISAT_with_segment_anything ***@***.***>
抄送: jhrcws ***@***.***>, Author ***@***.***>
主题: Re: [yatengLG/ISAT_with_segment_anything] 可以支持tif影像吗 (Issue #170)






你可以邮件发我一张图片嘛，我可以试一下。

**Comment by yatengLG** [comment]
> 老师您好，附件是我的几张TIF影像，烦请您试下。我目前用的软件不支持tif。 另，我的目的是对水稻田中的正常水稻和受病水稻进行分割，当然无人机影像中还有水体、建筑、道路、林地等其他地物，请问，如果可以识别TIF的话，可以对影像中的这么多中地物进行分割吗？ 麻烦您了
> […](#)
> -----原始邮件----- 发件人:yatengLG ***@***.***> 发送时间:2024-06-04 11:13:24 (星期二) 收件人: yatengLG/ISAT_with_segment_anything ***@***.***> 抄送: jhrcws ***@***.***>, Author ***@***.***> 主题: Re: [yatengLG/ISAT_with_segment_anything] 可以支持tif影像吗 (Issue #170) 你可以邮件发我一张图片嘛，我可以试一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

没有收到附件，你直接发这个邮箱吧： yatenglg@foxmail.com

**Comment by Alias-z** [comment]
tif类是支持的 我标注过很多图了

**Comment by yatengLG** [comment]
你数据收到了，的确读不了。
你这个应该是特定格式的tif，PIL读不了，cv2也读不了，ubuntu自带图像软件也打不开。

建议你转换格式，然后再标注。
