### ISSUE TITLE
关于3D交互式半自动分割的咨询

### ISSUE THREAD

**Issue by lichen14** [yatengLG/ISAT_with_segment_anything#173]
作者好，ISAT做2D-SAM分割已经能基本上满足我对2d图像的分割标注了，感谢！
这个issue是想问：是否有类似的3D 标注工具呢？另外，现在的3D标注是什么个情况啊？也是需要逐slice标注了再整合在一起吗？那这样的话，似乎2D的ISAT就能做，能否支持load 3D的模型，接受3D的输入呢？例如三维的医学图像CT volume
感谢，实际使用中遇到的一个新问题，前来咨询 :smile:

**Comment by yatengLG** [comment]
您好，您这里所说的3D数据应该是2D图像的堆叠，而不是三维点云那样的完全立体结构。对于这种数据，我之前没有涉及过（没做过医学相关的研究）。

如果我理解没错的话，那当前的标注方法的确应该是切片标注以后再整合。即使支持直接输入原始数据也会切片，类似于标注视频时，输入视频，但标注还是以帧为单位。

**Comment by Alias-z** [comment]
我在考虑一下把3D的tiff输入的最后维度展开，change in position。但需要一个新的ISAT json类，不然切片层 
太多保存不方便。效果显示类似这样：

[1] 正常图.xxx
[2] 3D图.tif
    [1] slice 1
    [2] slice 2
    ...
[3] 正常图.xxx
