### ISSUE TITLE
增加一个yolo的txt标签转换

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#177]
25 0.475759 0.414523 0.951518 0.672422
0 0.671279 0.617945 0.645759 0.726859

你好，可以增加一个yolo的txt标签转换吗
yolov8n.pt 模型，coco128.yaml 使用的格式
一个标签对应一个txt的那种

**Comment by yatengLG** [comment]
你说的应该是yolo目标检测格式。这个可以从yolo图像分割格式转，网上可以找到转换代码。

**Comment by 379061296** [comment]
> 你说的应该是yolo目标检测格式。这个可以从yolo图像分割格式转，网上可以找到转换代码。
> 
> 你说的应该是yolo目标检测格式。这个可以从yolo图像分割格式转，网上可以找到转换代码。

https://github.com/Samsara0Null/xml_txt_mutual_conversion
是的，目标检测，目前找到了一个经过测试能用的，需要先vco目标检测转换出xml，再用xml_txt.py代码转yolo的目标检测
