### ISSUE TITLE
请问不同类别之间的缝隙怎么处理

### ISSUE THREAD

**Issue by Wst-sd** [yatengLG/ISAT_with_segment_anything#180]
用sam标注时，由于不同类别的物体识别时不能完全准确，标注完后，交界处会有一条缝隙，不想要这个缝隙的话，软件有地方设置吗？
示例图片中的这个杯子周围就没有缝隙
![000000002592](https://github.com/yatengLG/ISAT_with_segment_anything/assets/125892081/8137641d-193e-409c-a13c-446a29b9709e)
但是这张示例图片中的人和桌子就有缝隙
![000000117425](https://github.com/yatengLG/ISAT_with_segment_anything/assets/125892081/bb2b39c1-5134-45f7-b100-a22810d6c9a6)
我的数据里，几乎都有缝隙
![20240611182303](https://github.com/yatengLG/ISAT_with_segment_anything/assets/125892081/9f46f2ed-92ad-4d94-8c0f-a7d949e36fe9)

**Comment by yatengLG** [comment]
有缝隙是因为sam分割结果就不可能完全准确，即使手动画多边形，也会存在缝隙。

没有缝隙，是因为标注存在重叠区域。

**Comment by XieDeWu** [comment]
#167 
大选区,排除背景,异或
我的实现是扁平化,所以方便处理

**Comment by Wst-sd** [comment]
> #167 大选区，排除背景，异或 我的实现是扁平化，所以方便处理

请问怎么使用这个扁平化功能？

**Comment by XieDeWu** [comment]
> > #167 大选区，排除背景，异或 我的实现是扁平化，所以方便处理
> 
> 请问怎么使用这个扁平化功能？

想起来这边当时rebase后懒得改了,但是关键代码没变 
只是只有默认E 并,其余Shift+E 减,Alt+E 交,Alt+Shift+E 异或
这个你看着我这边fork仓的canvas画布代码看着加上去就好,毕竟我也是对qt5不熟,当时不知道有设计器就模仿自动生成代码结构弄上去的
