### ISSUE TITLE
我标注了所有qq头像，点击标注完成以后，只有一个

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#181]
第1张图片是标注了所有qq群头像，标注完成，第2个图是点击类别查看，发现只标注了一个
已解决：轮廓模式，选择所有轮廓
大佬要是方便的话，看一下下面的第3个请求

![QQ截图20240613004122](https://github.com/yatengLG/ISAT_with_segment_anything/assets/21965603/58c00866-b451-4389-9441-82c6b6af81c5)
![QQ截图20240613004152](https://github.com/yatengLG/ISAT_with_segment_anything/assets/21965603/4da84a4c-7731-48ee-9904-8115fcb27533)

**Comment by 379061296** [comment]
![Uploading QQ截图20240613004122.jpg…]()

**Comment by 379061296** [comment]
![Uploading QQ截图20240613004152.jpg…]()

**Comment by 379061296** [comment]
还有，是否可以增加个用户使用 Segment anything，就默认记住这个，快捷键E完成标注以后，不用再次按Q进行Segment anything标注，默认还是Segment anything，当用户选择绘制多边形，再默认记住多边形选项，标注多个样品频繁的选择Segment anything多了这个操作很繁琐，很累

**Comment by 379061296** [comment]
图片列表的颜色是否可以再加深一点，太谈了不好区分自己选了哪个，需要仔细看才看的出来

![Uploading QQ截图20240613013708.jpg…]()

**Comment by yatengLG** [comment]
隐藏标注过图片的功能应该不会添加了。

1. 这个功能很鸡肋，反而会给用户带来一些困扰
2. 右下角有索引号，标注到多少张应该很好确认，也提供了快速跳转到指定图片的功能。

**Comment by 379061296** [comment]
> 隐藏标注过图片的功能应该不会添加了。
> 
> 1. 这个功能很鸡肋，反而会给用户带来一些困扰
> 2. 右下角有索引号，标注到多少张应该很好确认，也提供了快速跳转到指定图片的功能。

不如看颜色来的直接呀，图片列表选中的颜色太淡了

**Comment by 379061296** [comment]
> 隐藏标注过图片的功能应该不会添加了。
> 
> 1. 这个功能很鸡肋，反而会给用户带来一些困扰
> 2. 右下角有索引号，标注到多少张应该很好确认，也提供了快速跳转到指定图片的功能。

隐藏标注不会不实用，增加一个勾选的，勾选了就对保存过的隐藏，可以添加到如下图的位置

![767da6b4-ed9d-46bb-a109-5646542210a7](https://github.com/yatengLG/ISAT_with_segment_anything/assets/21965603/b6b514d6-38cf-482e-97c9-6d9fc48b056a)

**Comment by yatengLG** [comment]
> > 隐藏标注过图片的功能应该不会添加了。
> > 
> > 1. 这个功能很鸡肋，反而会给用户带来一些困扰
> > 2. 右下角有索引号，标注到多少张应该很好确认，也提供了快速跳转到指定图片的功能。
> 
> 隐藏标注不会不实用，增加一个勾选的，勾选了就对保存过的全部隐藏，取消就全部显示出来，可以添加到如下图的位置
> 
> ![767da6b4-ed9d-46bb-a109-5646542210a7](https://private-user-images.githubusercontent.com/21965603/339628577-b6b514d6-38cf-482e-97c9-6d9fc48b056a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjIxMzIsIm5iZiI6MTcxODUyMTgzMiwicGF0aCI6Ii8yMTk2NTYwMy8zMzk2Mjg1NzctYjZiNTE0ZDYtMzhjZi00ODJlLTk3YzktNmQ5ZmM0OGIwNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA3MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNmUyNjEzZTA0YTFiMGNlZDhiOWRhM2NjZmMwMDE0NzA5ZmE2ODdmODE2NzA1MTE2MmE5YmRkN2E0ODZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MK-AQ_dICKqdy-kNcor0Jv3N42HhLCsAmwwfRKwQ708)

这个涉及到的不只是一个按钮问题，需要一系列的处理逻辑。
1. 如果添加了隐藏已标注的勾选框，好处是什么？
    好处是：打开软件直接就是未标注图片，不用再下拉寻找，或者跳转了。
2. 如果要添加，怎么添加该功能？
    1）只在勾选/取消勾选的时候，进行一波文件列表刷新。 如果是这样，为什么不直接瞅一眼当前n/m?而需要取消勾选+勾选两次操作。
    2）每次标注完都进行一波文件列表刷新。如果是这样，那就是标注完直接从文件列表中剔除。之所以做文件列表，就是为了能前后切换，现在前切换没了，后切换是逐个顺序，那这个文件列表就没有存在的意义了。
3. 如果添加了，需要多大的工作量。
    1）软件在后台多线程缓存特征，该缓存哪些图片的特征，这个与文件列表强相关。如果手动/自动去更新文件列表，缓存都需要清空重新计算...
    2）逻辑问题，同2。

这也是为什么我会说这个功能很鸡肋的原因。

**Comment by 379061296** [comment]
> > > 隐藏标注过图片的功能应该不会添加了。
> > > 
> > > 1. 这个功能很鸡肋，反而会给用户带来一些困扰
> > > 2. 右下角有索引号，标注到多少张应该很好确认，也提供了快速跳转到指定图片的功能。
> > 
> > 
> > 隐藏标注不会不实用，增加一个勾选的，勾选了就对保存过的全部隐藏，取消就全部显示出来，可以添加到如下图的位置
> > ![767da6b4-ed9d-46bb-a109-5646542210a7](https://private-user-images.githubusercontent.com/21965603/339628577-b6b514d6-38cf-482e-97c9-6d9fc48b056a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjIxMzIsIm5iZiI6MTcxODUyMTgzMiwicGF0aCI6Ii8yMTk2NTYwMy8zMzk2Mjg1NzctYjZiNTE0ZDYtMzhjZi00ODJlLTk3YzktNmQ5ZmM0OGIwNTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA3MTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNmUyNjEzZTA0YTFiMGNlZDhiOWRhM2NjZmMwMDE0NzA5ZmE2ODdmODE2NzA1MTE2MmE5YmRkN2E0ODZlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MK-AQ_dICKqdy-kNcor0Jv3N42HhLCsAmwwfRKwQ708)
> 
> 这个涉及到的不只是一个按钮问题，需要一系列的处理逻辑。
> 
> 1. 如果添加了隐藏已标注的勾选框，好处是什么？
>    好处是：打开软件直接就是未标注图片，不用再下拉寻找，或者跳转了。
> 2. 如果要添加，怎么添加该功能？
>    1）只在勾选/取消勾选的时候，进行一波文件列表刷新。 如果是这样，为什么不直接瞅一眼当前n/m?而需要取消勾选+勾选两次操作。
>    2）每次标注完都进行一波文件列表刷新。如果是这样，那就是标注完直接从文件列表中剔除。之所以做文件列表，就是为了能前后切换，现在前切换没了，后切换是逐个顺序，那这个文件列表就没有存在的意义了。
> 3. 如果添加了，需要多大的工作量。
>    1）软件在后台多线程缓存特征，该缓存哪些图片的特征，这个与文件列表强相关。如果手动/自动去更新文件列表，缓存都需要清空重新计算...
>    2）逻辑问题，同2。
> 
> 这也是为什么我会说这个功能很鸡肋的原因。

我用过一个标注软件是这样的，我勾选了隐藏，只要保存了数据，他就会从列表删除那个图片显示，然后自动显示下一张图片，
