### ISSUE TITLE
自动保存不起作用，保存所有轮廓的组id有问题

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#182]
自动保存不起作用，点击标注完成，应该是自动保存，但是我测试需要再点击一下保存，才有数据，

轮廓模式--保存所有轮廓（只保存外轮廓）测试都有下面的问题
标注2个人，2个同样的person标签，然后标注完成，就会2个组id都是1，会有问题，问题在下面

数据转换--VOC目标检测，转换出来的xml标签数据打开查看，里边只有一个标注数据，
我把组id 改成1 2，再次转换才会正常出来2个标注数据

isat转coco测试也是，只要同组id，转出来的数据只有一个标签数据，其他我没再继续测试了

只有1个数据的话，我这边xml转txt也只能转出一个yolo txt的坐标点

那么多格式转换都支持了，强烈要求再添加一个转yolo txt格式的
0 0.351852 0.586111 0.138272 0.416667
0 0.183333 0.600926 0.238272 0.462963

**Comment by yatengLG** [comment]
> 自动保存不起作用，点击标注完成，应该是自动保存，但是我测试需要再点击一下保存，才有数据，
> 
> 轮廓模式--保存所有轮廓（只保存外轮廓）测试都有下面的问题 标注2个人，2个同样的person标签，然后标注完成，就会2个组id都是1，会有问题，问题在下面
> 
> 数据转换--VOC目标检测，转换出来的xml标签数据打开查看，里边只有一个标注数据， 我把组id 改成1 2，再次转换才会正常出来2个标注数据
> 
> isat转coco测试也是，只要同组id，转出来的数据只有一个标签数据，其他我没再继续测试了
> 
> 只有1个数据的话，我这边xml转txt也只能转出一个yolo txt的坐标点
> 
> 那么多格式转换都支持了，强烈要求再添加一个转yolo txt格式的 0 0.351852 0.586111 0.138272 0.416667 0 0.183333 0.600926 0.238272 0.462963

1. 自动保存，切换图片时才会保存。
2. 不是轮廓模式有问题，是理解有误。一次标注都会是同一个组id，无论是哪种轮廓模式。
3. 格式支持问题。软件是一个针对图像分割的标注工具，所以提供了几乎所有的图像分割通用格式；针对目标检测用户，也提供了能附带更多信息的voc目标检测格式xml。  xml可以满足其他各种目标检测格式的转换需求，并且有很多公开的脚本。

**Comment by 379061296** [comment]
> > 自动保存不起作用，点击标注完成，应该是自动保存，但是我测试需要再点击一下保存，才有数据，
> > 轮廓模式--保存所有轮廓（只保存外轮廓）测试都有下面的问题 标注2个人，2个同样的person标签，然后标注完成，就会2个组id都是1，会有问题，问题在下面
> > 数据转换--VOC目标检测，转换出来的xml标签数据打开查看，里边只有一个标注数据， 我把组id 改成1 2，再次转换才会正常出来2个标注数据
> > isat转coco测试也是，只要同组id，转出来的数据只有一个标签数据，其他我没再继续测试了
> > 只有1个数据的话，我这边xml转txt也只能转出一个yolo txt的坐标点
> > 那么多格式转换都支持了，强烈要求再添加一个转yolo txt格式的 0 0.351852 0.586111 0.138272 0.416667 0 0.183333 0.600926 0.238272 0.462963
> 
> 1. 自动保存，切换图片时才会保存。
> 2. 不是轮廓模式有问题，是理解有误。一次标注都会是同一个组id，无论是哪种轮廓模式。
> 3. 格式支持问题。软件是一个针对图像分割的标注工具，所以提供了几乎所有的图像分割通用格式；针对目标检测用户，也提供了能附带更多信息的voc目标检测格式xml。  xml可以满足其他各种目标检测格式的转换需求，并且有很多公开的脚本。

大佬啊，看你上一次线好难，从6月11号到16号终于盼来了你的回复，有QQ交流群吗，方便提交bug或建议。

自动保存命名很容易让人产生错误的认知啊，要不改个名字，要不Segment anything标注好的数据，保存标注，也根据勾选的自动保存，保存一下数据，你看可以不，目前我还在用你提供的https://github.com/yatengLG/ISAT_with_segment_anything/issues/182 方法实现这种

self.scene.start_segment_anything() # Q Segment anything
如果需要使用绘制多边形，这个应该怎么修改呢，谢谢

**Comment by yatengLG** [comment]
> > > 自动保存不起作用，点击标注完成，应该是自动保存，但是我测试需要再点击一下保存，才有数据，
> > > 轮廓模式--保存所有轮廓（只保存外轮廓）测试都有下面的问题 标注2个人，2个同样的person标签，然后标注完成，就会2个组id都是1，会有问题，问题在下面
> > > 数据转换--VOC目标检测，转换出来的xml标签数据打开查看，里边只有一个标注数据， 我把组id 改成1 2，再次转换才会正常出来2个标注数据
> > > isat转coco测试也是，只要同组id，转出来的数据只有一个标签数据，其他我没再继续测试了
> > > 只有1个数据的话，我这边xml转txt也只能转出一个yolo txt的坐标点
> > > 那么多格式转换都支持了，强烈要求再添加一个转yolo txt格式的 0 0.351852 0.586111 0.138272 0.416667 0 0.183333 0.600926 0.238272 0.462963
> > 
> > 
> > 
> > 1. 自动保存，切换图片时才会保存。
> > 2. 不是轮廓模式有问题，是理解有误。一次标注都会是同一个组id，无论是哪种轮廓模式。
> > 3. 格式支持问题。软件是一个针对图像分割的标注工具，所以提供了几乎所有的图像分割通用格式；针对目标检测用户，也提供了能附带更多信息的voc目标检测格式xml。  xml可以满足其他各种目标检测格式的转换需求，并且有很多公开的脚本。
> 
> 大佬啊，看你上一次线好难，从6月11号到16号终于盼来了你的回复，有QQ交流群吗，方便提交bug或建议。
> 
> 自动保存命名很容易让人产生错误的认知啊，要不改个名字，要不Segment anything标注好的数据，保存标注，也根据勾选的自动保存，保存一下数据，你看可以不，目前我还在用你提供的#106 方法实现这种，而且把你这个开源代码地址发别人，也遇到一些人问我自动保存的问题
> 
> self.scene.start_segment_anything() # Q Segment anything 如果需要使用绘制多边形，这个应该怎么修改呢，谢谢

1.自动保存这个功能，这么看逻辑上的确有点误解，我后续更改下。
2.https://github.com/yatengLG/ISAT_with_segment_anything/issues/106 是相当于用户自定义组合键的问题。这个后续我也会考虑推出对组合键的支持。

**Comment by yatengLG** [comment]
1. 自动保存功能已经更新了。
    现在每次改动都会自动保存了。
