### ISSUE TITLE
每张照片标注前等待时间过长

### ISSUE THREAD

**Issue by HePengguang** [yatengLG/ISAT_with_segment_anything#184]
电脑配置如下，使用CPU进行辅助标注，每次切换图片至少等待15s才能开始标注。这是电脑配置太低的原因吗？
又没有可能实现，提前把数据集需要提取的特征先缓存了之类的，在标注的时候做到快速切换即可标注。
谢谢！
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/73171209/79575bbf-ee16-4ac2-87f2-a18cb5e1c84a)

**Comment by HePengguang** [comment]
有时候加载时间超过1分钟

**Comment by HePengguang** [comment]
用的300多M那个模型，现在每张图片都需要等待超过1min才能启用sam，请问这个怎么解决呀

**Comment by yatengLG** [comment]
> 用的300多M那个模型，现在每张图片都需要等待超过1min才能启用sam，请问这个怎么解决呀

cpu建议用 sam-hq-tiny或者mobile-sam

**Comment by HePengguang** [comment]
> > 用的300多M那个模型，现在每张图片都需要等待超过1min才能启用sam，请问这个怎么解决呀
> 
> cpu建议用 sam-hq-tiny或者mobile-sam

管用的，感谢大佬，非常感谢。  另外请问怎么删除背景类呢？

**Comment by yatengLG** [comment]
> > > 用的300多M那个模型，现在每张图片都需要等待超过1min才能启用sam，请问这个怎么解决呀
> > 
> > 
> > cpu建议用 sam-hq-tiny或者mobile-sam
> 
> 管用的，感谢大佬，非常感谢。 另外请问怎么删除背景类呢？

背景类删不了，1.软件有其他功能需要用到背景类；2.图像分割训练过程中即使不标注也会需要用到背景类。

如果你不需要背景类，训练的时候直接忽略就可以了。
