### ISSUE TITLE
不能加载自动分割

### ISSUE THREAD

**Issue by Tonyjoker1** [yatengLG/ISAT_with_segment_anything#185]
![屏幕截图 2024-06-20 113530](https://github.com/yatengLG/ISAT_with_segment_anything/assets/133932353/ca51b2dc-cbb8-406d-acef-683943f1e9a9)
作者大大，您好
预标注的图片和标注文件，类别和模型都设置好以后，自动加载的图标经常是灰色的，然后整个程序就卡住不能用，重新加载也是一样。
这要怎么解决呢

**Comment by yatengLG** [comment]
你是cpu吧。

卡住应该是在加载模型。cpu的话，建议用小点儿的模型，sam-hq-tiny或mobile-sam。

**Comment by Tonyjoker1** [comment]
是环境配置里的那个要变成GPU呢

**Comment by Tonyjoker1** [comment]
就是怎样用GPU去运行程序呢

**Comment by yatengLG** [comment]
> 就是怎样用GPU去运行程序呢

你安装gpu版本的pytorch就可以用gpu了。

**Comment by Tonyjoker1** [comment]
好的，感谢
