### ISSUE TITLE
关于推理设备的问题

### ISSUE THREAD

**Issue by xchouzhang** [yatengLG/ISAT_with_segment_anything#186]
您好，请问下现在的版本是只支持cpu版本的推理吗，在linux ubuntu平台上也是如此吗？

**Comment by yatengLG** [comment]
> 您好，请问下现在的版本是只支持cpu版本的推理吗，在linux ubuntu平台上也是如此吗？

你装torch的gpu版本，就支持gpu了啊。

**Comment by Alias-z** [comment]
> 谢谢！再请教一下在调整标签时 快进键R怎么用啊 就是除了一些红色的点 不知道怎么确定

![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/66273343/b68062f1-33f9-43a5-96b0-87a8e9049a17)

没有快进键噢，R是重绘模式的快捷键。具体使用方法看文档 https://isat-samzh.readthedocs.io/zh-cn/latest/features.html
