### ISSUE TITLE
原始图像被自动旋转了90度，是不是显示图片是宽高设置的问题

### ISSUE THREAD

**Issue by tensor-song** [yatengLG/ISAT_with_segment_anything#189]

**Comment by tensor-song** [comment]
添加一个图像旋转功能，或者读取原图的宽高设置为显示的宽高

**Comment by Alias-z** [comment]
没有这个问题呀，你要不尝试用其他图片浏览器打开看看图片原来是什么样子的？旋转功能倒是个不错的提议。

**Comment by yatengLG** [comment]
和软件没问题。
之前有个裂缝识别数据集遇到过这个问题，拍摄的图片旋转了（但实际情况并不是）。

你可以打印下你图片的宽高对比下。

**Comment by yatengLG** [comment]
> 没有这个问题呀，你要不尝试用其他图片浏览器打开看看图片原来是什么样子的？旋转功能倒是个不错的提议。

旋转功能好添加，主要是不想改动用户数据。
