### ISSUE TITLE
读取图片时是存在性能问题吗  没有labelme 切换图片快

### ISSUE THREAD

**Issue by OxygenLost** [yatengLG/ISAT_with_segment_anything#19]
切换图片越大等待时间越长

**Comment by yatengLG** [comment]
> 切换图片越大等待时间越长

切换的时候，SAM得计算图片特征啊。

把计算都在载入时计算了，自动分割的时候就可以做到低延迟。 如果把计算放在分割的时候，鼠标点一下再计算，那才叫灾难。

不用SAM做半自动标注，切换图片怎么可能比labelme慢T_T

**Comment by yatengLG** [comment]
最新版本中，使用独立线程计算sam，解决了使用大模型时切换图片的卡顿感
