### ISSUE TITLE
拥挤的勾选会起到什么作用

### ISSUE THREAD

**Issue by kecin2019** [yatengLG/ISAT_with_segment_anything#190]
感谢作者的付出，有一点问题，双击打开标签后有一个拥挤可以勾选，这个拥挤勾选后会对最后的标签有什么影响嘛
![image](https://github.com/user-attachments/assets/5167b05e-7042-4514-9d30-b9ecb4843913)

**Comment by yatengLG** [comment]
没什么影响。

coco任务区分是否是拥挤目标，所以添加了对这个的支持。

**Comment by kecin2019** [comment]
那划分到同一组的目标默认就是拥挤目标吧，还要一个个单独勾选是否太麻烦了

**Comment by yatengLG** [comment]
> 那划分到同一组的目标默认就是拥挤目标吧，还要一个个单独勾选是否太麻烦了

并不是的。coco里面的拥挤，你可以理解为一群人一个mask，而不是一个人一个mask。

**Comment by kecin2019** [comment]
啊 是我理解错了 谢谢！

**Comment by yatengLG** [comment]
> 啊 是我理解错了 谢谢！

一般使用，你是不需要管这个的。

即使是COCO数据集，一般用的时候也会把crowd的目标过滤掉。保留这个只是为了满足个别需求。

**Comment by kecin2019** [comment]
谢谢你的解答！
