### ISSUE TITLE
可以保存分割出的mask图片嘛

### ISSUE THREAD

**Issue by qq846511277** [yatengLG/ISAT_with_segment_anything#192]
可以保存分割出的mask图片嘛

**Comment by zzingok** [comment]
同求，希望保存的时候，能够把当前标注的mask也保存下来

**Comment by yatengLG** [comment]
> 同求，希望保存的时候，能够把当前标注的mask也保存下来

都标注完了，polygon自行转mask就可以了。

对于转mask，你们每个人的需求都不一样，没法出一个能满足你们所有人的功能[摊手]。
