### ISSUE TITLE
死机状态

### ISSUE THREAD

**Issue by zzingok** [yatengLG/ISAT_with_segment_anything#193]
![image](https://github.com/user-attachments/assets/875ed8b2-8916-4189-bda8-5b72f308da4e)

你好，我这里加载模型之后，然后又点了一遍模型，就死机了

**Comment by zzingok** [comment]
是在我选择图片文件夹之后，再点一次模型就死机了，如果没有选择图片文件夹，是可以重复点的

**Comment by yatengLG** [comment]
你没gpu吧？
用cpu建议用mobile-sam或者sam-hq-tiny

**Comment by zzingok** [comment]
是的，切换了就好了
