### ISSUE TITLE
你好请问有最新版的exe文件嘛

### ISSUE THREAD

**Issue by qq846511277** [yatengLG/ISAT_with_segment_anything#194]
你好请问有最新版的exe文件嘛

**Comment by yatengLG** [comment]
> 你好请问有最新版的exe文件嘛

没顾上打包呢。

**Comment by qq846511277** [comment]
> > 你好请问有最新版的exe文件嘛
> 
> 没顾上打包呢。

直接用pyinstaller 打包嘛？
有没有啥关键点

**Comment by yatengLG** [comment]
直接用pyinstaller打包就可以。

需要注意的是：
1. 打包用-W，别用-F
2. 项目的一些配置文件需要复制到打包后的位置
3. 打包完可能缺一些依赖包，需要手动自己复制一下

**Comment by yatengLG** [comment]
打包完gpu版本，差不多有4个G。建议直接pip安装

**Comment by qq846511277** [comment]
好嘞 我来试试，主要是sam安装有点烦

**Comment by yatengLG** [comment]
> 好嘞 我来试试，主要是sam安装有点烦

可以直接 `pip install isat-sam`

`isat-sam`运行即可

**Comment by qq846511277** [comment]
感谢 我来试试看 py版本有要求吗

**Comment by yatengLG** [comment]
> 感谢 我来试试看 py版本有要求吗

理论上没要求，你用3.8以上的吧。
