### ISSUE TITLE
请问分割边缘有些锯齿，有推荐的模型吗？顺便问问支持最新的SAM2嘛

### ISSUE THREAD

**Issue by StanleyYake** [yatengLG/ISAT_with_segment_anything#196]
首先感谢作者的这个标注工具箱，很方便，目前也是主力在使用。但是发现SAM1（GPU显存：6G，使用sam_hq_vit_b.pth）做分割标注，有的边缘有些锯齿，然后训练的模型识别后锯齿更加严重了。楼主有推荐的sam1模型吗，或者顺便问问支持最新的SAM2吗？
https://github.com/facebookresearch/segment-anything-2
https://mp.weixin.qq.com/s/JZVjRlmxMRAPFfpW3IMMIA

**Comment by yatengLG** [comment]
sam2的支持昨晚就写完了，今儿晚上提交。

另外，sam2的主要贡献在视频分割，对于单图效果并没有提升。
这边建议使用sam_hq_vit_h模型，如果显存不够，可以开启bfloat16模式（在模型管理界面）。

另外所说的边缘锯齿问题，这个只是显示问题，你可以自己转换为labelme后用labelme打开瞅瞅。。。

**Comment by yatengLG** [comment]
> 谢谢楼主，勾选bfloat16模式，可以下载更高精度的模型，但是打开以前用float32标注的文件夹就报错了，是不兼容是吧，是不是只能重新标注了？ ![Screenshot from 2024-08-07 14-31-59](https://private-user-images.githubusercontent.com/7522853/355702212-a598a22e-c752-4906-a143-abb8b727dae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQzNDAsIm5iZiI6MTcyMzAxNDA0MCwicGF0aCI6Ii83NTIyODUzLzM1NTcwMjIxMi1hNTk4YTIyZS1jNzUyLTQ5MDYtYTE0My1hYmI4YjcyN2RhZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMDcwMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU0OTQ1YThlZjk1NWFmMTQ3YjE1MGQ3MWM3NmIzNTBmNDY5MGIyZjdkMmJjY2RhMWE5NzNiNzUxMDhkM2RjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gKUpQf5lp_KR20SSsGTUdkEiLHgSsyG-4jGWCb_HEYQ)

不是勾选bfloat16可以下载高精度模型，是bfloat16模式跑模型时占用显存会比较低一些（如果你显存不够跑特别大的模型，可以通过这种方式跑大模型）。

另外这个报错不是不兼容，可能是你显卡不支持bfloat16（或者cuda版本较低/torch版本较低）。

**Comment by yatengLG** [comment]
刚添加了对sam2的支持。你可以尝试使用下sam2的模型
