### ISSUE TITLE
希望用这个工具处理素材

### ISSUE THREAD

**Issue by wasni001** [yatengLG/ISAT_with_segment_anything#2]
不知道有没有可能加一些功能，比如勾选或者未勾选的图层不显示（擦除掉）然后导出标注的图片/ 原图 ， 
（因为有时候需要人物图片，要先把不用的元素啥的P掉，不知道有没有表达清楚）

**Comment by yatengLG** [comment]
我大概能理解您的需求，这个需求实际上非常简单，下述是解决方法：
比如您只想保存‘人物’与‘杯子’这两类，您可以解析json文件，获取关于人物与杯子两类别的object，另存为一个新的json就可以。
通过软件自带的转换工具，转换这个新的json文件就可以了。
