### ISSUE TITLE
置底程序崩溃

### ISSUE THREAD

**Issue by GeYifan123** [yatengLG/ISAT_with_segment_anything#20]
为什么点置底的时候程序总崩溃呢

**Comment by yatengLG** [comment]
能详细说明下具体情况嘛，以便于我进行调试。

**Comment by GeYifan123** [comment]
像这种标注的比较多的情况下，把最后一类置底可能会窗口无响应




葛怡帆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yatengLG/ISAT_with_segment_anything"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yatengLG/ISAT_with_segment_anything] 置底程序崩溃 (Issue #20)





 
能详细说明下具体情况嘛，以便于我进行调试。

**Comment by yatengLG** [comment]
能把标注的json发我一份，我调试用嘛。  就出问题这份

**Comment by GeYifan123** [comment]
他有时候可以用，有时候直接无响应，是不是我硬件问题










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yatengLG/ISAT_with_segment_anything"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yatengLG/ISAT_with_segment_anything] 置底程序崩溃 (Issue #20)





 
能把标注的json发我一份，我调试用嘛。  就出问题这份

**Comment by yatengLG** [comment]
你所说的标注比较多的情况，最多的时候有多少个啊
