### ISSUE TITLE
工具/数据转换/ISAT转COCO

### ISSUE THREAD

**Issue by Link-kai** [yatengLG/ISAT_with_segment_anything#200]
我用ISAT标注一批数据，然后想转换成COCO数据集格式
为什么不是转换为多个json文件，而是全部变成一个文件，能否与labelme统一呢

**Comment by yatengLG** [comment]
有没有可能coco数据集就是单个的json文件呢(ㄒ.ㄒ)

如果你代码的数据格式有问题，软件也提供了转换labelme的功能，你可以尝试先转labelme，然后再转换你所说的多个json。
