### ISSUE TITLE
请教 self.set_labels_visible 显示/隐藏函数是这个吗

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#206]
def extra_func(self):
        self.scene.finish_draw() # E 标注完成
        self.save() # S 保存标注文件
        # self.next_image() # D 下一张图片
        self.scene.start_segment_anything() # Q Segment anything
        self.set_labels_visible

self.set_labels_visible 大大，显示/隐藏是这个函数吗，我添加了没有效果，方便的话提供一下所有快捷键函数，谢谢

**Comment by 379061296** [comment]
> 这是个函数，需要传参数的

那应该怎么写

**Comment by yatengLG** [comment]
所有的快捷键，你可以看
https://github.com/yatengLG/ISAT_with_segment_anything/blob/2b09db01b02136c9dd4a0c31123491d08dcbf97d/ISAT/widgets/mainwindow.py#L1373

这里面包含了大部分的 函数，如果需要对应快捷键，请对照

https://github.com/yatengLG/ISAT_with_segment_anything/blob/2b09db01b02136c9dd4a0c31123491d08dcbf97d/ISAT/ui/MainWindow.py#L457

**Comment by yatengLG** [comment]
> > 这是个函数，需要传参数的
> 
> 那应该怎么写

https://github.com/yatengLG/ISAT_with_segment_anything/blob/2b09db01b02136c9dd4a0c31123491d08dcbf97d/ISAT/widgets/mainwindow.py#L1224


```python
def extra_func(self):
    self.scene.finish_draw() # E 标注完成
    self.save() # S 保存标注文件
    # self.next_image() # D 下一张图片
    self.scene.start_segment_anything() # Q Segment anything
    self.set_labels_visible(True) # 显示
    self.set_labels_visible(False) # 不显示
```

**Comment by yatengLG** [comment]
所有快捷键的话，[菜单栏]-[帮助]-[快捷键]。里面有

**Comment by 379061296** [comment]
> n

感谢，已经解决，对了，视频分割命名容易误导人，我以为是支持添加视频，测试又不支持，后面查看display的gif动图，才搞清楚是图片，命名图片分割或许好一点

**Comment by yatengLG** [comment]
> > n
> 
> 感谢，已经解决，对了，视频分割命名容易误导人，我以为是支持添加视频，测试又不支持，后面查看display的gif动图，才搞清楚是图片，命名图片分割或许好一点

实际上，所有的视频相关的，不管是视频分割，还是视频目标检测，视频标注。都是基于图像做的，sam2也同理（只要你看过他代码）。

至于添加视频，后台也是分成n个图片，然后做，只是看起来不同罢了，多此一举T.T。
