### ISSUE TITLE
可以增加一个选中标注好的目标，ISAT界面右下角显示大小吗

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#207]
可以增加一个选中标注好的目标，ISAT界面右下角显示目标大小，如下图，选中目标，ISAT界面右下角显示200x200
可以在主页留个支付宝，微信收款二维码吗，想赞助支持一下找不到付款方式

![QQ20240920-200653](https://github.com/user-attachments/assets/7bf55a9e-e2ea-4aea-a21e-95e2e4d898d2)

**Comment by 379061296** [comment]
如下图，在标注列表每个类后面显示出它的大小，如 200x200

![QQ20240920-234805](https://github.com/user-attachments/assets/2b2f13d1-3d0d-4125-8137-4ec336a8dc31)

**Comment by yatengLG** [comment]
你是需要区别大小目标嘛？
如果是这个需求，建议还是标注完，整体遍历一遍更好。
另外，在保存的标注json文件中，每个多边形，都存储了面积与边框，可以通过这个字段区分大小目标。
![截图 2024-09-23 10-41-18](https://github.com/user-attachments/assets/112f73be-bdc6-42a7-afbc-14ba1001417f)

**Comment by 379061296** [comment]
> 都存储了面积与边框，可以通过这个字段区分大小目标

是的，区别目标大小，直接显示到list上更加直观，这个功能也不是必须要的，有的话更加好
