### ISSUE TITLE
希望增加选择标注过的，list列表自动滚动，定位到对应的标签名

### ISSUE THREAD

**Issue by 379061296** [yatengLG/ISAT_with_segment_anything#208]
在安卓里面就有这个函数，不知道py能不能实现这种效果
// 定位到指定项如果该项可以置顶就将其置顶显示
    ui.list.getLayoutManager().scrollToPositionWithOffset(5 - 1, 0);

![QQ20240922-093635](https://github.com/user-attachments/assets/2364f135-fa91-4eaa-a056-d0d041716957)

**Comment by yatengLG** [comment]
是点击画布上多边形，然后右侧标签列表 自动滚动嘛？

**Comment by 379061296** [comment]
> 是点击画布上多边形，然后右侧标签列表 自动滚动嘛？
> 
> 该功能已更新，github拉取最新代码即可（pip包未更新）。

经过测试，可以跳转，已解决
