### ISSUE TITLE
数据转换yolo bug

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#211]
文件--图片文件夹  导入C:\yolo\ISAT_with_segment_anything-1.2.2\example\videos
只保留5个图片+json标注文件，手动删除其他图片+json剩余文件

工具--数据转换--LOYO--ISAT转LOYO
转换出来的txt数据依然是200个

重新打开ISAT，工具--数据转换--LOYO--ISAT转LOYO  这样转换的才没问题
数据转换里面遍历图片跟json的函数应该独立出来，不要和图片文件夹导入的函数共享

![QQ20240929-173001](https://github.com/user-attachments/assets/bfec5246-2bb1-4e0c-b225-fcaee59b7ea8)
![QQ20240929-173010](https://github.com/user-attachments/assets/9fd00ffd-5a3d-4833-8985-bf750ca6fa76)

**Comment by yatengLG** [comment]
问题已经修复了

原因是加载ISAT标注前，没有清空之前加载的数据。

https://github.com/yatengLG/ISAT_with_segment_anything/commit/c9bc27e9bbeaf07dcf4a4d555119689facae8933

**Comment by 258692011** [comment]
> 问题已经修复了
> 
> 原因是加载ISAT标注前，没有清空之前加载的数据。
> 
> [c9bc27e](https://github.com/yatengLG/ISAT_with_segment_anything/commit/c9bc27e9bbeaf07dcf4a4d555119689facae8933)

那个弹窗的去掉可以吗

左下角的这个Track 模式是干嘛的，我翻译了也没看懂
Group id changed with the group of current polygons when use [TAB] or ['] to checke

**Comment by yatengLG** [comment]
弹窗是不准备去了，有弹窗大家都不明白，别说没弹窗提示了。   不然过几天就会有人来说，你这软件不行啊，我在网站上跑的比你这个快多了T.T


左下角那个是 组 的模式，有【自动】、【手动】、【跟踪】？  三个模式，就是组id改变的方式。

自动模式下，每添加一个目标，组id自动+1，手动不会变。跟踪track，是你使用 tab或· 切换目标时（目标会放大，便于修改），这个组id会随着目标组id变，方便你修改过程中添加新目标。
