### ISSUE TITLE
建议删除这个坑爹的模型

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#213]
sam-med2d_b.pth 模型，占用2.4G，我以为多牛逼的模型，下载回来点几次以后自己懵逼了，就这个结果，连mobile_sam.pt 模型都比不上，心疼我的手机2G流量

你自己看把，我啥也不想说了

![QQ20240930-013148](https://github.com/user-attachments/assets/74a1ecfb-4c69-43b6-a136-c90793e93a8a)

**Comment by yatengLG** [comment]
可能你需要先去了解下各个模型的优缺点。T.T

sam_med2d是针对医疗图像的。。。

**Comment by GewelsJI** [comment]
这个issue最搞笑了
