### ISSUE TITLE
发现一个啥几把弄的话，会触发崩溃的问题

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#214]
加载模型，导图图片以后，把左下角的 auto 改成 track ,然后按一下Tab键盘，id框会出来一个All，再用 Segment anything 英文真长--标注一个目标，点击标注完成，咦，崩溃了

**Comment by yatengLG** [comment]
不知道你为什么崩溃，没有复现出来。

但是可以肯定的是，程序崩溃不是因为track引起的：因为标注使用的组id用的一直是左下角输入框的值，右侧标注列表的那个 all、1、2、3、...只是显示用的。

**Comment by 258692011** [comment]
加载一个模型，导图图片文件夹以后，把左下角的 auto 改成 track ,然后按一下Tab键盘，id框会出来一个All，我发了一个图你看看

![Uploading QQ20240930-125051.jpg…]()

**Comment by 258692011** [comment]
> 不知道你为什么崩溃，没有复现出来。
> 
> 但是可以肯定的是，程序崩溃不是因为track引起的：因为标注使用的组id用的一直是左下角输入框的值，右侧标注列表的那个 all、1、2、3、...只是显示用的。

加载一个模型，导图图片文件夹以后，把左下角的 auto 改成 track ,然后按一下Tab键盘，id框会出来一个All，我发了一个图你看看

![QQ20240930-125051](https://github.com/user-attachments/assets/07e864b1-62e1-4f9e-928c-a021e9ce0937)

**Comment by 258692011** [comment]
这个时候再点击一下 - 减号按钮，也会触发崩溃

![QQ20240930-125444](https://github.com/user-attachments/assets/e2f19fef-66d2-45bb-9c39-dce5de224d8b)

**Comment by yatengLG** [comment]
问题已经修复了

https://github.com/yatengLG/ISAT_with_segment_anything/commit/bda72ba106f10772304b2e2c4aedff549e387289
