### ISSUE TITLE
置顶无效，置底也无效。列表不会刷新

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#215]
![QQ20240930-145339](https://github.com/user-attachments/assets/23324929-574a-4cd7-8d38-5c0cc8deef72)

**Comment by yatengLG** [comment]
置顶和置底调整的是图层高低（影响多边形相互遮挡）。

和这个列表没关系。

**Comment by 258692011** [comment]
> 置顶和置底调整的是图层高低（影响多边形相互遮挡）。
> 
> 和这个列表没关系。

命名没区分太容易误解了
