### ISSUE TITLE
可否增加搜索类别名字

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#216]
如图，如果像这些标注，7000多个汉字，类别要一个个找起来很困难，可以增加一个搜索框，输入类别名字，搜索到以后定位滚动到类名显示吗

![F595EC09FA5E2758797E3C3E13E8A406](https://github.com/user-attachments/assets/f0c7d867-bf5a-4e9d-b8da-2135f19119b8)

**Comment by yatengLG** [comment]
类别查找功能已添加。

不过使用的是模糊匹配算法，即使输入有误差也可以匹配到最近似的类别。

https://github.com/yatengLG/ISAT_with_segment_anything/commit/bc4362a3736b4f3ae366135824dc33978963fc6e

**Comment by 258692011** [comment]
> 类别查找功能已添加。
> 
> 不过使用的是模糊匹配算法，即使输入有误差也可以匹配到最近似的类别。
> 
> [bc4362a](https://github.com/yatengLG/ISAT_with_segment_anything/commit/bc4362a3736b4f3ae366135824dc33978963fc6e)

功能牛逼了，中文，英文测试没问题
