### ISSUE TITLE
数据转换，可以增加记住标签位置选择吗

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#217]
每次打开ISAT_with_segment_anything，都是VOC，有时忘记要选YOLO，就直接选json去转换了，等关闭软件以后，才发现转换错了，又重新打开转换一次

![QQ20241010-200129](https://github.com/user-attachments/assets/ad948f29-abf0-4c8a-8de7-2ad4ea30c182)

**Comment by yatengLG** [comment]
功能已添加

https://github.com/yatengLG/ISAT_with_segment_anything/commit/04ca02dabef076aac45f29cd3b25c48035d301fa
