### ISSUE TITLE
类别查找默认获取到光标的问题

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#219]
每次第一次启动ISAT，选择模型，导入图片，类别输入框还是默认获取到光标状态，导致按Q快捷键变成输入Q查找，还得点击一下图片或者类名，光标才会消失，不然没法按快捷键，修复一下类别输入框不要默认获取到光标焦点

**Comment by yatengLG** [comment]
更新了。

https://github.com/yatengLG/ISAT_with_segment_anything/commit/fc7b80f139e7a4e95326ae058e87e6c120d565ae

**Comment by 258692011** [comment]
> 更新了。
> 
> [fc7b80f](https://github.com/yatengLG/ISAT_with_segment_anything/commit/fc7b80f139e7a4e95326ae058e87e6c120d565ae)

def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setFocus()   我刚刚在一个个测试，最后找到这个位置，在这里添加这个，我发现也可以解决

**Comment by yatengLG** [comment]
> > 更新了。
> > [fc7b80f](https://github.com/yatengLG/ISAT_with_segment_anything/commit/fc7b80f139e7a4e95326ae058e87e6c120d565ae)
> 
> def retranslateUi(self, Form): _translate = QtCore.QCoreApplication.translate Form.setWindowTitle(_translate("Form", "Form")) Form.setFocus() 我刚刚在一个个测试，最后找到这个位置，在这里添加这个，我发现也可以解决

是的。都是一些小问题，很好修复。

但发现问题，还得依靠广大用户。 O(∩_∩)O
