### ISSUE TITLE
添加多边形时角点大小不随分辨率改变

### ISSUE THREAD

**Issue by qjr1997** [yatengLG/ISAT_with_segment_anything#22]
我传入一张分辨率为7000*4000的图像后，我想通过拖拽mask上的这些点来改变其形状，但是点看上去特别小，必须要放大才能找到这些点并拖拽，有没有办法在显示这些点的时候根据图像分辨率动态调节其大小呢

**Comment by yatengLG** [comment]
如果以固定值指定顶点大小，你可以直接修改这两行
https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/polygon.py#LL15C1-L16C1

实现动态调节功能，改动会比较大，可能后续会进行更新。

**Comment by qjr1997** [comment]
好的 我试试 谢谢🙏
