### ISSUE TITLE
能否添加快捷键切换类别，而非鼠标点击切换功能

### ISSUE THREAD

**Issue by StanleyYake** [yatengLG/ISAT_with_segment_anything#220]
感谢楼主的工具，标注很方便。看看能否添加快捷键快速切换类别(如数字1,2,3；或字母键在类别列表里切换)，而非鼠标点击呢，那样就可以更加快捷的标注了^_^

**Comment by yatengLG** [comment]
类别选择快捷键与具体类别无关，只与类别列表顺序有关。

使用 [查找类别] 功能后，快捷键依然有效。
