### ISSUE TITLE
Checkpoints更新

### ISSUE THREAD

**Issue by deyang2000** [yatengLG/ISAT_with_segment_anything#222]
感谢你们的杰出工作。
我注意到SAM2团队公布了2.1版本的checkpoints：
![image](https://github.com/user-attachments/assets/4663a5ca-b8aa-4e7b-904b-8ce46ce22dcb)
你们有考虑过将新的checkpoints加入本项目吗？

**Comment by yatengLG** [comment]
稍后更新

**Comment by deyang2000** [comment]
两个版本的模型略有不同

**Comment by yatengLG** [comment]
对sam2.1的支持已经添加
