### ISSUE TITLE
在调整已标注数据的时候，切换图片后莫名闪退

### ISSUE THREAD

**Issue by StanleyYake** [yatengLG/ISAT_with_segment_anything#224]
在调整已标注数据的时候，切换后莫名闪退。是因为自己切换太快了吗？如何能够调出调试信息呢
![Screenshot from 2024-10-28 18-17-25](https://github.com/user-attachments/assets/9efb79fa-cd1c-4e38-81eb-da163c9b2e30)

**Comment by yatengLG** [comment]
更新了，现在即使出问题应该不会闪退了。  

https://github.com/yatengLG/ISAT_with_segment_anything/commit/8ab59136e7379e3d3c4f1b1839b1e85e15750a21

报错是，读取显存的进程出错了。
但出错原因未知，如果可以的话，希望帮忙复现下。

**Comment by 258692011** [comment]
用了大模型吧，你的显出不够大，我的8G显卡，最大也只能用sam2_hiera_base_plus.pt模型，sam2_hiera_large.pt模型跑不起来，切换图片也会有几率闪退
