### ISSUE TITLE
[功能添加] 楼主，组别切换的时候能够加上拉和下拉按钮吗

### ISSUE THREAD

**Issue by StanleyYake** [yatengLG/ISAT_with_segment_anything#225]
[功能添加] 楼主，非常感谢您的标注软件。组别切换的时候能够加上拉和下拉按钮吗，鼠标双击进来，又要去按键盘，用户感受不是太连贯。加入上拉和下拉按钮，就可以只用鼠标单独操作了
![20241028 182708](https://github.com/user-attachments/assets/f582c625-8014-48fb-b103-7d3dfb52e402)

**Comment by yatengLG** [comment]
软件提供了多边形图层置顶和置底的功能。

**Comment by yatengLG** [comment]
功能已添加

https://github.com/yatengLG/ISAT_with_segment_anything/commit/6ad065f114ed55fe2b90de901a84b1d6c72cca2c#diff-656c6a570db269039aacacff5aa64fe47fb0374071e97308e0af100b0dd22683R50

**Comment by 258692011** [comment]
> 功能已添加
> 
> [6ad065f#diff-656c6a570db269039aacacff5aa64fe47fb0374071e97308e0af100b0dd22683R50](https://github.com/yatengLG/ISAT_with_segment_anything/commit/6ad065f114ed55fe2b90de901a84b1d6c72cca2c#diff-656c6a570db269039aacacff5aa64fe47fb0374071e97308e0af100b0dd22683R50)

按钮太小了，弄成这样比较好，

![QQ20241101-165404](https://github.com/user-attachments/assets/fd9a31eb-a552-4db3-9c26-1281589b4d70)

**Comment by yatengLG** [comment]
> > 功能已添加
> > [6ad065f#diff-656c6a570db269039aacacff5aa64fe47fb0374071e97308e0af100b0dd22683R50](https://github.com/yatengLG/ISAT_with_segment_anything/commit/6ad065f114ed55fe2b90de901a84b1d6c72cca2c#diff-656c6a570db269039aacacff5aa64fe47fb0374071e97308e0af100b0dd22683R50)
> 
> 按钮太小了，弄成这样比较好，

那个好用，你信我。
不只能点击，还能用滚轮调整。

**Comment by 258692011** [comment]
滚轮调整不如直接输入数字快

**Comment by 258692011** [comment]
滚轮调整不如直接输入数字快，嘎嘎

**Comment by yatengLG** [comment]
> 滚轮调整不如直接输入数字快

可以直接输入的啊，这个功能一直保留的。
添加这两点击按钮，只是方便用鼠标快速调整组id。
