### ISSUE TITLE
sam2_hiera_tiny.pt 模型快下载完时，ISAT整个闪退

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#227]
sam2_hiera_tiny.pt 模型下载到99.99% ，ISAT整个闪退

**Comment by yatengLG** [comment]
没遇到过这个问题，能复现出来嘛？

**Comment by 258692011** [comment]
> 没遇到过这个问题，能复现出来嘛？

cuda cudnn 这2个驱动软件我卸载了就会，因为我看群里有人发了个图，我翻译出来是这样
![C9E45334ACE4656FDCC25CA9150856D9](https://github.com/user-attachments/assets/22a3b092-2dbf-43a6-b0de-17953831d042)

经过实测训练yolo，环境如下
python-3.10.11
下载地址：https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe
pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu118
pip install ultralytics==8.2.103

pytorch确实包含了cuda cudnn，不再需要安装那2个驱动包，也是可以训练

ISAT环境如下
python-3.10.11
下载地址：https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe
pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt

结果下载模型时，快要下载完的时候遇到了闪退，但是手动把模型下载放进去，标注，导出也没问题

今天又重新弄了一下ISAT环境，换成最新的又没遇到闪退的情况
pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by yatengLG** [comment]
只是下载的话，和环境应该没关系。

**Comment by 258692011** [comment]
> 只是下载的话，和环境应该没关系。

我也是这样认为，但是实在找不出什么问题导致的

**Comment by 258692011** [comment]
这样，我重新装回这个环境，再下载看看会闪退吗，以为我从你开源的代码里拉取的最新的包，不知道你改了requirements.txt没，可能导致的pip版本不兼容的问题，我去测试一下，等会回来给你答复

pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt

**Comment by 258692011** [comment]
> 这样，我重新装回这个环境，再下载看看会闪退吗，因为我昨天从你开源的代码里拉取的最新的包，不知道你改了requirements.txt没，可能导致的pip版本不兼容的问题，我去测试一下，等会回来给你答复
> 
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118 pip install -r requirements.txt

问题没复现出来，正常的下载完成

**Comment by yatengLG** [comment]
> > 这样，我重新装回这个环境，再下载看看会闪退吗，因为我昨天从你开源的代码里拉取的最新的包，不知道你改了requirements.txt没，可能导致的pip版本不兼容的问题，我去测试一下，等会回来给你答复
> > pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118 pip install -r requirements.txt
> 
> 问题没复现出来，正常的下载完成

可能是偶然现象，后续我在下载的部位加一个异常捕获就好了，出问题报错别闪退。

**Comment by 258692011** [comment]
> > > 这样，我重新装回这个环境，再下载看看会闪退吗，因为我昨天从你开源的代码里拉取的最新的包，不知道你改了requirements.txt没，可能导致的pip版本不兼容的问题，我去测试一下，等会回来给你答复
> > > pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118 pip install -r requirements.txt
> > 
> > 
> > 问题没复现出来，正常的下载完成
> 
> 可能是偶然现象，后续我在下载的部位加一个异常捕获就好了，出问题报错别闪退。

好的，我等下还要给你提交个类别快捷键一个很矛盾的问题，你再看看需要修改吗
