### ISSUE TITLE
类别快捷键一个很矛盾的问题

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#228]
根据官方的yolo数组类别是从0开头，那么background类别实际数组=0

1、如果我使用数字作为标签，那么按快捷键1，实际是__background__
     快捷键1=__background__
     快捷键2=1
     快捷键3=2
这样就产生了一个不对等，很矛盾的问题，background不应该是快捷键0么

![1](https://github.com/user-attachments/assets/c0749440-028a-450c-a46b-6419ad75f267)

2、为了避免这种矛盾问题，如下图，我给快捷键类别重新命名了一下，但是background不能修改，删除，重命名看着很变扭

![2](https://github.com/user-attachments/assets/d086e0b7-06c9-42ac-bad1-876985755ca2)

为了解决这个问题，我特意把coco128.yaml 数组0不使用，但是这个names列表数组又对不上问题2的快捷键，看着相当变扭
# Classes
names:
  0: __background__
  1: 苹果
  2: 雪梨
  3: 香蕉
  4: 橘子
  5: 葡萄
  6: 黄瓜
  7: 西红柿
  8: 萝卜
  9: 青菜
  10: fire hydrant
  11: stop sign

这里最大的问题还是 __background__ 不能修改，删除，重命名，昨天也有人跟我提到background这个问题，相信也有不少人跟我一样跟你说过这个问题吧

**Comment by yatengLG** [comment]
标注数据不能按特定模型或者特定数据集去处理。

1. 首先，background类，在isat中是一个必须概念，因为涉及到标注镂空目标等需求。
2. 无论在检测还是分割中，实际上都存在负样本的概念，只是不同模型的处理方式不一样。ISAT中的__background__实际就是手动添加了一个负样本。
3. 如果按特定模型或者特定数据集去要求，那就没法统一了。没必要纠结于那个模型或者数据格式。
4. ISAT只是一个标注工具，标注完的文件是可以编辑的。
5. 最主要的是，在模型训练中，一般都需要处理标签的。如果用户标注完就要扔模型里面直接训练，还要满足所有模型和格式，千人千面，那ISAT肯定没法满足的。

另外纠结类别快捷键第一个是0，还是1。 应该更没必要T.T。

----
难道真的有人，标注数据的时候，标签顺序是  1: 苹果2: 雪梨3: 香蕉；训练出来的模型就要定死是这个类别顺序？ISAT存储的json都是直接存储的类别名，也没定顺序吧T.T

**Comment by yatengLG** [comment]
> names:
0: background
1: 苹果
2: 雪梨
3: 香蕉
4: 橘子
5: 葡萄
6: 黄瓜
7: 西红柿
8: 萝卜
9: 青菜
10: fire hydrant
11: stop sign

> 这里最大的问题还是 background 不能修改，删除，重命名，昨天也有人跟我提到background这个问题，相信也有不少人跟我一样跟你说过这个问题吧

1，2，3 快捷键从来对应的不是某个类别。是类别列表的第几个。

按你这个思路，如果筛选了类别，又当如何处理
