### ISSUE TITLE
虚线框问题

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#229]
使用多边形标注，上面的滑块滑到最小，会有个虚线框，这个挺好的，
1、但是这个虚线框，标注第1个图片会出来，第2个图片又可能不出来，第3个图片又出来
2、重新打开标注工具，标注，这个虚线框又不出来，要重新拖动一下滑块，再标注才会出来

**Comment by 258692011** [comment]
![QQ20241101-164334](https://github.com/user-attachments/assets/cd78832b-ef81-42ae-992f-88cc58ada1b3)

**Comment by yatengLG** [comment]
更新了，可能和你想象的不太一样。

出现那个虚线框本身就是个bug。这是由于顶点大小为0以后，标注过程选中多边形导致的。
这个bug间接导致了顶点为0时拖动绘制出错。

现在已经全部修复了，在绘制过程中，多边形不允许被选中以及拖动。

**Comment by 258692011** [comment]
> 更新了，可能和你想象的不太一样。
> 
> 出现那个虚线框本身就是个bug。这是由于顶点大小为0以后，标注过程选中多边形导致的。 这个bug间接导致了顶点为0时拖动绘制出错。
> 
> 现在已经全部修复了，在绘制过程中，多边形不允许被选中以及拖动。

mask alpha 这个滑块条是干嘛的，翻译也没翻译出来，滑动到最大也没什么变化

**Comment by 258692011** [comment]
知道干嘛的了，但是这个zh_CH.ts 不是中文显示吗，为啥界面还是英文显示呢
![QQ20241107-131829](https://github.com/user-attachments/assets/2972b568-fee9-44f4-b8c9-93670376005e)

**Comment by yatengLG** [comment]
- mask alpha    sam生成mask的透明度
- approx polyyon 近似多边形，开启以后有效减少顶点数量
- show prompt sam提示点显示

**Comment by 258692011** [comment]
是问题1，你的翻译不完全，我自己改了一下

![QQ20241109-020354](https://github.com/user-attachments/assets/c3187a85-bb6d-4bd8-99e5-f008dcfd95ec)
![QQ20241109-020427](https://github.com/user-attachments/assets/636c7241-e58d-46f7-aaa2-6e08df11aa36)

**Comment by 258692011** [comment]
> * mask alpha    sam生成mask的透明度
> * approx polyyon 近似多边形，开启以后有效减少顶点数量
> * show prompt sam提示点显示
> 
> 语言问题：
> 
> 1. 如果说的是中文界面存在部分英文，是因为工具栏的那几个拖动条是手动添加的，不会自动翻译。有时候就忘了处理......
> 2. 如果说的是界面整体是英文的，可能是因为你没切换语言吧。 【菜单栏】-【help】-【language】

是问题1

**Comment by 258692011** [comment]
> * mask alpha    sam生成mask的透明度
> * approx polyyon 近似多边形，开启以后有效减少顶点数量
> * show prompt sam提示点显示
> 
> 语言问题：
> 
> 1. 如果说的是中文界面存在部分英文，是因为工具栏的那几个拖动条是手动添加的，不会自动翻译。有时候就忘了处理......
> 2. 如果说的是界面整体是英文的，可能是因为你没切换语言吧。 【菜单栏】-【help】-【language】

1、Mask alpha 拖动经过测试无效，
2、Image saturation 拖动改变饱和度，Mask alpha拖动 或 Vertex size 或 点击图片列表，饱和度又变会原来的颜色

**Comment by yatengLG** [comment]
> 1、Mask alpha 拖动经过测试无效，经过测试，sam标注选中目标时拖动才生效，标注完拖动不生效 
> 2、Image saturation 拖动改变饱和度，Mask alpha拖动--或者--Vertex size拖动--或者--点击图片列表，饱和度又变会原来的颜色

1. mask alpha: **sam生成mask的透明度**，不是polygon的透明度。
    
| | |
|:----|:----|
|![1](https://github.com/user-attachments/assets/bfdd7b9f-c3ce-4495-bbf4-19c96df2a336) | ![3](https://github.com/user-attachments/assets/d1897826-5ee3-404f-9ce9-407493bc3deb)| 

2. 再次重申: **ISAT不会对图像进行任何更改，用户自己的数据自己负责**
    饱和度调整只是显示问题，没有调整图像，只针对手动标注时，方便人眼识别细节；不会对sam结果有任何影响。
