### ISSUE TITLE
类别快捷键对应的类别很迷糊

### ISSUE THREAD

**Issue by 258692011** [yatengLG/ISAT_with_segment_anything#230]
1、类别很难看出来对应哪个快捷键，界面上要不加个id，显示对应的编号，读取isat.yaml，for i 把计次写到界面，类别搜索也是

1  __background__
2  person
3  knife
4  fork
5  cup
6  giraffe

2、或者直接在界面上竖向写上固定死的id，1234567890

![QQ20241105-162331](https://github.com/user-attachments/assets/17f88f3c-896e-49e1-a51e-f8a77b7a15cf)

**Comment by 258692011** [comment]
类似下面这个图
序号 ＝ 序号 ＋ 1

![QQ20241105-163532](https://github.com/user-attachments/assets/4a5e0417-30cd-49c4-8aff-87fdb3e7cbd2)

**Comment by 258692011** [comment]
![QQ20241105-164256](https://github.com/user-attachments/assets/0acf97c4-e27c-447a-a3e0-651ae8c12f52)

**Comment by yatengLG** [comment]
不添加了。添加这个属于多此一举。

类别快捷键，主要针对一些类别少的时候比较好用。快捷键对应哪一类基本上都记住了，不用看列表，直接按快捷键就行了。

如果类别多一些，也不多说，假如有十类，先不说对应关系好不好找（这是这个issue提出的关注点）。
就这个操作流程：先看类别列表，8对应table，然后，键盘再按8，这个处理逻辑就比较搞笑，都需要看类别列表了，为啥不直接点选一下？更何况按键盘8也没那么好按啊。

所以根本不是对应关系的问题。
