### ISSUE TITLE
关于轮廓模式的疑问

### ISSUE THREAD

**Issue by Victtttttt** [yatengLG/ISAT_with_segment_anything#231]
![10](https://github.com/user-attachments/assets/e93734a8-1272-4ef2-921d-8f9be1a8e631)
作者您好，正如您提供的测试图像，使用sam2_hiera_tiny.pt做测试、轮廓模式选择显示全部轮廓。针对作者提供的工具表现出来良好的效果，故咨询您几个问题：
1.模型能够标注出目标内部的背景如何实现的
2.如果使用其他分割模型进行训练、要想达到同样的分割效果需要怎么准备训练数据。
3.在标注实例分割模型数据时，我们标注了背景区域（如上图）和不标注背景区域有什么区别

**Comment by yatengLG** [comment]
1. 这个主要是模型分割出的mask就是镂空的。ISAT只是做了针对性处理。
2. 这个和具体模型无关，和标注的数据有关。有的数据在标注时就没有处理镂空区域，所以训练出来的模型也是无法识别的。
3. 我做分割一直都是采用VOC格式png标签（polygon形式的标签本身就无法处理镂空区域）。ISAT在转换VOC格式png时，不标注区域与标注为背景区域像素都为0。添加背景类只是为了更好的处理镂空区域。

**Comment by Victtttttt** [comment]
假设现在我有一批数据都采用上图的方式对数据进行标注（目标内部出现镂空的情况都标注为背景），然后将ISAT再转换成VOC格式的png，制作成训练数据，那模型分割出来的mask会是镂空的吗？

**Comment by yatengLG** [comment]
> 假设现在我有一批数据都采用上图的方式对数据进行标注（目标内部出现镂空的情况都标注为背景），然后将ISAT再转换成VOC格式的png，制作成训练数据，那模型分割出来的mask会是镂空的吗？

是的

**Comment by Victtttttt** [comment]
> > 假设现在我有一批数据都采用上图的方式对数据进行标注（目标内部出现镂空的情况都标注为背景），然后将ISAT再转换成VOC格式的png，制作成训练数据，那模型分割出来的mask会是镂空的吗？
> 
> 是的

好的，谢谢您的建议
