### ISSUE TITLE
是否能够增加跨文件复制粘贴的功能

### ISSUE THREAD

**Issue by YMDong-GitHub** [yatengLG/ISAT_with_segment_anything#234]
考虑到当前的复制粘贴只能在同一文件内进行，而有一些标注任务部分图片之间存在相同的掩膜，如果增加跨文件复制粘贴的功能，将不需要对重复的掩膜再次标注。
这样不仅可以免除重复标注产生的额外工作量，也能有效避免两次标注不一致而引发的标注歧义的问题。

**Comment by YMDong-GitHub** [comment]
视频帧预测可以实现类似功能，并且更好

**Comment by yatengLG** [comment]
> 视频帧预测可以实现类似功能，并且更好

是的，刚想回你这个

**Comment by YMDong-GitHub** [comment]
楼主有考虑把sam2.1更新进去吗，我自己折腾进去后，初始化一切正常，但是只能使用point prompt预测，使用预测下一视频帧就会闪退。
----------------------------------------
* Init SAM... *
  - device  : cuda
  - dtype   : torch.bfloat16
  - loading : E:\ISAT_with_segment_anything-1.2.6\ISAT\checkpoints\sam2.1_hiera_large.pt
* Init SAM finished *
----------------------------------------
----------------------------------------
* Init SAM for video... *
  - device  : cuda
  - dtype   : torch.bfloat16
  - loading : E:\ISAT_with_segment_anything-1.2.6\ISAT\checkpoints\sam2.1_hiera_large.pt
* Init SAM for video finished *
----------------------------------------
sam_tag: True sam_video_tag:  True
Warning: The file C:/Users/PS/Desktop/texture\000.json is not a ISAT json.
Warning: The file C:/Users/PS/Desktop/texture\000.json is not a ISAT json.
E:\Grounded-SAM-2\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  x = F.scaled_dot_product_attention(
self.start_frame_idx:  1
self.max_frame_num_to_track:  1
init state finished.

进程已结束，退出代码为 -1073740791 (0xC0000409)

**Comment by yatengLG** [comment]
会添加的。但近期顾不上，得等会儿。
