### ISSUE TITLE
怎么把自己的分割模型加入模型管理的选择栏中

### ISSUE THREAD

**Issue by Paphael** [yatengLG/ISAT_with_segment_anything#235]
我自己下载了分割模型，放在了checkpoints目录下，但我怎么在模型管理中选择我需要用的模型，我在模型管理中没有看到我自己下载的分割模型

**Comment by yatengLG** [comment]
......

1. ISAT提供的模型
    在模型管理界面，直接就可以点击下载（不需要自己另外下载）
2. 非ISAT提供的模型
2.1 自己微调或训练的sam模型，如果isat提供了对应模型的支持（sam, sam2, mobile-sam, edegsam, samhq等），把权重名更改为对应原始权重名，复制到checkpoint下就可以使用。
2.2 其他魔改的sam模型，且ISAT没有提供支持，那就改代码吧
