### ISSUE TITLE
ISAT json to voc png 问题

### ISSUE THREAD

**Issue by LinJing517** [yatengLG/ISAT_with_segment_anything#236]
转voc png时，未使用实例分割，转出的图片是全黑的，使用了其他的灰度图转伪彩色图工具进行了转换，还是没有显示出来标注的地方，但是用实例分割导出的png就是正常的

**Comment by yatengLG** [comment]
> 转voc png时，未使用实例分割，转出的图片是全黑的，使用了其他的灰度图转伪彩色图工具进行了转换，还是没有显示出来标注的地方，但是用实例分割导出的png就是正常的

标注的什么类别？不会只标注了__background__类吧

**Comment by yatengLG** [comment]
![image](https://github.com/user-attachments/assets/2fffd2f6-f3e7-4d69-8948-f92f10bc5857)

这是刚测的，没有问题。

你可以用项目给的example的例子，测试下。

**Comment by LinJing517** [comment]
> > 转voc png时，未使用实例分割，转出的图片是全黑的，使用了其他的灰度图转伪彩色图工具进行了转换，还是没有显示出来标注的地方，但是用实例分割导出的png就是正常的
> 
> 标注的什么类别？不会只标注了__background__类吧

嗯 只标注了__background__类，是不是标错了，是不是需要新建个标签重复标注啊

**Comment by yatengLG** [comment]
__background__是默认添加的背景类

你需要在设置里面配置下自己需要标注的类别

**Comment by LinJing517** [comment]
> __background__是默认添加的背景类
> 
> 你需要在设置里面配置下自己需要标注的类别

嗯 添加了新的标签 重新标注可以了，感谢！！！
