### ISSUE TITLE
model.image_encoder_error

### ISSUE THREAD

**Issue by sunpengjian** [yatengLG/ISAT_with_segment_anything#237]
请问以下报错则呢么回事？我加载Mobilesam就没问题
Init SAM2 video Error:  Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.image_encoder.trunk
sam_tag: False sam_video_tag:  False.

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the SegAnyVideo class to better handle SAM2 model loading errors, provide more informative error messages, and fallback to MobileSAM if SAM2 loading fails.

You can review changes in this commit: https://github.com/kkpo4553/yatengLG-ISAT_with_segment_anything-237/commit/a42cc0611fad32b266445672758c3c15dee82e6a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by yatengLG** [comment]
> 请问以下报错则呢么回事？我加载Mobilesam就没问题 Init SAM2 video Error: Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: model.image_encoder.trunk sam_tag: False sam_video_tag: False.

啥模型啊？大概率是你torch版本问题

**Comment by sunpengjian** [comment]
> > 请问以下报错则呢么回事？我加载Mobilesam就没问题 Init SAM2 video Error: Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: model.image_encoder.trunk sam_tag: False sam_video_tag: False.
> 
> 啥模型啊？大概率是你torch版本问题

torch版本是2.3.1GPU版。我能加载MobileSAM，但是加载SAM2无反应。显卡是1660SUPER显存6G

**Comment by sunpengjian** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modify the SegAnyVideo class to better handle SAM2 model loading errors, provide more informative error messages, and fallback to MobileSAM if SAM2 loading fails.
> 
> You can review changes in this commit: [kkpo4553@a42cc06](https://github.com/kkpo4553/yatengLG-ISAT_with_segment_anything-237/commit/a42cc0611fad32b266445672758c3c15dee82e6a).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

* Init SAM for video... *
ERROR:root:Error initializing SAM2: 'SegAnyVideo' object has no attribute 'model_type'
Falling back to MobileSAM...
Init SAM2 video Error:  name 'sam_model_registry' is not defined
sam_tag: False sam_video_tag:  False

**Comment by sunpengjian** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modify the SegAnyVideo class to better handle SAM2 model loading errors, provide more informative error messages, and fallback to MobileSAM if SAM2 loading fails.
> 
> You can review changes in this commit: [kkpo4553@a42cc06](https://github.com/kkpo4553/yatengLG-ISAT_with_segment_anything-237/commit/a42cc0611fad32b266445672758c3c15dee82e6a).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

* Init SAM for video... *
  - device  : cuda
  - dtype   : torch.bfloat16
  - loading : Meta_Seg\ISAT_with_segment_anything-master\ISAT\checkpoints\sam2.1_hiera_tiny.pt
ERROR:root:Error initializing SAM2: Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.image_encoder.trunk
Falling back to MobileSAM...
  - device  : cuda
  - dtype   : torch.bfloat16
  - loading : ./ISAT/checkpoints/mobile_sam.pt
* Init SAM for video finished *

**Comment by yatengLG** [comment]
```
export HYDRA_FULL_ERROR=1
python main.py
```
你把这个环境变量加上，瞅瞅啥报错吧，可能是硬件或者cuda问题了。

**Comment by yatengLG** [comment]
报错应该是： full_key: model.image_encoder.trunk

sam2也有人遇到这个问题了，是环境问题，缺少了sam2的依赖。https://github.com/facebookresearch/sam2/issues/380

1. 如果是 pip安装的，应该不会遇到这个问题，如果遇到可以pip install isat-sam --upgrade更新一下
2. 如果是源码安装的，pip install -r requirements.txt 安装下新的依赖包
