### ISSUE TITLE
关于图片标注和json的转换

### ISSUE THREAD

**Issue by cvv-student** [yatengLG/ISAT_with_segment_anything#238]
很棒的工作！
我已经有了一些分割的结果，但是效果不太对劲，也能省点力，但是结果对应着图片格式，那我该如何将单通道的灰度图片转成isat能读取的json格式，或者哪些是isat读取label的代码，方便我研读一下

**Comment by yatengLG** [comment]
要将灰度图转为ISAT格式的json，可以参考以下步骤：

1. 读取灰度图，获取mask
2. mask转为polygon
  这部分代码可以参考：
https://github.com/yatengLG/ISAT_with_segment_anything/blob/c3a29117797027dbce60aa86c218ad7f3b0b7396/ISAT/widgets/canvas.py#L281-L324
4. 将转换后的polygon顶点与其他信息写入到json中。
  ISAT的json格式可以参考：
https://github.com/yatengLG/ISAT_with_segment_anything/blob/c3a29117797027dbce60aa86c218ad7f3b0b7396/ISAT/scripts/isat.py#L12-L180

**Comment by cvv-student** [comment]
感谢回复，我已经成功转换并且读取

**Comment by yatengLG** [comment]
后续标注完，如果你还是需要图片形式的标注，可以使用VOC格式的单通道png。

在工具栏-工具-数据转换中提供了各种常见数据的转换功能。
