### ISSUE TITLE
关于模型加载的错误

### ISSUE THREAD

**Issue by le-wei** [yatengLG/ISAT_with_segment_anything#239]
模型已经下载到对应文件目录，但是选择模型是出现下面的错误
* Init SAM... *
  - device  : cuda
  - dtype   : torch.float32
  - loading : /ISAT_with_segment_anything/ISAT/checkpoints/sam2_hiera_large.pt
config_file:  sam2_hiera_l.yaml
Init SAM Error:  Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.image_encoder.trunk
----------------------------------------
* Init SAM for video... *
  - device  : cuda
  - dtype   : torch.float32
  - loading : /ISAT_with_segment_anything/ISAT/checkpoints/sam2_hiera_large.pt
Init SAM2 video Error:  Error locating target 'ISAT.segment_any.sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.image_encoder.trunk
sam_tag: False sam_video_tag:  False

**Comment by yatengLG** [comment]
缺包了，检查下 requirements.txt的包都装好没。目测是缺了iopath包。

另外，不用自行下载模型，软件提供了模型管理，点击自动就下载了。

**Comment by yatengLG** [comment]
- 建议使用pip安装
  安装: 'pip install isat-sam'
  运行: 'isat-sam'

实际使用中，如果发现bug或有什么建议，欢迎issue。
