### ISSUE TITLE
环境配置成功但是图片无法显示

### ISSUE THREAD

**Issue by yc-whu** [yatengLG/ISAT_with_segment_anything#24]
我按照说明配置了环境，程序可以正常运行，但是我点击右下侧图像时，终端CUDA报错，不知道什么原因？我是新手--new hand。
![Screenshot from 2023-05-28 11-41-20](https://github.com/yatengLG/ISAT_with_segment_anything/assets/111022936/a767912f-f88e-4565-b3ea-3246def461b1)
![Screenshot from 2023-05-28 11-41-28](https://github.com/yatengLG/ISAT_with_segment_anything/assets/111022936/95ea78d7-850b-40de-a2ec-256b161ef764)

**Comment by yatengLG** [comment]
解决了嘛？

**Comment by yc-whu** [comment]
没解决，可以发一下你的cuda和pytorch版本吗

**Comment by yatengLG** [comment]
> 没解决，可以发一下你的cuda和pytorch版本吗

你不用按我的来，你应该是cuda版本不够，3090比较新吧。

https://blog.csdn.net/qq_40968179/article/details/129003406

**Comment by yatengLG** [comment]
你pytroch装高一点儿没事儿的，依赖问题不大

**Comment by yc-whu** [comment]
问题已解决，真手把手教
