### ISSUE TITLE
分割出来的物体，边缘不是那么平滑

### ISSUE THREAD

**Issue by foocker** [yatengLG/ISAT_with_segment_anything#25]
有计划再写一个，边缘编辑，局部填充，使得分割出来的物件，更光滑。 
类似于ps里面的切割，图层使用那里。吗？ (不会写qt，chatgpt生成出来的代码，老失败)
我是这样问的：
```
用 pyqt实现一个图像编辑界面：实现
1.边缘检测按钮，
2.光滑边缘按钮，
3.鼠标点击检测到的边缘做修改，使其更光滑，
4.鼠标画一条光滑的边缘线按钮，
5.让显示图在边缘线内部保持局部像素一致，实现图像边缘局部修复效果。
```
还有就是输入， rgba可以优化下。最后合并a通道。

**Comment by yatengLG** [comment]
1. 分割效果依赖于SAM性能，这个上限是定死的。
2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162

4. rgba输入进行标注不是问题，但SAM输入强制三通道图片。

5. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154

**Comment by foocker** [comment]
> 

可以， 我测试一下看看。
另外我用gptxx生成的代码：
```
import sys
import cv2
import numpy as np
from PyQt5.QtGui import QImage, QPixmap, QPainter, QPen, QBrush
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QVBoxLayout, QPushButton, QFileDialog, \
    QGraphicsScene, QGraphicsView
from PyQt5.QtCore import Qt, QRectF, QPointF
from PyQt5.QtCore import QEventLoop, QEvent
from PyQt5.QtWidgets import QMessageBox, QSlider


class ImageViewer(QMainWindow):
    def __init__(self):
        super().__init__()
        self.image = None
        self.tmp_image = None
        self.filename = ""
        self.scale_factor = 1.0
        self.edge_points = []  # 存储绘制的边缘点
        self.smoothing_factor = 0.5  # 平滑拟合的参数
        self.initUI()

    def initUI(self):
        self.setWindowTitle('图像编辑器')
        self.setGeometry(100, 100, 800, 600)

        # 创建显示图像的场景和视图
        self.scene = QGraphicsScene(self)
        self.view = QGraphicsView(self.scene)
        self.view.setRenderHint(QPainter.Antialiasing)
        self.view.setDragMode(QGraphicsView.ScrollHandDrag)
        self.view.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.view.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.view.setResizeAnchor(QGraphicsView.AnchorUnderMouse)

        # 创建按钮
        import_button = QPushButton('导入图片')
        import_button.clicked.connect(self.showDialog)
        smooth_button = QPushButton('画光滑边缘线')
        smooth_button.clicked.connect(self.startDrawing)
        
        # 创建滑竿和标签
        self.slider = QSlider(Qt.Horizontal)
        self.slider.setMinimum(1)
        self.slider.setMaximum(10)
        self.slider.setValue(5)
        self.slider.setTickInterval(1)
        self.slider.setTickPosition(QSlider.TicksBelow)

        self.slider_label = QLabel(str(self.slider.value()))

        # 连接滑竿的valueChanged信号到槽函数
        self.slider.valueChanged.connect(self.sliderValueChanged)
        # 通过在滑竿值改变时修改鼠标形状
        self.slider.valueChanged.connect(self.updateCursor)

        # 创建布局
        layout = QVBoxLayout()
        layout.addWidget(import_button)
        layout.addWidget(smooth_button)
        layout.addWidget(self.view)
        layout.addWidget(self.slider)
        layout.addWidget(self.slider_label)

        # 创建中心部件并设置布局
        central_widget = QLabel()
        central_widget.setLayout(layout)
        self.setCentralWidget(central_widget)
        
        # 创建中心部件并设置布局
        central_widget = QLabel()
        central_widget.setLayout(layout)
        self.setCentralWidget(central_widget)
    
    def updateCursor(self):
        """ 当滑竿值为1时，将鼠标形状设置为箭头（Qt.ArrowCursor），否则设置为十字架（Qt.CrossCursor）"""
        if self.slider.value() == 1:
            self.setCursor(Qt.ArrowCursor)
        else:
            self.setCursor(Qt.CrossCursor)

    def sliderValueChanged(self, value):
        self.slider_label.setText(str(value))

    def showDialog(self):
        self.filename, _ = QFileDialog.getOpenFileName(self, '打开图片', '', 'Image Files (*.png *.jpg *.jpeg)')
        if self.filename:
            self.loadImage()

    def loadImage(self):
        # 加载图片并根据窗口尺寸进行缩放
        image = cv2.imread(self.filename)
        height, width, _ = image.shape
        max_width = self.view.viewport().width()
        max_height = self.view.viewport().height()
        if width > max_width or height > max_height:
            self.scale_factor = min(max_width / width, max_height / height)
            image = cv2.resize(image, None, fx=self.scale_factor, fy=self.scale_factor, interpolation=cv2.INTER_AREA)
        self.image = image.copy()
        self.tmp_image = self.image.copy()
        self.displayImage()

    def displayImage(self):
        # 在场景中显示图片
        self.scene.clear()
        height, width, channel = self.tmp_image.shape
        bytes_per_line = channel * width
        q_image = QImage(self.tmp_image.data, width, height, bytes_per_line, QImage.Format_BGR888)
        pixmap = QPixmap.fromImage(q_image)
        self.scene.addPixmap(pixmap)
        self.view.setSceneRect(QRectF(pixmap.rect()))
        self.view.fitInView(self.view.sceneRect(), Qt.KeepAspectRatio)

    def startDrawing(self):
        self.view.setDragMode(QGraphicsView.NoDrag)
        self.view.viewport().installEventFilter(self)
        self.setCursor(Qt.CrossCursor)

    def eventFilter(self, source, event):
        if event.type() == QEvent.MouseButtonPress and source is self.view.viewport():
            if event.button() == Qt.LeftButton:
                self.drawPoint(event.pos())
        return super().eventFilter(source, event)

    def drawPoint(self, pos):
        # 绘制点
        scene_pos = self.view.mapToScene(pos) 
        # 添加到边缘点列表
        self.edge_points.append(scene_pos)

        # 绘制线段
        if len(self.edge_points) > 1: 
            prev_point = self.edge_points[-2]
            current_point = self.edge_points[-1]
            self.scene.addLine(prev_point.x(), prev_point.y(), current_point.x(), current_point.y(), QPen(Qt.red))

    def keyPressEvent(self, event): 
        if event.key() == Qt.Key_E:
            # 停止生成
            self.view.viewport().removeEventFilter(self)
            self.setCursor(Qt.ArrowCursor)
        else:
            super().keyPressEvent(event)
            
    def drawCurve(self):
        if len(self.edge_points) < 2:
            return
        
        # 清除场景  
        self.scene.clear()   
        # 绘制所有点和线段
        for i in range(len(self.edge_points)-1): 
            prev_point = self.edge_points[i]
            current_point = self.edge_points[i+1]
            self.scene.addEllipse(prev_point.x() - 2, prev_point.y() - 2, 4, 4, QPen(Qt.red), QBrush(Qt.red))
            self.scene.addLine(prev_point.x(), prev_point.y(), current_point.x(), current_point.y(), QPen(Qt.red))
        
        # 使用Bezier曲线拟合点
        curve_points = self.interpolatePoints(self.edge_points)

        # 创建临时图像副本
        tmp_image = self.image.copy()

        # 将tmp_image转换为QImage类型
        height, width, channel = tmp_image.shape
        bytesPerLine = channel * width
        qImg = QImage(tmp_image.data, width, height, bytesPerLine, QImage.Format_BGR888)

        # 创建绘制器
        painter = QPainter(qImg)
        pen_color = Qt.red
        pen_width = 2
        painter.setPen(QPen(pen_color, pen_width, Qt.SolidLine, Qt.RoundCap, Qt.RoundJoin))

        prev_point = curve_points[0]
        for point in curve_points[1:]:
            painter.drawLine(prev_point, point)
            prev_point = point

        painter.end()  # 结束绘制

        # 将QImage转换回numpy.ndarray类型
        tmp_image = np.array(qImg)

        # 更新临时图像
        self.tmp_image = tmp_image.copy()
        self.displayImage()


    def interpolatePoints(self, points):
        # 使用Bezier曲线插值算法拟合点
        t = np.linspace(0, 1, len(points))
        curve_points = []
        for i in range(len(points) - 1):
            p0, p1 = points[i], points[i + 1]
            cp0 = p0 + self.smoothing_factor * (p1 - p0)
            cp1 = p1 - self.smoothing_factor * (p1 - p0)
            curve_points.extend(self.bezierCurve(p0, cp0, cp1, p1, t))
        curve_points.append(points[-1])
        return curve_points

    def bezierCurve(self, p0, p1, p2, p3, t):
        # 计算Bezier曲线上的点
        u = 1 - t
        tt = t * t
        uu = u * u
        uuu = uu * u
        ttt = tt * t
        p = uuu * p0 + 3 * uu * t * p1 + 3 * u * tt * p2 + ttt * p3
        return p

    def smoothEdge(self):
        if len(self.edge_points) < 2:
            QMessageBox.warning(self, 'Message', '请先绘制边缘线')
            return
        # 平滑边缘线
        self.edge_points = self.interpolatePoints(self.edge_points)
        self.drawCurve()

    def updateSmoothingFactor(self, value):
        self.smoothing_factor = value / 100.0

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Z:
            self.undoDrawing()
        else:
            super().keyPressEvent(event)

    def undoDrawing(self):
        if self.edge_points:
            self.edge_points.pop()
            self.drawCurve()
    
    def regionGrowing(self):
        # 执行区域生长算法
        # 请根据具体需求实现该方法
        pass
        
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = ImageViewer()
    ex.show()
    sys.exit(app.exec_())

``` 
问题比较多。。

**Comment by foocker** [comment]
> 

另外问下，鼠标点击，其自动生成的mask有可能包含很远的无关的地方，你需要右键取消他，同时， 已经生成的区域，在左键增加点后，也会改变已经生成的区域。是sam本身算法的特性吧。 对obj的预测。 你至少对他预测后的值，做了阈值处理后，加了个findcontours？

**Comment by foocker** [comment]
> 1. 分割效果依赖于SAM性能，这个上限是定死的。
> 
>     2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162
> 
>     3. rgba输入进行标注不是问题，但SAM输入强制三通道图片。
> 
>     4. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154

感觉有必要加强一下对生成的边缘做编辑，使得其更细节，更光滑。 findcontours改变，保存了全部边缘点，但，你左键点击的时候，不能控制mask的细节。导致cut出来的图，边缘细节不好。  只能增加边缘编辑了。改变mask,给原图做1.2左右的放大，模糊，然后检测边缘，然后和原始的做合并，边缘为放大后的边缘/1.2。

**Comment by yatengLG** [comment]
> 

软件进行标注时，通过鼠标进行point prompt，每次点击把prompt传给SAM引导分割，所以每次点击都会刷新mask。

SAM会输出多级的分割mask，进行阈值筛选以后，选择了分数最大的mask，然后通过mask计算外接多边形，转为polygon。

如果你修改这部分逻辑的需求，可以看代码: 
1. SAM分割以及筛选mask：https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/segment_any/segment_any.py#L35

4. mask转polygon代码：https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L146

**Comment by foocker** [comment]
> > 
> 
> 软件进行标注时，通过鼠标进行point prompt，每次点击把prompt传给SAM引导分割，所以每次点击都会刷新mask。
> 
> SAM会输出多级的分割mask，进行阈值筛选以后，选择了分数最大的mask，然后通过mask计算外接多边形，转为polygon。
> 
> 如果你修改这部分逻辑的需求，可以看代码:
> 
>     1. SAM分割以及筛选mask：https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/segment_any/segment_any.py#L35
> 
>     2. mask转polygon代码：https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L146

看来就是和sam的mask预测有关系了，很难做边缘的细节控制。 改这些算法，不行，只有增加边缘控制按钮。 你增加了呀，只是整体mask的移动。。

**Comment by yatengLG** [comment]
> > 1. 分割效果依赖于SAM性能，这个上限是定死的。
> >    
> >    2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162
> >    3. rgba输入进行标注不是问题，但SAM输入强制三通道图片。
> >    4. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154
> 
> 感觉有必要加强一下对生成的边缘做编辑，使得其更细节，更光滑。 findcontours参数改变，可以保存全部边缘点，但，你左键点击的时候，不能控制mask的细节。导致cut出来的图，边缘细节不好。 只能增加边缘编辑了。改变mask：比如，给原图做1.2左右的放大，模糊，然后检测边缘，然后和原始的做合并，边缘为放大后的边缘/1.2。但是还是要编辑。。
> 
> 您看gptxx写的代码，能搞么。 我感觉他理解的qt不过关啊。给你这个增加个边缘编辑功能， 直接出cut 部分图。


1. 这个mask质量上限是SAM带来的，鼠标点击出的mask，是SAM计算得到的，所以无法控制mask细节。
2. 不存在不能控制mask，才增加边缘编辑的问题。因为本身软件就是一个标注工具，标注的二次修改是我软件的必要功能。
3. 改变mask部分的提议，不是一个边缘检测可以做到的，给定一个多边形与一张图片，按照你提供的思路，需要的步骤是：
（1）全图边缘提取。提取得到的边缘线段会非常繁杂，包含各种边缘曲线
（2）计算mask与图中所有边缘的距离，并自动调整。这方面也是不太现实的。
（3）修正mask

我看了下你的issue的描述，你的需求应该不是标注图片，而是想完美的抠图，你可以看下其他项目的实现方式，比如[Inpaint-Anything](https://github.com/geekyutao/Inpaint-Anything)等项目，这些项目可能会提供一些比较好的抠图思路。

单纯靠SAM实现完美抠图，是不现实的，边缘总会存在问题。

**Comment by foocker** [comment]
> > > 1. 分割效果依赖于SAM性能，这个上限是定死的。
> > >    
> > >    2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162
> > >    3. rgba输入进行标注不是问题，但SAM输入强制三通道图片。
> > >    4. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154
> > 
> > 
> > 感觉有必要加强一下对生成的边缘做编辑，使得其更细节，更光滑。 findcontours参数改变，可以保存全部边缘点，但，你左键点击的时候，不能控制mask的细节。导致cut出来的图，边缘细节不好。 只能增加边缘编辑了。改变mask：比如，给原图做1.2左右的放大，模糊，然后检测边缘，然后和原始的做合并，边缘为放大后的边缘/1.2。但是还是要编辑。。
> > 您看gptxx写的代码，能搞么。 我感觉他理解的qt不过关啊。给你这个增加个边缘编辑功能， 直接出cut 部分图。
> 
>     1. 这个mask质量上限是SAM带来的，鼠标点击出的mask，是SAM计算得到的，所以无法控制mask细节。
> 
>     2. 不存在不能控制mask，才增加边缘编辑的问题。因为本身软件就是一个标注工具，标注的二次修改是我软件的必要功能。
> 
>     3. 改变mask部分的提议，不是一个边缘检测可以做到的，给定一个多边形与一张图片，按照你提供的思路，需要的步骤是：
>        （1）全图边缘提取。提取得到的边缘线段会非常繁杂，包含各种边缘曲线
>        （2）计算mask与图中所有边缘的距离，并自动调整。这方面也是不太现实的。
>        （3）修正mask
> 
> 
> 我看了下你的issue的描述，你的需求应该不是标注图片，而是想完美的抠图，你可以看下其他项目的实现方式，比如[Inpaint-Anything](https://github.com/geekyutao/Inpaint-Anything)等项目，这些项目可能会提供一些比较好的抠图思路。
> 
> 单纯靠SAM实现完美抠图，是不现实的，边缘总会存在问题。

是的，和标注软件是有出入的。 我想的是，sam快速出一个粗糙的边缘，然后鼠标画一个包围粗边缘的外边缘，然后，类似区域生，进行填充。 得到一个新的高质量的mask，但，同时在填充部分，保存距离信息，可能要做做融合。
不过你提的inpaint-anthing,确实似乎更合适。 但，怕就怕在细节还是不行， 还是需要描边啊。

**Comment by yatengLG** [comment]
> > > > 1. 分割效果依赖于SAM性能，这个上限是定死的。
> > > >    
> > > >    2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162
> > > >    3. rgba输入进行标注不是问题，但SAM输入强制三通道图片。
> > > >    4. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154
> > > 
> > > 
> > > 感觉有必要加强一下对生成的边缘做编辑，使得其更细节，更光滑。 findcontours参数改变，可以保存全部边缘点，但，你左键点击的时候，不能控制mask的细节。导致cut出来的图，边缘细节不好。 只能增加边缘编辑了。改变mask：比如，给原图做1.2左右的放大，模糊，然后检测边缘，然后和原始的做合并，边缘为放大后的边缘/1.2。但是还是要编辑。。
> > > 您看gptxx写的代码，能搞么。 我感觉他理解的qt不过关啊。给你这个增加个边缘编辑功能， 直接出cut 部分图。
> > 
> > 
> > ```
> > 1. 这个mask质量上限是SAM带来的，鼠标点击出的mask，是SAM计算得到的，所以无法控制mask细节。
> > 
> > 2. 不存在不能控制mask，才增加边缘编辑的问题。因为本身软件就是一个标注工具，标注的二次修改是我软件的必要功能。
> > 
> > 3. 改变mask部分的提议，不是一个边缘检测可以做到的，给定一个多边形与一张图片，按照你提供的思路，需要的步骤是：
> >    （1）全图边缘提取。提取得到的边缘线段会非常繁杂，包含各种边缘曲线
> >    （2）计算mask与图中所有边缘的距离，并自动调整。这方面也是不太现实的。
> >    （3）修正mask
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我看了下你的issue的描述，你的需求应该不是标注图片，而是想完美的抠图，你可以看下其他项目的实现方式，比如[Inpaint-Anything](https://github.com/geekyutao/Inpaint-Anything)等项目，这些项目可能会提供一些比较好的抠图思路。
> > 单纯靠SAM实现完美抠图，是不现实的，边缘总会存在问题。
> 
> 是的，和标注软件是有出入的。 我想的是，sam快速出一个粗糙的边缘，然后鼠标画一个包围粗边缘的外边缘，然后，类似区域生，进行填充。 得到一个新的高质量的mask，但，同时在填充部分，保存距离信息，可能要做做融合。 不过你提的inpaint-anthing,确实似乎更合适。 但，怕就怕在细节还是不行， 还是需要描边啊。


像inpaint-anthing也没有做的你描述的完美抠图，他是基于SAM做了一个mask，然后放大mask区域，保证mask可以覆盖整个目标，然后移除mask区域，通过扩散模型进行填充。

你描述的需求方向，我关注的比较少，没见过开源的实现。 

不过既然ps能做的传统算法抠图，基于SAM的粗mask与图像边缘特征，理论上可以实现你的需求，但这方面我了解的比较少。

**Comment by foocker** [comment]
> > > > > 1. 分割效果依赖于SAM性能，这个上限是定死的。
> > > > >    
> > > > >    2. 边缘粗糙问题，是多边形轮廓造成的（这部分也是故意为之，毕竟是标注工具，没有保存所有轮廓点的需要，所以轮廓相对mask粗糙一些），你可以把CHAIN_APPROX_TC89_KCOS改用其他算法，比如CHAIN_APPROX_NONE。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L162
> > > > >    3. rgba输入进行标注不是问题，但SAM输入强制三通道图片。
> > > > >    4. 如果你有使分割更光滑的需求，可以在下述代码处进行添加，这部分是mask转polygon的主要代码，你优化mask即可。具体代码在https://github.com/yatengLG/ISAT_with_segment_anything/blob/709b19e1d8ccdb8f3d96c09dbce6b18e3024935e/widgets/canvas.py#L154
> > > > 
> > > > 
> > > > 感觉有必要加强一下对生成的边缘做编辑，使得其更细节，更光滑。 findcontours参数改变，可以保存全部边缘点，但，你左键点击的时候，不能控制mask的细节。导致cut出来的图，边缘细节不好。 只能增加边缘编辑了。改变mask：比如，给原图做1.2左右的放大，模糊，然后检测边缘，然后和原始的做合并，边缘为放大后的边缘/1.2。但是还是要编辑。。
> > > > 您看gptxx写的代码，能搞么。 我感觉他理解的qt不过关啊。给你这个增加个边缘编辑功能， 直接出cut 部分图。
> > > 
> > > 
> > > ```
> > > 1. 这个mask质量上限是SAM带来的，鼠标点击出的mask，是SAM计算得到的，所以无法控制mask细节。
> > > 
> > > 2. 不存在不能控制mask，才增加边缘编辑的问题。因为本身软件就是一个标注工具，标注的二次修改是我软件的必要功能。
> > > 
> > > 3. 改变mask部分的提议，不是一个边缘检测可以做到的，给定一个多边形与一张图片，按照你提供的思路，需要的步骤是：
> > >    （1）全图边缘提取。提取得到的边缘线段会非常繁杂，包含各种边缘曲线
> > >    （2）计算mask与图中所有边缘的距离，并自动调整。这方面也是不太现实的。
> > >    （3）修正mask
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我看了下你的issue的描述，你的需求应该不是标注图片，而是想完美的抠图，你可以看下其他项目的实现方式，比如[Inpaint-Anything](https://github.com/geekyutao/Inpaint-Anything)等项目，这些项目可能会提供一些比较好的抠图思路。
> > > 单纯靠SAM实现完美抠图，是不现实的，边缘总会存在问题。
> > 
> > 
> > 是的，和标注软件是有出入的。 我想的是，sam快速出一个粗糙的边缘，然后鼠标画一个包围粗边缘的外边缘，然后，类似区域生，进行填充。 得到一个新的高质量的mask，但，同时在填充部分，保存距离信息，可能要做做融合。 不过你提的inpaint-anthing,确实似乎更合适。 但，怕就怕在细节还是不行， 还是需要描边啊。
> 
> 像inpaint-anthing也没有做的你描述的完美抠图，他是基于SAM做了一个mask，然后放大mask区域，保证mask可以覆盖整个目标，然后移除mask区域，通过扩散模型进行填充。
> 
> 你描述的需求方向，我关注的比较少，没见过开源的实现。
> 
> 不过既然ps能做的传统算法抠图，基于SAM的粗mask与图像边缘特征，理论上可以实现你的需求，但这方面我了解的比较少。

嗯，我刚也去看了inpaint-anything, 确实不符合。 其实主要就是对sam生成的mask做一个可控的扩展。inpaint-anything,是扩展了，但不精细，给生成用的。精细的只能人去做，就是拖动鼠标，编辑线条。
