### ISSUE TITLE
This plugin does not support propagateSizeHints()

### ISSUE THREAD

**Issue by dpsfigo** [yatengLG/ISAT_with_segment_anything#26]
按照要求安装了所有环境，但是运行python main.py的时候报错了，请问下该怎么解决？

**Comment by yatengLG** [comment]
可以说下具体报错嘛？

**Comment by dpsfigo** [comment]
运行main.py文件的时候报这个错，就停在这里了。
Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/imageformats" ...
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so"
loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so"
QFactoryLoader::QFactoryLoader() checking directory path "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessiblebridge" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/accessiblebridge" ...
QFactoryLoader::QFactoryLoader() checking directory path "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/accessible" ...
This plugin does not support propagateSizeHints()

**Comment by yatengLG** [comment]
> 运行main.py文件的时候报这个错，就停在这里了。 Got keys from plugin meta data ("webp") QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/imageformats" ... loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqgif.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqicns.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqico.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqjpeg.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqsvg.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtga.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqtiff.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwbmp.so" loaded library "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/imageformats/libqwebp.so" QFactoryLoader::QFactoryLoader() checking directory path "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessiblebridge" ... QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/accessiblebridge" ... QFactoryLoader::QFactoryLoader() checking directory path "/home/.virtualenvs/seg/lib/python3.8/site-packages/PyQt5/Qt5/plugins/accessible" ... QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/accessible" ... This plugin does not support propagateSizeHints()

这个是QT环境报的错，换个pyqt版本试一试或者百度搜一下怎么解决吧。
