### ISSUE TITLE
还是无法检测到checkpoint

### ISSUE THREAD

**Issue by Richardg706** [yatengLG/ISAT_with_segment_anything#27]
已经把预训练模型下载到了segment_any路径下，为什么运行还是无法使用呢？
![`Y G@%VU3QOVW`2YTX@(9E1](https://github.com/yatengLG/ISAT_with_segment_anything/assets/104958583/cc04cede-4e70-4be6-8978-d088172d0dd5)
![1F2C72160083CDCD4CD490B658FEC683](https://github.com/yatengLG/ISAT_with_segment_anything/assets/104958583/22ce16e3-8f99-4f3b-b0b7-ae18a89af4c0)

**Comment by yatengLG** [comment]
是不是路径问题。

具体这个代码在这行：https://github.com/yatengLG/ISAT_with_segment_anything/blob/d1e2ffc2391e9a4273e184d5375f3394e8ec4726/widgets/mainwindow.py#L62

之前在windows上运行过，没出现你描述的这个问题。

**Comment by Richardg706** [comment]
路径没有问题，我试了改成绝对路径还有加上转义符，用其他代码测试os.path返回值是true，但是还是一直出错

**Comment by yatengLG** [comment]
你测试下，这行代码返回的是True嘛？
https://github.com/yatengLG/ISAT_with_segment_anything/blob/d1e2ffc2391e9a4273e184d5375f3394e8ec4726/widgets/mainwindow.py#L62

现在的提示窗口代码是在
https://github.com/yatengLG/ISAT_with_segment_anything/blob/d1e2ffc2391e9a4273e184d5375f3394e8ec4726/widgets/mainwindow.py#L75

如果 if os.path.exists('./segment_any/sam_vit_h_4b8939.pth'): 返回的是True，就不会走提示窗口的分支。
