### ISSUE TITLE
支持使用 LoRA做了finetune的模型吗

### ISSUE THREAD

**Issue by liuhengli** [yatengLG/ISAT_with_segment_anything#28]
我使用LoRA在自己的数据上做了微调，想用这个做标注模型

**Comment by yatengLG** [comment]
可以啊，你可以更改下计算mask的代码。 项目中是使用SAM计算的mask，你可以改为使用lora。

计算mask的代码在：
https://github.com/yatengLG/ISAT_with_segment_anything/blob/fff96f6d2f32d64e6b206750d243c45349849d77/widgets/canvas.py#L364

应该还有一些其他逻辑方面的小改动。

**Comment by liuhengli** [comment]
非常感谢，我试一下
