### ISSUE TITLE
SAM clone issue

### ISSUE THREAD

**Issue by Alias-z** [yatengLG/ISAT_with_segment_anything#29]
On MacOS, `git clone git@github.com:facebookresearch/segment-anything.git` may not work as it shows below:
`Cloning into 'segment-anything'... `
`git@github.com: Permission denied (publickey).`
`fatal: Could not read from remote repository.`

Instead, one could run `git clone https://github.com/facebookresearch/segment-anything.git`

Btw, thanks for your great efforts!

**Comment by yatengLG** [comment]
Maybe you can try ```git clone https://github.com/facebookresearch/segment-anything.git``` to clone SAM.

**Comment by yatengLG** [comment]
Thanks, You have already solved this problem.
