### ISSUE TITLE
想问一下这个错是为什么 啊

### ISSUE THREAD

**Issue by yutian7036** [yatengLG/ISAT_with_segment_anything#3]
The checkpoint of [Segment anything] not existed.If you want use quick
annotate,please download from https:// github.com/facebookresearch/segment- anything#model-checkpoints

已经安装了segment_anything

**Comment by yatengLG** [comment]
> The checkpoint of [Segment anything] not existed.If you want use quick annotate,please download from https:// github.com/facebookresearch/segment- anything#model-checkpoints
> 
> 已经安装了segment_anything

需要去下载segment anything的预训练模型

```text
# 下载Segment anything预训练模型
下载任一模型，并将模型存放于ISAT_with_segment_anything/segment_any目录下
模型链接：
   https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
   https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth
   https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
h模型最大，效果也最好；
b模型最小，效果也最差；
请按照硬件下载合适的模型，h模型在示例样本上的显存需求约8G.
```

**Comment by yutian7036** [comment]
好的，谢谢啦
