### ISSUE TITLE
更新了一下，变成cpu了，之前是cuda：显存占用，怎么回事

### ISSUE THREAD

**Issue by zidddd9527** [yatengLG/ISAT_with_segment_anything#30]
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/110211430/e6c65ee7-213a-4db8-af69-187604d25f07)

**Comment by yatengLG** [comment]
我确认了下更新代码，没有问题。

这个cpu提示只是因为 if torch.cuda.is_available() 返回了False

具体代码在widgets/mainwindows.py的85行

**Comment by yatengLG** [comment]
相关代码在：

https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/mainwindow.py#LL80C13-L85C53

https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/segment_any/segment_any.py#L20

**Comment by zidddd9527** [comment]
> 相关代码在：
> 
> https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/mainwindow.py#LL80C13-L85C53
> 
> https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/segment_any/segment_any.py#L20

谢谢，我是重装了一遍pytorch，可以了

**Comment by zidddd9527** [comment]
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/110211430/ae7f7931-1e42-4eef-a001-7b1498267177)
更新一下
