### ISSUE TITLE
Support SAM in HQ

### ISSUE THREAD

**Issue by Alias-z** [yatengLG/ISAT_with_segment_anything#31]
Hi, the model checkpoints of segment anything in high quality just released. It could be nice to implement that?

[SAM-HQ](https://github.com/SysCV/sam-hq)

**Comment by yatengLG** [comment]
I have already noticed this project, just now. SAM-HQ segmentation effect is better than Sam from the project introduction. 

But some code is different in model decoder, must change code of SAM or re-install the SAM-HQ.

I will update code for support sam-hq, thanks.

**Comment by yatengLG** [comment]
近期测试了SAM-HQ，SAM-HQ的分割效果的确比较好，但是在提示方面效果较差，不适用于本项目。

**Comment by Alias-z** [comment]
> 

方便创建一个SAM-HQ分支吗，我可以来改善提示效果试试。SAM-HQ作者在我们学校，我应该可以联系到。

**Comment by yatengLG** [comment]
已经添加了SAM-hq支持，之前测试时不知道哪里出现问题了，这次提示部分没问题T.T

可以试用develop分支，功能还在添加

1. 更新了界面，现在左侧选择类别，试用SAM时，直接快捷键Q，鼠标提示，E完成标注即可，不再选择类别与组。
2. 菜单栏添加了mask转polygon的方式选择，分为a.保存所有外轮廓(单个多边形)，b.保存顶点数最多的外轮廓(单个多边形)，c.保存所有轮廓（内轮廓多边形类别默认为__background__）
3. 菜单栏添加了模型选择，列出segment_any文件夹下的所有.pth权重文件。
4. 支持了SAM-HQ
