### ISSUE TITLE
生成标签时候的问题

### ISSUE THREAD

**Issue by gtoo8888** [yatengLG/ISAT_with_segment_anything#32]
[![pCnTMkD.png](https://s1.ax1x.com/2023/06/14/pCnTMkD.png)](https://imgse.com/i/pCnTMkD)
图1：原始图像
[![pCnTn0K.png](https://s1.ax1x.com/2023/06/14/pCnTn0K.png)](https://imgse.com/i/pCnTn0K)
图2：segment_anaything分割后的效果，可以看到可以检测到小物块
[![pCnTuTO.png](https://s1.ax1x.com/2023/06/14/pCnTuTO.png)](https://imgse.com/i/pCnTuTO)
图3：生成标签以后，成了整体的一块标签，忽略了小物块

使用segment_anything分割时候是正常的，但是在生成标签以后出现了问题，对于我中间镂空的小物块，标签把他忽略掉了，可以看一下我提供的图片。
之前使用EISeg进行标注时候，也出现过这个问题，这是那个标注软件的地址：
https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/EISeg
我判断是生成的图片将生成的轮廓标签化的那个过程中，由于是中间镂空的，所以就被忽略掉了
可以告诉我源码的地址在哪里，我可以自己尝试修复一下

**Comment by yatengLG** [comment]
这个情况是刻意这么处理的，原因是：SAM分割后，为满足手动修改的需求，会将mask会转换为polygon（多边形），这个问题就是出现在转换过程。

其实转换过程可以计算保留所有的多边形，但是无法区分多边形方向（就是无法区分当前多边形需要的是内部区域还是外部区域，比如图2的大红框需要内部区域，而小目标区域需要的是外部区域，这种情况会出现问题）

软件提供的思路是，在图3的基础上，对小目标区域进行一次分割，并标注为背景，这样就可以实现镂空效果。
具体操作可参考演示视频4:35秒处，https://www.bilibili.com/video/BV1Lk4y1J7uB/ 


如果你想改动代码的话，具体转换过程从这里开始https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/canvas.py#L154

**Comment by gtoo8888** [comment]
感谢回答，现在使用标注为背景的方法可以解决问题，修改源码的话，看到位置了，如果之后有机会的话看看能不能提交pr
