### ISSUE TITLE
 LoRA做了finetune的模型

### ISSUE THREAD

**Issue by liuhengli** [yatengLG/ISAT_with_segment_anything#35]
你好，我做了finetune但是没有做prompt训练，当我点击一张图做标注的时候，整张图都标上了mask，是不是finetune阶段要做prompt训练才能支持这种标注

**Comment by yatengLG** [comment]
本项目依赖于SAM的点提示功能，所以在finetune的时候，应该是需要进行提示训练的（无责任猜想，我也没有finetune SAM T.T）。
