### ISSUE TITLE
ToCOCO Bug: potential categories mismatch splitting train / val datasets

### ISSUE THREAD

**Issue by Alias-z** [yatengLG/ISAT_with_segment_anything#36]
## The issue
Assuming we have all images and JSON files under a given folder, where we want to split them into train/val dataset for training. The structure may look as the following:

```
train //
    |__ train_image_1.png
    |_ ... .png
    |_ ... train_COCO.json


val //
    |__ val_image_1.png
    |_ ... .png
    |_ ... val_COCO.json
 ```

The categories of train_COCO.json may look like this:
 `categories": [{"name": "CLASS_A", "id": 0, "supercategory": null}, {"name": "CLASS_B", "id": 1, "supercategory": null}, {"name": "CLASS_C", "id": 2, "supercategory": null}, {"name": "CLASS_D", "id": 3, "supercategory": null}]`

While that of val_COCO.json:
`"categories": [{"name": "CLASS_A", "id": 0, "supercategory": null}, {"name": "CLASS_C", "id": 1, "supercategory": null}, {"name": "CLASS_B", "id": 2, "supercategory": null}, {"name": "CLASS_D", "id": 3, "supercategory": null}]`

Note that CLASS_B id =1 in train, while CLASS_B id=2 in val, which impacts model performance.

## Causation
train_image_1.png contains all four classes, while one of the classes was missing in val_image_1.png.

In line 42 of [toCOCO.py](https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/tools/toCOCO.py) `categories_dict = {}` , then categories were gradually added in line 88-89 ` if cat not in categories_dict:
categories_dict[cat] = len(categories_dict)`. **This means the categories' order depends on the first few images. （JSON 文件类别取决于前几张图片包含的类，如果类不全则可能引起最终训练和验证集种类id不匹配）** 

## Potential solutions
1. allow users to define categories: 
```
    def __init__(self):
        super(TOCOCO, self).__init__()
        self.isat_json_root:str = None
        self.to_path:str = None
        **self.categories_dict =None**
        self.cancel = False
```

2. alternatively, fetch the `categories_dict` from `isat.yaml`

## Results
train_COCO.json
`categories": [{"name": "CLASS_A", "id": 0, "supercategory": null}, {"name": "CLASS_B", "id": 1, "supercategory": null}, {"name": "CLASS_C", "id": 2, "supercategory": null}, {"name": "CLASS_D", "id": 3, "supercategory": null}]`
val_COCO.json
`categories": [{"name": "CLASS_A", "id": 0, "supercategory": null}, {"name": "CLASS_B", "id": 1, "supercategory": null}, {"name": "CLASS_C", "id": 2, "supercategory": null}, {"name": "CLASS_D", "id": 3, "supercategory": null}]`

**Comment by yatengLG** [comment]
I get your PR, and solve this question by add these codes:

https://github.com/yatengLG/ISAT_with_segment_anything/blob/5678f61bc6b332c6bf2eaf60e9db2e6df3e59d2d/tools/toCOCO.py#L43C2-L50C51

**Comment by Alias-z** [comment]
> I get your PR, and solve this question by add these codes:
> 
> https://github.com/yatengLG/ISAT_with_segment_anything/blob/5678f61bc6b332c6bf2eaf60e9db2e6df3e59d2d/tools/toCOCO.py#L43C2-L50C51

Hi, thanks for paying attention to this. My PR proposed an alternative solution to fetching from yaml (sorry that I forget to mention it). The concern is that if the user use the default configs which contains more classes than he/she needs, than fetching from PR will not be a good idea. For instance, the user would like to have only Class A, Class B, Class C while the default config also contains person, knife, fork... 

My solution ranked the classes' name first, and remapped their id, which has been tested to work. Please consider that!

**Comment by yatengLG** [comment]
这种解决方式是会引入多余的标签，但是对于实际使用不会有任何影响。
比如使用getAnnIds通过类别id获取标注id，多余的标签，会直接返回空列表[]，存在的类别会返回[ids]。

并且这样处理，有一个好处是，最终的categorie对应的id是固定的，与训练集与测试集中类别的分布无关。如果训练集中，存在A,B,C三类，测试集划分时出现问题只存在B,C两类，原先的方式就会存在问题。

对于这种情况，一般是不会出现的（除非手动更改了yaml或json文件），如果出现这种情况，在转换过程的最后，会进行提示。https://github.com/yatengLG/ISAT_with_segment_anything/blob/8c6f189d5974644ae3fffbe999c50cfc176f58b4/tools/toCOCO.py#L97

**Comment by yatengLG** [comment]
欢迎发起pr，对本项目贡献代码。O(∩_∩)O谢谢

**Comment by yatengLG** [comment]
> 作者您好，请问这个问题是解决了吗，也就是后续用户不需要关注他们俩是否一致啦？我这边新版ISAT还是可以看到两个的类别不一致[@yatengLG](https://github.com/yatengLG)

这个问题的核心点在于，ISAT转COCO时，只会按当前数据的类别进行转换。
后续我添加一个 读取类别yaml作为默认类别，就可以同步了（但也需要训练集和测试集都存在相同的类别yaml）

**Comment by yatengLG** [comment]
> 作者您好，请问这个问题是解决了吗，也就是后续用户不需要关注他们俩是否一致啦？我这边新版ISAT还是可以看到两个的类别不一致[@yatengLG](https://github.com/yatengLG)

刚提交了一个新的更新。主要针对转coco时的类别问题。

远古的版本，保存isat格式标签时，不会另存一份类别配置文件。（所以转换时，类别是边读取边添加，这就导致了类别顺序可能不一致的问题）

更新后，会读取待转换的isat标签目录下的isat.yaml文件，获取具体的类别列表。可以保证顺序的一致性。

另外，训练集/测试集划分后，在转换前，记得目录下都拷贝一份isat.yaml文件，以保证转换过程中的类别一致。
