### ISSUE TITLE
How to reserve the raw color of picture when using the SAM to label?

### ISSUE THREAD

**Issue by sunsunnyshine** [yatengLG/ISAT_with_segment_anything#38]
When I use the SAM to label ,the picture goes dark which is hard for labeling the object whose board is blur.Could you please instruct me to  modify the code to reserve the raw color?

**Comment by yatengLG** [comment]
You can change modify this code. 
The 0.5 is alpha of background, 0.9 is alpha of the mask.
You can change them to 1.
https://github.com/yatengLG/ISAT_with_segment_anything/blob/7e2b31bedfac500d38e0c80db972410733cfc62d/widgets/canvas.py#L378

**Comment by sunsunnyshine** [comment]
thank u so much~
