### ISSUE TITLE
有没有通过框进行标注的功能

### ISSUE THREAD

**Issue by Fairywyt** [yatengLG/ISAT_with_segment_anything#39]
在某些领域中，通过点击进行分割无法达到最优效果，通常采用先画框得到初版mask，最后进行点击修正可以得到令人满意的结果，同时节省大量操作，请问有没有通过框进行标注的功能，如果没有后续会加上吗

**Comment by yatengLG** [comment]
现阶段没有添加框提示这个功能

请问，点击提示无法满足您的需求，是因为点击提示的初始mask比较粗糙？还是后续的点提示修改会超出您的目标框范围？

一般初始mask不精确，通过多次点提示就可以达到非常好的效果。
