### ISSUE TITLE
默认打开是英文，如何在程序中修改，为中文

### ISSUE THREAD

**Issue by happybear1015** [yatengLG/ISAT_with_segment_anything#42]

**Comment by yatengLG** [comment]
界面上修改即可，about -> language -> 中文

**Comment by happybear1015** [comment]
OK，已经改好了





------------------ 原始邮件 ------------------
发件人: yatengLG ***@***.***&gt;
发送时间: 2023年6月27日 15:29
收件人: yatengLG/ISAT_with_segment_anything ***@***.***&gt;
抄送: happy-bear ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yatengLG/ISAT_with_segment_anything] 默认打开是英文，如何在程序中修改，为中文 (Issue #42)





 
界面上修改即可，about -&gt; language -&gt; 中文
