### ISSUE TITLE
只支持三通道的彩色图的报错

### ISSUE THREAD

**Issue by KKD4Soei** [yatengLG/ISAT_with_segment_anything#44]
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/58964439/13dc72d2-8850-4cb5-98c9-d94435b084d1)
如图，当加载黑白图是，报错显示只支持三通道彩色图。在SAM官网demo 可用黑白图，是否考虑增加。

**Comment by yatengLG** [comment]
https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L34

SAM的输入的确是三通道的。至于标注单通道图，也很好处理，直接转个三通道就可以了，不影响标注过程和结果的。

**Comment by KKD4Soei** [comment]
好的。明白了  感谢！

**Comment by yatengLG** [comment]
更新了，已经支持SAM标注单通道图片，你拉取最新版本试一下吧。
（单通道png彩图，依然默认是标签图片，不支持标注。）

**Comment by TianchouYin** [comment]
> 更新了，已经支持SAM标注单通道图片，你拉取最新版本试一下吧。 （单通道png彩图，依然默认是标签图片，不支持标注。）

jpg灰度图还是不行啊
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/63798894/52d8032c-964c-46c8-903d-a4824fd85709)

**Comment by TianchouYin** [comment]
> https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L34
> 
> SAM的输入的确是三通道的。至于标注单通道图，也很好处理，直接转个三通道就可以了，不影响标注过程和结果的。

我在SAM官网demo上传灰度图是可以标注的啊
https://segment-anything.com/demo
