### ISSUE TITLE
希望在segment anything结果的基础上进行更灵活的修改，不知有没有可以做到的方法或者工具？

### ISSUE THREAD

**Issue by August9708** [yatengLG/ISAT_with_segment_anything#45]
感谢大佬提供了这么好用的工具！但使用过程中还是有一些别的需求，冒昧来问问。

现阶段只能拖拽多边形的顶点进行调整（应该没弄错吧？），我希望在当前分割结果的基础上更多操作，比如：

1. 选中多边形的若干个点，并删除他们（有时划分太细致了，某个局部不希望划分那么细，但是很难直接得到理想结果）。
2. 在多边形内部划线，将一个多边形分成两部分（有时segmenent anything可以取出整体，但无法分割得到整体的几个部分，所以希望在借助segment anything提取出整体后，进一步手动划分）。

有没有办法实现（特别是2）呢？或者有没有其他工具可以做到？

**Comment by yatengLG** [comment]
一. 删除点的功能暂时没有。如果想修改代码添加该功能，需要修改的地方主要涉及两部分代码：
1. 这部分代码中，需添加端点选取后触发的事件（这里建议限制为同时只能选取一个端点，配合快捷键操作不会慢，但是处理逻辑会简单很多）
同时，这部分代码中，若存在被选取的顶点时，通过self.scene().mainwindow.actiondelete.setEnable(True)来开放删除按钮。
https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/polygon.py#L34
2. 这部分代码中，需要对输入的GraphItem进行处理，判断是多边形还是顶点，然后分别执行不同的删除操作
https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/canvas.py#L224

在选取顶点后，vertex类包含了当前的polygon，以及在polygon中顶点的序号index。
可以通过index删除polygon中的points中对应的点，并通过polygon.redraw()函数重新绘制多边形。
vertex点的删除，可以通过scene.removeitem(vertex)来删除。
需要注意的是，在删除后，points中记录的点已经被删除，需要手动更新当前polygon中其他vertex对应的index。

**这个功能添加起来比较简单，但近期没时间更新，你可以手动修改下代码**

二. 这个功能不太好做，但软件应该可以满足你的需求。

我理解的你的需求应该是这样的，比如标注一个'人'，你的需求是需要标注胳膊、头、腿、身体等各个部分。

如果我的理解没有问题的话，你可以直接标注部分即可。 假如你点击头部，SAM自动分割了整个'人'，你可以通过右键点击'身体'部位，将这部分设置为不感兴趣区域，从而引导SAM分割到你想要分割的部分。

**左键点击为感兴趣区域；右键点击为不感兴趣区域；可以通过多次点击，更新SAM分割的mask，从而得到你想要的任何分割结果。**

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-HE9A71](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/8d94c524-13f1-453a-9ee3-ae89149ef70a)
![gnome-shell-screenshot-DFQC71](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/5af44902-12b2-45d5-bb73-c4959d018429)

**Comment by August9708** [comment]
我想分割的图像内部更复杂些，边界没那么清除，还有一些干扰性的东西，内部分割恐怕只能手动分，所以才有第二个需求。顺便想请教下，is crowded（拥挤）这个选项有什么用？
