### ISSUE TITLE
大佬可以增加一个SAM的Segment everything的模式吗？

### ISSUE THREAD

**Issue by Rainlt** [yatengLG/ISAT_with_segment_anything#46]
就是SAM的Demo里面的那个一次性把图中所有目标分割出来的功能，分配一个相同的id。这样可以适用于图片上有大量同类目标的情况，不用再一个一个地去点了，只需要手工修正一下结果就好

**Comment by yatengLG** [comment]
这样做的话，会出现很多你不需要的多边形，然后你还得仔细筛选，工作量也很大的

**Comment by yatengLG** [comment]
如果你实在有这个功能的需求，可以自行改一下
主要涉及以下几个地方：

1. 这个是调用SAM的接口，返回的是masks(多个mask组成的列表)
https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/segment_any/segment_any.py#L35

这部分你需要修改的是将点提示的方式，改成全图分割的模式。返回依旧是masks即可。


2. 这部分是点击标注完成后，选择类别的代码。
https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/canvas.py#L150

这部分你需要修改的逻辑是，将所有masks转为polygons，并赋予一个特定的类别，依次添加到目标列表中。L201的代码不在需要。

赋予类别等操作的代码可参考
https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/category_choice_dialog.py#L81

**Comment by Rainlt** [comment]
> 如果你实在有这个功能的需求，可以自行改一下 主要涉及以下几个地方：
> 
> 1. 这个是调用SAM的接口，返回的是masks(多个mask组成的列表)
>    https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/segment_any/segment_any.py#L35
> 
> 这部分你需要修改的是将点提示的方式，改成全图分割的模式。返回依旧是masks即可。
> 
> 2. 这部分是点击标注完成后，选择类别的代码。
>    https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/canvas.py#L150
> 
> 这部分你需要修改的逻辑是，将所有masks转为polygons，并赋予一个特定的类别，依次添加到目标列表中。L201的代码不在需要。
> 
> 赋予类别等操作的代码可参考
> 
> https://github.com/yatengLG/ISAT_with_segment_anything/blob/e38ffcfb63a7b4add342af919a2b2a29641529d4/widgets/category_choice_dialog.py#L81

了解了，多谢大佬！
