### ISSUE TITLE
交互建议

### ISSUE THREAD

**Issue by zyyyz** [yatengLG/ISAT_with_segment_anything#47]
作者你好，非常高兴看到有这么好的开源工具，感谢你的辛勤付出。这样的工具极大地减轻了标注的工程量，是我目前见到的最好用的分割标注工具了。但我还是有几点建议想反馈给您，希望能进一步完善：
1. 在对不同的类别进行标注时，每标注完一个块就需要手动选择标签这样比较麻烦，不够优雅。因为通常逻辑是持续的标注完某个特定类，再标注新的类。因此，可以考虑在标注某类时，预先选定好类别，后面与之同类的标注mask就不用每次再手动选择标签了。
2. 在按下鼠标左键自动出现mask后，会显示一些不连通的区域。通常这些分离区域都属于同一类，但是在选择了标签后却不能把所有的不连通块作为一类处理，往往只有某一个块被识别生成了掩码，别的同类的块被抛弃了。
3. 可否考虑利用SAM增加一个一键分割功能，用户再在此基础上做细微的修改即可。

好人一生平安，respect!

**Comment by yatengLG** [comment]
1. 这个需求的话，好多人都在提，后续我会出一个专门的版本，现在这个框架改动太大了。
2. 对于连通区域的处理，是为了后续多边形二次修改做出的妥协。对于不连通区域会出现多个多边形，还会出现多边形包含的情况，处理逻辑会比较繁杂。并且在当前框架下，一次只能处理一个多边形（主要ISAT先标注多边形，后选择类别，后续改成1中提到的逻辑就不会有这个影响了。） 所以对于多个不连通区域，为保证转换后多边形的唯一性，只保留了最大的部分。
3. SAM的一键分割功能，会与1中提到的版本一起添加。

感谢支持。

**Comment by zyyyz** [comment]
感谢你的回复呀，我最早也想做这样一个工具，但考虑到工程量有点大，遂放弃。我现在时间较为充分，不知道有没有兴趣我们一块来做这个东西，我纯粹用爱发电，想更加完善这个项目，同时也能一起学习。我的邮箱是zyy202314@outlook.com

**Comment by yatengLG** [comment]
等后续我新建一个分支吧，现版本就先不动了，改动太大。
到时候你可以在新分支上进行提交。

预计的新分支计划，整理工作流程不变，但是与现版本在操作逻辑上存在区别：
1. 左侧增加类别栏，工具栏新增标注按钮。选择类别（这个为单次），点击标注按钮直接开始标注（为了区分不同工作状态，因为同时存在拖动图片功能，所以不能点击直接开始标注），标注完成按钮不再弹窗进行标注选择，而是使用已选择的类别。
2. 多mask的处理：（1）对于不连通mask，转换为多个多边形，并赋予当前所选类别；（2）对于内包含的mask，转换多边形时，区分包含关系，外廓多边形赋予当前所选类别，内含多边形赋予背景类。
3. 新增SAM全图分割功能，所有mask默认为当前所选类别（这个功能实际上并不好用，因为全图分割会存在很多包含关系，手动处理也会非常麻烦）。

**Comment by yatengLG** [comment]
新版本已经提交了，在develop分支中。目前功能基本完成，但还不完善，翻译、文档等还没跟上。

**Comment by yatengLG** [comment]
第1,2点，在最新的版本中，已经全部实现了；第3点不具备实用性，已经放弃。

非常感谢你的建议！

如果你想为本项目贡献代码，可以fork一份，在自己分支上修改完以后，提交PR。我这里能收到你代码的。

**Comment by liuqinglong110** [comment]
作者你好，这个软件界面标注的多边形可以用鼠标增加或者删除点吗？编辑标注结果的时候很需要这个功能。

**Comment by yatengLG** [comment]
> 

在最新版的代码中，支持了多边形点的删除，但是添加点暂时不支持。工作量比较大，后续有时间可能会添加该功能，谢谢支持。
