### ISSUE TITLE
Unable to open high-resolution images

### ISSUE THREAD

**Issue by Namenameee** [yatengLG/ISAT_with_segment_anything#52]
JPG images with a resolution of 4032*3024 cannot be opened normally

**Comment by Alias-z** [comment]
> JPG images with a resolution of 4032*3024 cannot be opened normally

Maybe check your images? I can open a very large jpg file without any problem.

![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/66273343/6c4284a7-3d70-41f4-9a7d-a1040ca1ca15)

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-SFAH81](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/d1524862-6ddb-44e5-8a78-bf6a95e6bcf5)
我这边也没有问题。

**你可以试着拉取最新的版本，试一下。**

**Comment by Namenameee** [comment]
Thank u very much. I'll try it later.
