### ISSUE TITLE
可以支持矩形框选择吗？

### ISSUE THREAD

**Issue by xiaohuboer** [yatengLG/ISAT_with_segment_anything#54]
很好的工具！！！
提个建议：在使用sam时，一些偏小的图像，使用box框选后，自动选择的多边形会更准确一些。可以支持Box吗？
谢谢

**Comment by yatengLG** [comment]
我这边测试了多边形框选，没有任何提升。

SAM在进行特征提取时，先把图resize到1000*1000了，对大图进行裁剪后在输入SAM，分割效果会好很多；但如果还是直接大图输入，没有人眼可见的差异。


SAM的官方demo网站应该是经过了一些处理。但如果你用的是源码跑的，请联系我。

**Comment by xiaohuboer** [comment]
我做了个取巧，先把图片放大，然后把可视区的像素传给predictor并set_image；这样，小图就变大图了，然后分割；完成后，按照缩放scale，再把选择的区域还原到原始图中。
同时，为了提高效率，当可视区域没有变化时，不重新reset_image。
这是我后面想到的办法，效果很不错，供参考

**Comment by xiaohuboer** [comment]
每次缩放不去计算，是只有发生框选的时候，首先判断，可视区域有没有变化，有变化把可视区域的这部分图像进行重置。使用的GPU，卡顿也就1秒吧；大部分时候选择区域，都不会缩放的。

**Comment by yatengLG** [comment]
好的，谢谢。O(∩_∩)O
