### ISSUE TITLE
关于医学图像的标注 The medical image annotation issue

### ISSUE THREAD

**Issue by TtoastXin** [yatengLG/ISAT_with_segment_anything#57]
我是做医学影像分析方面研究的，希望ISAT_with_segment_anything能够支持对医学图像格式文件（如dicom、nii等）的读取和标注。我自己尝试改了部分代码，目前可以使用软件读取nii文件图像的轴位面，能够用鼠标拖动调整其窗宽窗位，并将图像保存为png格式。然后再按照软件原有的方式对png图像进行读取和标注，请问是否允许让我申请PR来加入这部分代码？目前的运行截图如下所示：

I am doing research in medical image analysis, I am hoping that ISAT_with_segment_anything can support reading and annotating medical image format files (such as dicom, nii, etc.). I tried to change part of the code by myself, and now I can use the software to read the axial plane of the nii file image, and I can use the mouse to drag to adjust the window width and window level, and save the image as png format. Then the png image can be read and labeled according to the original way of the software, is it allowed for me to apply for PR to add this part of the code? The current running screenshot is shown below:

![1](https://github.com/yatengLG/ISAT_with_segment_anything/assets/139123912/1d9b409e-60a8-4976-8d4f-d0036ba57bb1)
![2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/139123912/027b33ec-6606-4ce7-a069-43b65df11c13)

**Comment by yatengLG** [comment]
可以的啊，欢迎提交pr.

**Comment by TtoastXin** [comment]
好的，我随后提交
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月07日 14:26 |
| 收件人 | yatengLG/ISAT_with_segment_anything ***@***.***> |
| 抄送人 | TtoastXin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [yatengLG/ISAT_with_segment_anything] 关于医学图像的标注 The medical image annotation issue (Issue #57) |

可以的啊，欢迎提交pr.
