### ISSUE TITLE
半自动标注选项变成灰色的，选择不了

### ISSUE THREAD

**Issue by FZUChenhaoLin** [yatengLG/ISAT_with_segment_anything#58]
/

**Comment by yatengLG** [comment]
没有下载预训练模型，或者没有选择需要使用的模型。

新版本中，可以在菜单栏 SAM下 选择需要使用的模型，也可以随时切换要使用的模型。

SAM菜单下会列出/segment_any文件夹下的已存在的模型。

**Comment by FZUChenhaoLin** [comment]
> 

预训练模型下载了，我发现是不能标注32位深的图。

**Comment by yatengLG** [comment]
之前没有涉及到，后续添加对这个的支持吧。

**Comment by yatengLG** [comment]
sam只支持三通道的图进行分类，32位深的图带了alpha透明度是四通道图，所以不能直接进行标注。

本软件在标注时，为了保证图片的原始性，只读取图片，不会对图片进行处理，建议转换后再进行标注。
