### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by DrewdropLife** [yatengLG/ISAT_with_segment_anything#59]
首先这是一个很棒的工作，能够大大降低标注的工作量，但是实际标注下来遇到一些问题：
1、用sam标注mask后，存在很多点需要调整，一方面这些点似乎没法删除，只能一个一个拖动位置，另一方面在调整点的过程中，很容易误触到mask并拖动了它的位置，这会导致使用体验较差。
2、希望可以支持矩形框标注，这样能够拓宽该工具的适用性，能够用于标注检测任务。
也即，希望能够：
1、在标注完成后，点击某个多边形点可以进行删除操作，删除后自动连接断开的首尾点。
2、禁止mask被拖动
3、增加矩形框标注
谢谢。

**Comment by yatengLG** [comment]
感谢您的建议。

1. 多边形顶点的删除功能已经添加
2. 多边形拖动还是需要保留的，为了减少误拖动，会增大顶点大小，使顶点更易被选中。 在菜单栏中新添加一个条，用于调整顶点大小。
3. 矩形框不准备添加，通过mask可以很方便的计算出外接矩形。

**Comment by DrewdropLife** [comment]
> 感谢您的建议。
> 
> 1. 多边形顶点的删除功能已经添加
> 2. 多边形拖动还是需要保留的，为了减少误拖动，会增大顶点大小，使顶点更易被选中。 在菜单栏中新添加一个条，用于调整顶点大小。
> 3. 矩形框不准备添加，通过mask可以很方便的计算出外接矩形。

感谢你的回复以及添加的功能！现在的使用体验确实好了很多~~O(∩_∩)O~~
