### ISSUE TITLE
无法生成标签

### ISSUE THREAD

**Issue by kaka-ice** [yatengLG/ISAT_with_segment_anything#6]
标注之后在图片路径下无法生成标签，后台会报'NoneType' object has no attribute 'shape'错误，想知道怎么解决该问题，谢谢up主，已三联支持。

**Comment by yatengLG** [comment]
项目自带的example/images下面的图片也不行嘛？

**Comment by kaka-ice** [comment]
我发现了是因为图片路径有中文，cv2.imread无法读取含有中文路径的图片，我尝试了两种方法解决：1.路径全部设置为英文 2.将widgets/annotation.py下Line 31的cv2.imread()替换成cv2.imdecode()了。非常感谢大佬回复。
