### ISSUE TITLE
I downloaded and used the latest code, but when loading sam hq and mobile sam, it crashed

### ISSUE THREAD

**Issue by LS-YQ** [yatengLG/ISAT_with_segment_anything#61]
I downloaded and used the latest code, but when loading sam hq and mobile sam, it crashed

**Comment by yatengLG** [comment]
SAM model can be used?

**Comment by LS-YQ** [comment]
Only SAM can be used

**Comment by yatengLG** [comment]
![gnome-shell-screenshot-OG9B91](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/9992bec8-a2bd-4d10-b3fd-b44998179868)

1. Make sure your project is newest and contain these file.
2. Check Python packages, is the package 'timm' installed. Mobile-sam and sam-hq-tiny need 'timm' support.

**Comment by LS-YQ** [comment]
Thank you!
