### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by gtoo8888** [yatengLG/ISAT_with_segment_anything#63]
十分感谢作者的持续更新，新出的"保存所有轮廓"十分的好用，我的标注更加快捷了

最近我和我的同学都在使用这个进行标注，遇到了一些使用上的问题和bug想请作者请教一下

1. self.mask_aplha.setValue(mask_alpha*10)处我启动的话会报错，我需要修改为
    self.mask_aplha.setValue(int(mask_alpha*10))才可以使用，不知道是不是我这边的问题，我已经提交了一个pr
2. 没有模型的提示感觉不友好，在第一次启动的时候，如果没有模型，会弹出一大堆的错误，我不知道是代码出现了什么问题，后来才发现是模型没有添加，不知道能不能修复一下。同时我这边测试了下，第一次启动之后，我将模型移除，就不会出现那一大堆的报错，整个程序可以正常运行，就是SAM选项卡下面没有内容，应该是正常的现象。
RuntimeError: wrapped C/C++ object of type FROMCOCO has been deleted
3. 我这边使用pip install -r requirements.txt这个安装环境，但是安装的总是有很大的问题，主要的问题出在安装pycocotools上，我这边是使用anaconda来配置环境的，pip install和conda list都无法安装pycocotools,只有使用conda install -c conda-forge pycocotools才可以成功

## bug
请作者验证下是否是bug
1. 关于"保存所有轮廓"的一个bug，
   1. 选项卡中没有__background__，我尝试将这个替换为了background
   2. 使用"保存所有轮廓"进行标注->点击segment anything->调整好自己想要标注的区域，中间有镂空部分->点击"完成"
   3. 程序页面直接卡死，没有报错提示，也无法关闭，需要在pycharm中强行终止程序
   4. 将标签改回__background__就可以正常标注
2. 一个图像切换的bug
   1. 对当前图像完成所有标注，都使用"完成"将需要的标注框固定了下来，并且没有按下过"保存"按钮
   2. 鼠标点击右下方框中的任意除了自己以外的其他图片
   3. 主界面会切换到下一张图片，并且不会提示是否需要保存
   4. 重新切换回当前的图片，会发现所有标注的内容都消失了
   5. 不知道这个是bug还是特地设计的特性？因为现在没有一键删除所有标注框的功能，如果当前图片全部标注完，但是觉得标注的不好，想要重新标注，可以使用这种切换的方法
3. 标签选择的bug
   1. 不知道启动时，对左边标签选择的情况是怎么样的，有时候默认勾选了一个，有时候什么都没有勾选
   2. 启动时候什么都没有勾选的情况会出现bug
   3. 启动软件->(左边标签为空白，什么都没有勾选)->加载模型->点击segment anything->调整好自己想要标注的区域->->点击"完成"
   4. 程序页面直接卡死，没有报错提示，也无法关闭，需要在pycharm中强行终止程序
   5. 这里是否需要一个更好一点的交互？比如开启的时候强制勾选一个标签，防止报错退出，或者弹出提示，还没有勾选标签
   6. 我不太清楚标签的勾选机制，可能我这个测试是在刚刚卡死退出的情况下进行的，希望作者可以继续测试一下

## 性能优化相关
我的配置是:
GPU: NVIDIA GeForce RTX 3060
CPU: AMD Ryzen 9 5900X(12核心、24线程)
内存: 32G
硬盘: 西部数据SN770

1. 图像切换在加载模型以后比较卡顿
   1. 启动软件->选择图像文件夹(没有标注的文件)->使用AD键前后翻动图像->十分流畅
   2. 启动软件->选择图像文件夹(标注的内容比较多)->使用AD键前后翻动图像->有一些卡顿（需要读取较多的节点信息，有一些卡顿？）
   3. 启动软件->选择图像文件夹(没有标注的文件)->加载了sam_vit_h_4b8939.pth模型->使用AD键前后翻动图像->有一些卡顿
   4. 启动软件->选择图像文件夹(标注的内容比较多)->加载了sam_vit_h_4b8939.pth模型->使用AD键前后翻动图像->十分卡顿
   5. 启动软件->选择图像文件夹(标注的内容比较多)->加载了sam_vit_b_01ec64.pth模型->使用AD键前后翻动图像->比h模型卡顿好一些
   6. 流畅程度排序，最左边为最流畅
      1. 1>2>5>3>4
   7. 不知道这其中是否有性能优化的空间，还是是由于我电脑的性能决定的
   8. 我觉得在加载标注文件的内容中，应该是这个仓库可以控制的
2. 使用工具->To VOC
   1. 我标注的数据中，有的标注量多，有的标注量少
   2. 可以看到标注越多的数据，转化的越慢，应该是需要识别每个节点，并且转化
   3. 我没有定量统计，我现在是有500张标注量比较大的图片，转化的速度十分的缓慢
   4. 不知道在这个部分是否有提升的空间
3. 是否可以增加一个一键删除所有标注框的操作
   1. 有时候由于识别的问题，识别之后，直接按完成，会有很多分散的小矩形块，所以图片需要重新标注
   2. 现在的方法是需要点击右侧的标签栏，需要对所有的标签一个一个删除
   3. 不知道能否出一个一键删除所有标注框的功能
4. 是否可以调整图层的值
   1. 我标注的图像有前后重叠的关系，现在在标注完成后，双击右侧标签栏中的标注的内容
   2. 可以看到可以修改类别和组，可以添加注释，但是无法修改图层
  

最后再次感谢作者的不断更新，这个仓库对我起到了极大的帮助，关于性能优化问题，只是想提出一些建议，不知道能不能有机会改进。

**Comment by yatengLG** [comment]
不好意思，最近在忙其他事情。

问题回复：
1. 对于问题1，问题2，你可以试着拉取最新版本试一下，我这边在linux以及windows下都没有出现过这个问题。
2.问题3的确是存在的，pycocotools安装的确存在很大问题。

bug回复：
1. 在最新的代码中，没有出现这个问题
2. 这个的确是个bug，T.T
3. 最新的代码中，默认勾选__background__

优化方面回复：
1. 卡顿现象是存在的，软件在设计的时候，在图像加载时运行sam运算，这样可以减少标注过程中的延迟。使用越大的模型，所需的计算量越大，卡顿感越强。
2. 这个工具是个单线程的，后期可以试一下多线程，应该可以有效提升转换速度。
3. 一键删除可以添加，但是近期没有时间更新
4. 这个可以实现，但是比较麻烦，一般情况下应该也不会涉及到多个图层叠加的情况。


欢迎提出问题与建议，后续我会抽空进行更新的。可以随时关注最新版本的代码。

**Comment by gtoo8888** [comment]
我重新拉取了代码，还是存在第一次启动时报错的问题
self.mask_aplha.setValue(int(mask_alpha10))这个问题在代码合并后应该解决了

**Comment by yatengLG** [comment]
> 我重新拉取了代码，现在可以正常启动了

更新了独立显存计算encoder，现在完全没有卡顿感了
