### ISSUE TITLE
照片切换

### ISSUE THREAD

**Issue by Shuimojiangshan** [yatengLG/ISAT_with_segment_anything#65]
请问如何调参可以让照片切换更顺畅，现在换一种照片就要等好久~

**Comment by yatengLG** [comment]
1. 换小模型
2. 换算力更大的显卡

切换图片时的卡顿是由于SAM计算带来，无法避免，使用小模型降低算力需求，或者换大显卡增加算力都可以缓解这个问题。

**Comment by Shuimojiangshan** [comment]
感谢！

**Comment by komoreda** [comment]
@yatengLG 您好，请问是否可以提前用SAM-huge推理所有图片，保存为特征，然后标注时直接读取特征和图片，这样是否可以实现顺畅切换图片？

**Comment by yatengLG** [comment]
> @yatengLG 您好，请问是否可以提前用SAM-huge推理所有图片，保存为特征，然后标注时直接读取特征和图片，这样是否可以实现顺畅切换图片？

是可以的

**Comment by komoreda** [comment]
> > @yatengLG 您好，请问是否可以提前用SAM-huge推理所有图片，保存为特征，然后标注时直接读取特征和图片，这样是否可以实现顺畅切换图片？
> 
> 是可以的

请问，最近是否考虑增加这种功能，这种标注方式应该会大大缩短标注时间，貌似其它标注工具也没有相关实现

**Comment by yatengLG** [comment]
> > > @yatengLG 您好，请问是否可以提前用SAM-huge推理所有图片，保存为特征，然后标注时直接读取特征和图片，这样是否可以实现顺畅切换图片？
> > 
> > 
> > 是可以的
> 
> 请问，最近是否考虑增加这种功能，这种标注方式应该会大大缩短标注时间，貌似其它标注工具也没有相关实现

近期没有增加该功能的计划。

**如果这个项目给您的工作生活带来了便捷，请给一个Star，谢谢**
