### ISSUE TITLE
优化group标注逻辑

### ISSUE THREAD

**Issue by Alias-z** [yatengLG/ISAT_with_segment_anything#66]
增加 手动/自动 选择group 功能。 标注同组多目标时group id可以不变。

假设我们需要标注一杯饮料和上面的西瓜， 饮料和西瓜应该为同一组。 示例图上有两杯饮料，第一杯上有2片西瓜；第二杯上有一片西瓜。

目前的标注逻辑是自动group+1，这样会导致标注不方便。结果为5个groups每个饮料/西瓜自个为一个组。

示例：

![auto (1)](https://github.com/yatengLG/ISAT_with_segment_anything/assets/66273343/684238c8-550d-455d-aada-8b807204ad82)

新增 手动选组按钮，模式为‘manual’时group id不变。这样可以用group id=1标注第一杯饮料和上面的西瓜。要进行下一组时可以快捷点击‘+’按钮，再用group id=2标注第二组的物体。结果为第一杯饮料和上面的西瓜group id都为1， 第二组的都为2。

示例：
![manual (1)](https://github.com/yatengLG/ISAT_with_segment_anything/assets/66273343/bd96f8c9-a600-4042-8285-6eceedb8818d)

同时，增加了‘Z’和‘X’快捷键快速查看上一组和下一组的的标注。

如有需要我可以提PR

**Comment by yatengLG** [comment]
我是不是可以这么理解这个例子，在饮料瓶上，有西瓜图案。

标注的时候，需要把类别 杯子+西瓜全部标注了，但是在实例方面，又需要按照杯子标group？

但一般情况下，如果只需要标注杯子的话，那以杯子为组即可，这个需求一般是没有异议的；如果杯子和西瓜图案都需要标注类别，但实例只需要标注杯子的话，这种需求会比较少见，除非这是两个任务。

**Comment by Alias-z** [comment]
> 我是不是可以这么理解这个例子，在饮料瓶上，有西瓜图案。
> 
> 标注的时候，需要把类别 杯子+西瓜全部标注了，但是在实例方面，又需要按照杯子标group？
> 
> 但一般情况下，如果只需要标注杯子的话，那以杯子为组即可，这个需求一般是没有异议的；如果杯子和西瓜图案都需要标注类别，但实例只需要标注杯子的话，这种需求会比较少见，除非这是两个任务。


是的，这种一般用于多任务标注。列如任务需要先找到目标再分割每个目标上的东西。这个在目前的工具里实现其实很方便，因为可以转换实列的位图，也可以做转换语义分割的位图。这类需求的代码我也经写好并测试了很久了。你觉得有需要的话我可以合并过来。

**Comment by yatengLG** [comment]
可以的，提交个PR吧，只是我最近有点忙，可能得拖一段时间再合并。

**Comment by Alias-z** [comment]
> 可以的，提交个PR吧，只是我最近有点忙，可能得拖一段时间再合并。

提交了。其实还有个好处是，需要反复修改一个标注的时候。比如用sam-hq标好的不满意，需要删掉重新表。用手动模式可以固定住组，这样就不要特意去修改组别了。

**Comment by yatengLG** [comment]
已合并，非常感谢一直以来的支持O(∩_∩)O

**Comment by StanleyYake** [comment]
> > 我是不是可以这么理解这个例子，在饮料瓶上，有西瓜图案。
> > 标注的时候，需要把类别 杯子+西瓜全部标注了，但是在实例方面，又需要按照杯子标group？
> > 但一般情况下，如果只需要标注杯子的话，那以杯子为组即可，这个需求一般是没有异议的；如果杯子和西瓜图案都需要标注类别，但实例只需要标注杯子的话，这种需求会比较少见，除非这是两个任务。
> 
> 是的，这种一般用于多任务标注。列如任务需要先找到目标再分割每个目标上的东西。这个在目前的工具里实现其实很方便，因为可以转换实列的位图，也可以做转换语义分割的位图。这类需求的代码我也经写好并测试了很久了。你觉得有需要的话我可以合并过来。

@Alias-z 您好，我也很好奇您提到的这个多任务的标注，例子中先西瓜饮料这个大类，再去分割西瓜和杯子。需要先找到目标再分割每个目标上的东西，有点类似组件的感觉，西瓜和杯子组成西瓜饮料。这样的任务用Maskrcnn可以直接做吗，是标注好了就可以直接喂去训练？

**Comment by Alias-z** [comment]
> > > 我是不是可以这么理解这个例子，在饮料瓶上，有西瓜图案。
> > > 标注的时候，需要把类别 杯子+西瓜全部标注了，但是在实例方面，又需要按照杯子标group？
> > > 但一般情况下，如果只需要标注杯子的话，那以杯子为组即可，这个需求一般是没有异议的；如果杯子和西瓜图案都需要标注类别，但实例只需要标注杯子的话，这种需求会比较少见，除非这是两个任务。
> > 
> > 
> > 是的，这种一般用于多任务标注。列如任务需要先找到目标再分割每个目标上的东西。这个在目前的工具里实现其实很方便，因为可以转换实列的位图，也可以做转换语义分割的位图。这类需求的代码我也经写好并测试了很久了。你觉得有需要的话我可以合并过来。
> 
> @Alias-z 您好，我也很好奇您提到的这个多任务的标注，例子中先检测西瓜饮料这个大类，再去分割西瓜和杯子。需要先找到目标再分割每个目标上的东西，有点类似组件的感觉，西瓜和杯子组成西瓜饮料。这样的任务用Maskrcnn可以直接做吗，是标注好了就可以直接喂去训练？

直接做是可以的，通过后处理也能得到各个组件的掩码。但是我用transformer类的模型如果直接多标签做实力分割显存吃不消，所以才先目标检测，再切到bbox里分别语义分割。
