### ISSUE TITLE
标签格式问题

### ISSUE THREAD

**Issue by d710055071** [yatengLG/ISAT_with_segment_anything#7]
请问这个工具生成的标签是通用的格式吗？例如coco等的通用格式？

**Comment by yatengLG** [comment]
如果是说标注完形成的json文件的话，不通用。ISAT里面为了处理遮挡问题，给每个目标都添加了图层信息。

但是，如果你想转coco的json，其实特别简单。解析json再保存就好了。

（不过，你这个问题最近很多人都在问，我也在考虑要不要替换ISAT最终的json格式 或是添加一个转换工具。）

**Comment by kime541200** [comment]
这是个非常棒的项目, 想要给一点小建议
1. 可输出COCO格式
2. 切换到下一张图片时自动保存当前标注的结果

最后还是要再次感谢大大的贡献!

**Comment by yatengLG** [comment]
@kime541200 已经在做了ʕ̯•͡˔•̯᷅ʔ

**Comment by mushroom-x** [comment]
作者使用的实例分割标注格式是自己定义的ISAT格式， 而使用YoloV8实例分割则需要转换为Yolo格式。 如果使用MaskRCNN则需要转换为COCO格式。 我写了将ISAT格式转换为Yolo与COCO格式的Python转换脚本 
https://github.com/mushroom-x/SegConvert
