### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.  Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

### ISSUE THREAD

**Issue by mazhendi** [yatengLG/ISAT_with_segment_anything#72]
这是什么问题，我用的windows，搭载的租的服务器

**Comment by mazhendi** [comment]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

**Comment by yatengLG** [comment]
qt的问题，你这服务器不是桌面版吧

**Comment by mazhendi** [comment]
就是那种远程服务器，远程算力平台（AUtoDL）



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月8日(星期五) 上午9:18
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yatengLG/ISAT_with_segment_anything] qt.qpa.plugin: Could not load the Qt platform plugin &quot;xcb&quot; in &quot;&quot; even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.  Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb. (Issue #72)





 
qt的问题，你这服务器不是桌面版吧

**Comment by yatengLG** [comment]
这种服务器基本都是命令行版本的，ssh直接连命令行就可以。

但这个标注软件有界面，依赖QT，你服务器没有QT。

**Comment by mazhendi** [comment]
怎么办呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月8日(星期五) 上午9:56
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yatengLG/ISAT_with_segment_anything] qt.qpa.plugin: Could not load the Qt platform plugin &quot;xcb&quot; in &quot;&quot; even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.  Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb. (Issue #72)





 
这种服务器基本都是命令行版本的，ssh直接连命令行就可以。
 
但这个标注软件有界面，依赖QT，你服务器没有QT。

**Comment by yatengLG** [comment]
现在的话，只支持部署到单机上。
