### ISSUE TITLE
导入模型后发现无法使用

### ISSUE THREAD

**Issue by esonst** [yatengLG/ISAT_with_segment_anything#73]
环境： win11

导入模型后提升错误
- sam hq!
<All keys matched successfully>
'gbk' codec can't decode byte 0xad in position 1879: illegal multibyte sequence

**Comment by yatengLG** [comment]
编码问题，你试一下全英文路径

**Comment by lgf821793883** [comment]
linux无法使用sam模式

**Comment by yatengLG** [comment]
> linux无法使用sam模式

请详细描述你的问题

**Comment by yatengLG** [comment]
> 环境： win11
> 
> 导入模型后提升错误
> 
> * sam hq!
> 
> 'gbk' codec can't decode byte 0xad in position 1879: illegal multibyte sequence

编码问题解决了嘛？

**Comment by lgf821793883** [comment]
只能使用多边形的，Q键 segment anything 无法使用

**Comment by yatengLG** [comment]
> 只能使用多边形的，Q键 segment anything 无法使用

没下载sam模型

https://github.com/yatengLG/ISAT_with_segment_anything#3-%E4%B8%8B%E8%BD%BDsegment-anything%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B
