### ISSUE TITLE
导入模型后出现segment anything dont support the image shape

### ISSUE THREAD

**Issue by whisky997** [yatengLG/ISAT_with_segment_anything#74]
请问出现这种情况，图片的要求是什么呢

**Comment by yatengLG** [comment]
虽然你没输入全，但是应该是因为图片是4通道。转换为三通道就可以了。

sam只支持三通道图片，软件想保留原始图片信息，所以不对输入图片进行处理。


如果本软件给你的工作生活带来了方便，请给个star哦！！！
