### ISSUE TITLE
关于windows下的使用，如何才能支持cpu

### ISSUE THREAD

**Issue by hupu1dong** [yatengLG/ISAT_with_segment_anything#75]
你好，作者，感谢你的开源工作，我想咨询一下，关于windows下的使用，如何才能支持cpu，我验证了一些，如果我的windows电脑，没有英伟达的独显，打开main.exe 点击加载sam模型，就会闪退

**Comment by hupu1dong** [comment]
建议torch 的device 做成可配置的选项，这确实是一个刚需点

**Comment by yatengLG** [comment]
应该不是软件的问题，你试着换个模型试一下。

比如sam-hq-tiny，这个问题之前有人反馈过，可能是mobile-sam保存的模型为gpu的。

**Comment by yatengLG** [comment]
另外，cpu的话不建议用较大的模型，算的会比较慢，切换图片时卡顿感特别明显。

**Comment by yatengLG** [comment]
> 建议torch 的device 做成可配置的选项，这确实是一个刚需点

这个以及是自适应的。如果torch能调用gpu就会调用，如果不能调用就会用cpu。

打包的exe，只包含了mobile-sam，只是为了方便下载后可以直接体验。  问题应该就是出在了mobile-sam模型保存的权重上。

**Comment by hupu1dong** [comment]
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/58175002/3c27fece-2dbb-4405-85d9-238bf718bdc5)

**Comment by hupu1dong** [comment]
我下载的windows 包，里面是sam-hq-tiny 这个权重

**Comment by yatengLG** [comment]
那你换个权重，可能是我记错了 T.T

**Comment by hupu1dong** [comment]
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/58175002/14ec90e9-c9f5-4d5e-93df-75fa67345fdb)

**Comment by yatengLG** [comment]
![webwxgetmsgimg (4)](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/9aedc569-0b71-4d6b-a68f-ce05c3771cad)

**Comment by hupu1dong** [comment]
确实是权重问题，换了mobile-sam，就可以了

**Comment by hupu1dong** [comment]
谢谢作者，爱你哦

**Comment by yatengLG** [comment]
> 谢谢作者，爱你哦

谢谢支持，爱你哟

如果好用的话，git给个star哦O(∩_∩)O
欢迎多提建议

**Comment by hupu1dong** [comment]
早就start，干就完了，老铁666，没毛病！！！
