### ISSUE TITLE
服务器不支持图形化界面该怎么办？

### ISSUE THREAD

**Issue by jingzhengli** [yatengLG/ISAT_with_segment_anything#76]
作者您好，我的远程服务器不支持图像化界面，所以会出现如下报错：我的本地机器上没有足够的内存，所以这个图形化界面可以显示在本地机器上么？

_qt.qpa.xcb: could not connect to display localhost:57.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem._

**Comment by yatengLG** [comment]
暂时只支持本机部署

**Comment by jingzhengli** [comment]
虽然可以在本地上显示图形化界面，但是Images dir和Label dir这些按钮好像不能使用，所以还是不能用。


| |
BUAA_ljz
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月28日 20:33 |
| 收件人 | ***@***.***> |
| 抄送人 | Jingzheng ***@***.***> ,
***@***.***> |
| 主题 | Re: [yatengLG/ISAT_with_segment_anything] 服务器不支持图形化界面该怎么办？ (Issue #76) |

暂时只支持本机部署

**Comment by yatengLG** [comment]
你看下这个衍生项目，是不是可以满足你的需求
https://github.com/LSH9832/SAMLabelerPro

**Comment by jingzhengli** [comment]
你的项目我已经可以用了（在本地打开远程服务器上的图形化界面），非常感谢。这个衍生的项目也很不错。


| |
BUAA_ljz
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月28日 20:47 |
| 收件人 | ***@***.***> |
| 抄送人 | Jingzheng ***@***.***> ,
***@***.***> |
| 主题 | Re: [yatengLG/ISAT_with_segment_anything] 服务器不支持图形化界面该怎么办？ (Issue #76) |

你看下这个衍生项目，是不是可以满足你的需求
https://github.com/LSH9832/SAMLabelerPro

**Comment by wolfworld6** [comment]
> export

export 本地 ip是什么意思？
