### ISSUE TITLE
快捷键冲突问题

### ISSUE THREAD

**Issue by NBao01** [yatengLG/ISAT_with_segment_anything#78]
当前最新版本存在快捷键冲突问题，具体是Backspace回退的快捷键Z，与切换分组的快捷键Z/X冲突，导致回退功能无法正常使用，此时命令行中报错信息为：`QAction::event: Ambiguous shortcut overload: Z`。

**Comment by yatengLG** [comment]
已解决（删除了手动加减组id的快捷绑定）。多谢反馈

**Comment by Alias-z** [comment]
> 已解决（删除了手动加减组id的快捷绑定）。多谢反馈

切换分组的功能还是很重要的，所以当时才加入的。要不重新布置一下键位？
