### ISSUE TITLE
无法使用自动标注

### ISSUE THREAD

**Issue by Shuimojiangshan** [yatengLG/ISAT_with_segment_anything#79]
您好 请问选择了sam后无法使用自动标注该如何解决呢？

**Comment by yatengLG** [comment]
请描述下具体情况

**Comment by Shuimojiangshan** [comment]
选择权重文件之后 seganything那个键（类似∞）是黑色的 不是彩色的 点击了没有反应



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月10日(周二) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79)




 
请描述下具体情况

**Comment by yatengLG** [comment]
1. 下载的exe
如果是cpu环境，下载  mobile-sam的权重试一下，sam-hq-tiny的权重网友反应不支持cpu
如果是gpu环境，先查看下显卡驱动，然后测试下torch是否可以调用

2. 下载的源码
把加载模型后的输出，反馈下

**Comment by yatengLG** [comment]
你不是很早之前就开始用了嘛？一直有问题？

**Comment by Shuimojiangshan** [comment]
之前一直没有问题的 现在隔了一个月了 突然一用发现用不了了😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月10日(周二) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79)




 
你不是很早之前就开始用了嘛？一直有问题？

**Comment by Shuimojiangshan** [comment]
您好 我重新下载了源码 安装的环境是gpu的 运行后自动标注还是没法使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月10日(周二) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79)




 
你不是很早之前就开始用了嘛？一直有问题？

**Comment by yatengLG** [comment]
> 您好 我重新下载了源码 安装的环境是gpu的 运行后自动标注还是没法使用
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月10日(周二) 下午5:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79) 你不是很早之前就开始用了嘛？一直有问题？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你是不是用了虚拟环境，但是这次没切换啊。

**Comment by Shuimojiangshan** [comment]
您好我是使用了虚拟环境，但是我已经切换了😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 上午8:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79)




  
您好 我重新下载了源码 安装的环境是gpu的 运行后自动标注还是没法使用
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年10月10日(周二) 下午5:53 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79) 你不是很早之前就开始用了嘛？一直有问题？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你是不是用了虚拟环境，但是这次没切换啊。

**Comment by yatengLG** [comment]
代码没问题，主要你一开始也没动代码啊😭。应该就是环境问题，或者你看看咋个报错？试一下单sam能不能跑

**Comment by Shuimojiangshan** [comment]
您好😭我这里直接运行main.py没有报错 就是没法自动标注 还有请问单sam是什么意思呢 非常感谢回答😭



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yatengLG/ISAT_with_segment_anything] 无法使用自动标注 (Issue #79)




 
代码没问题，主要你一开始也没动代码啊😭。应该就是环境问题，或者你看看咋个报错？试一下单sam能不能跑

**Comment by yatengLG** [comment]
你现在用的哪个模型啊，你试一下mobile-sam看能不能用
