### ISSUE TITLE
不使用终端命令，直接点击main.py运行时候报错

### ISSUE THREAD

**Issue by w-arrior** [yatengLG/ISAT_with_segment_anything#8]
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

**Comment by w-arrior** [comment]
就是用pytharm的ssh连接了服务器，在服务器的那个pycharm里面点击main.py就会出现以上错误，后来测试在服务器上直接运行就可以正常显示了

**Comment by canhe173** [comment]
> 就是用pytharm的ssh连接了服务器，在服务器的那个pycharm里面点击main.py就会出现以上错误，后来测试在服务器上直接运行就可以正常显示了

我想问一下，你这个在服务器上直接运行是指在服务器上连显示器和键盘运行吗？
