### ISSUE TITLE
sam_hq_vit_tiny.pth模型无法切换

### ISSUE THREAD

**Issue by 8410ttt** [yatengLG/ISAT_with_segment_anything#81]
我是下载的程序进行运行，当切换sam_hq_vit_tiny.pth模型时，直接退出程序，报错
- sam hq!

进程已结束,退出代码-1073740791 (0xC0000409)
我的电脑是RTX3050 4G显存

**Comment by yatengLG** [comment]
换mobile-sam模型试一下。

https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/README.md#2-%E4%B8%8B%E8%BD%BDsegment-anything%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B

**Comment by yatengLG** [comment]
mobile-sam模型下载地址： https://github.com/ChaoningZhang/MobileSAM/blob/master/weights/mobile_sam.pt

**Comment by yatengLG** [comment]
#75 你的问题与这个反馈一致。鉴于你有显卡，但是无法调用sam-hq-tiny，应该是你显卡驱动未安装，或版本较低的缘故。
