### ISSUE TITLE
百度网盘下载的Windows安装包解压失败

### ISSUE THREAD

**Issue by tj250** [yatengLG/ISAT_with_segment_anything#85]
百度网盘下载的Windows安装包解压失败

**Comment by yatengLG** [comment]
用 winrar 解压试一试

**Comment by yatengLG** [comment]
好用的话，给点个star哦

**Comment by tj250** [comment]
就是用的winrar,不行呃。你们可否试一下？谢谢

**Comment by yatengLG** [comment]
> 就是用的winrar,不行呃。你们可否试一下？谢谢

好多人都是用的exe，都没问题的啊，你可以看B站那边的反馈。
exe都没更新过的T.T，现在只有那一个版本

**Comment by yatengLG** [comment]
> 就是用的winrar,不行呃。你们可否试一下？谢谢

另外，能的话，上传一下你的解压报错，不然没法分析你遇到的问题。

**Comment by tj250** [comment]
好的







------------------ 原始邮件 ------------------
发件人: yatengLG ***@***.***&gt;
发送时间: 2023年10月13日 10:58
收件人: yatengLG/ISAT_with_segment_anything ***@***.***&gt;
抄送: tj250 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yatengLG/ISAT_with_segment_anything] 百度网盘下载的Windows安装包解压失败 (Issue #85)





  
就是用的winrar,不行呃。你们可否试一下？谢谢
  
好多人都是用的exe，都没问题的啊，你可以看B站那边的反馈。
 exe都没更新过的T.T，现在只有那一个版本
