### ISSUE TITLE
能像metaAI网页端那样，在标注时显示prompt点吗

### ISSUE THREAD

**Issue by pkyzh2006** [yatengLG/ISAT_with_segment_anything#86]

**Comment by yatengLG** [comment]
提示点功能已经添加

可以在工具栏中点击show prompt进行 显示/隐藏 提示点。

**Comment by pkyzh2006** [comment]
> 提示点功能已经添加
> 
> 可以在工具栏中点击show prompt进行 显示/隐藏 提示点。

非常感谢！

**Comment by yatengLG** [comment]
如果对你的工作生活带来帮助，欢迎点个star哦O(∩_∩)O
