### ISSUE TITLE
语义分割

### ISSUE THREAD

**Issue by henuJackSon** [yatengLG/ISAT_with_segment_anything#88]
作者，您好，非常感谢您提供的标注工具。
我想对两张图片之间不同的区域进行语义分割，这个需要选中两张图片并调整其中一张图片的透明度才可以精准地对目标进行分割，类似于PhotoShop中的两个图层，调整顶端图层的透明度，看到两个图片之间差异的地方。
请问有这种功能模块吗？或者需要修改那些文件可以得到这个功能？
非常感谢您的回答！

**Comment by yatengLG** [comment]
你这个需求比较特殊，本软件没有提供这个功能。

首先，你这个需求是没法直接用sam标注的，只能手动进行标注（因为你是需要标注两张图片的不同区域，但是sam是基于每张图片计算特征图）。

如果你要更改本项目满足你的需求，你需要在widgets/canvas.py中是load_image函数中，一次加载两个图像；调整透明度的代码，你可以参考canvas.py中的update_mask函数，里面有有关透明度如何更改的代码。

如果还有其他需求，欢迎提问。

**Comment by henuJackSon** [comment]
作者您好，请问您会更新这方面的功能，我并没有成功实现这个功能。
或者有做这方面的工具吗？类似于您这个手工标注数据集的功能。

**Comment by yatengLG** [comment]
软件后续不会更新类似的功能，因为这个需求很少见，也与本软件的目标不一致（软件是为语义分割设计的，你这个任务已经不属于和这个范畴了）。

目前没有做与这个方面相关的工具，因为这个需求目前也就只有你一个人涉及了T.T

**Comment by henuJackSon** [comment]
这个也是语义分割任务中的一种。是找两张图片之间变化区域，然后对变化区域里面的内容进行语义分割，也是有一定需求的。
我觉得作者您开发的这个软件易用性很好，很容易上手，star了。

**Comment by yatengLG** [comment]
谢谢支持O(∩_∩)O

后续如果有空的话（时间保证不了哈T.T），可能单独针对你这个需求出一个软件。
如果出了，通知你！
