### ISSUE TITLE
在windows下mahotas和numpy包报错，可能是环境问题

### ISSUE THREAD

**Issue by kuatazz1993** [yatengLG/ISAT_with_segment_anything#9]
软件效果看起来不错，支持！

我用的Windows 10，segment完的结果想转成png保存下来。按README教程操作，但是报了图片中的错误。

![76811fe9250c897f65fe5288911d4a0](https://user-images.githubusercontent.com/131949124/234781887-fde64915-a352-45bd-9481-cc854ba1b4f7.png)

这个环境的问题能帮忙测试一下，看看怎么解决吗，如果能补到README里面最好，感谢！

**Comment by yatengLG** [comment]
您好，回去测试，手头没有win机器

**Comment by yatengLG** [comment]
有可能是包依赖或版本问题。
尝试更新使用最新的版本，软件持续更新中，很抱歉给您带来不便。
