### ISSUE TITLE
能否增加关键点标注任务？

### ISSUE THREAD

**Issue by zsy7532** [yatengLG/ISAT_with_segment_anything#92]
你好，请问源代码里可以增加关键点标注吗，从代码里要修改哪些地方

**Comment by yatengLG** [comment]
应该是b站来的b友吧。

改动关键点的功能，不会添加，因为软件起初就是为图像分割任务设计的。

另外如果想从源代码中进行修改的话，主要涉及以下几点：
1. polygons.py中添加一个关键点类，用于显示标注的关键点。具体可以参考prompt_point类。
2. canvas.py中需要修改，鼠标点击，拖动等事件函数，另外需要添加 开始标注关键点的函数，并在标注过程中，进行判断。
3. mainwindow.py中，主要对导入以及保存标签文件部分进行修改。

主要涉及的就这几个点，剩下的也有修改的地方，但都是小修改了。
