### ISSUE TITLE
图像resize

### ISSUE THREAD

**Issue by FOURSEVEN-L** [yatengLG/ISAT_with_segment_anything#93]
非常好用的标注软件，提供了极大的便利，十分感谢！
请问图像一定要resize到1000吗？ 我的图片分辨率过高，resize到1000*1000之后很多目标类别肉眼不好区分，请问可以修改这个resize的大小吗？或者可以模型按照1000*1000去做预测，但是我们那个页面人类肉眼看到的是原图尺寸是可以吗？我应该去修改哪个文件呢？

打扰啦~

**Comment by yatengLG** [comment]
只是Sam在计算特征图时需要resize到1000，软件是不会resize你图片的。
所以这方面你完全不用担心。

好用的话，给个star哦O(∩_∩)O

**Comment by FOURSEVEN-L** [comment]
噢噢！我明白啦，感谢！
