### ISSUE TITLE
能否增加对标注结果选择“是否镂空”？

### ISSUE THREAD

**Issue by liuqinglong110** [yatengLG/ISAT_with_segment_anything#95]
您好，我正在使用您的软件工具标注“草”。对于草地上的“非草”需要标记为其他类别，也就是需要将mask镂空处理。如下图所示：
原图如下：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/23652342/34d16d2e-3e85-46e4-87eb-76eae7581c79)
当我手动标注完“草”后，草地上的篱笆是被包含进去的。如下图所示：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/23652342/cf9447c0-e37f-4748-bb7f-805c17940c07)
此时，我需要将篱笆继续标注成“障碍物”，此时我使用SAM自动化标注，标注时，SAM可以正确的区分篱笆和草。如下图所示：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/23652342/ad956d16-9412-49e3-838d-9be96a8640ae)
但是，按快捷键E后，篱笆的镂空位置的草，也被标注成了障碍物。可是，SAM算法明明是知道每个像素的类别，最终结果并不是我想要的。如下图所示：
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/23652342/8e7224dd-a882-4f4c-9560-c623d3831fe8)

某些情况下确实可以直接覆盖镂空的区域，避免mask出现空洞。但是，我上面的例子希望能保存成SAM算法成功检测出来的真实结果。请问作者这个需求是否可以实现吗？不一定是将标注结果保存成json，保存成图片也可以。
我知道您现在的保存方式是将mask用多边形方式记录，所以直接保存成镂空的形式，会比较麻烦，所以，我绝对保存成图片形式可能更容易一些。

如果有了这个功能，最好是有个开关控制，有的时候需要镂空，有的时候不需要镂空。

**Comment by yatengLG** [comment]
你想要的是这种效果吧

1. '草'的标注，可以在菜单栏-模式-轮廓模式-保存所有轮廓
- sam分割效果
![gnome-shell-screenshot-I79NE2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/8c076050-200b-496d-aeeb-31cedd1dd1a4)
-  最终结果，将草的部分，均保存为一个多边形。
![gnome-shell-screenshot-YFLVE2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/c04eebab-f5f7-4712-9c1d-e51e60bef9f1)

2. '栅栏'的标注
![gnome-shell-screenshot-W7ISE2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/c2d29318-b9ac-448f-baed-86be7495c9fd)
中间的黑色部分，是背景类。


3. 如果你需要同时标注'草'和'栅栏'两种类别，这种情况需要区分下先后顺序，我这里先标注了'栅栏'，然后标注的'草'。
![gnome-shell-screenshot-E1UAE2](https://github.com/yatengLG/ISAT_with_segment_anything/assets/31759824/839a03d7-5648-462c-91be-c2a1fc9eaab7)



轮廓模式的说明
1. 只保存最大轮廓 - 默认的选项，对于有干扰的情况，特别好。缺点是只会保存最大的轮廓，即使存在多个区域的mask，也只会保存一个。
3. 保存外轮廓 - 保存所有的外轮廓，介于1和3之间。和3的主要区别是，会忽略内轮廓，内轮廓会被填充。
4. 保存所有轮廓 - 所有的轮廓都会保存，内轮廓会额外添加一个背景类的多边形。

**Comment by liuqinglong110** [comment]
@yatengLG 感谢您的即使回答。没错，我确实需要的是这种效果。非常感谢！

另外，我还有一个疑问：每次标注之后，由于存在多个区域，会一次性生成很多个标签。此时，如果我想把所有标签都删除，需要一个标签单击选中一次，然后删除。非常繁琐。不知道有什么方法能一次同时删除多个标签。我曾经尝试了ctrl+A等方式，均不成功。

**Comment by yatengLG** [comment]
> @yatengLG 感谢您的即使回答。没错，我确实需要的是这种效果。非常感谢！
> 
> 另外，我还有一个疑问：每次标注之后，由于存在多个区域，会一次性生成很多个标签。此时，如果我想把所有标签都删除，需要一个标签单击选中一次，然后删除。非常繁琐。不知道有什么方法能一次同时删除多个标签。我曾经尝试了ctrl+A等方式，均不成功。

最新的代码中中，添加了 多边形的批量选择与删除功能。

- 按下Ctrl，在画布上点选多边形
- 按下Ctrl，在右侧标注栏中点选多边形
- 按下Shift，在右侧标注栏中多选多边形
- 在右侧标注栏中，Ctrl+A，全选多边形

**Comment by liuqinglong110** [comment]
> > @yatengLG 感谢您的即使回答。没错，我确实需要的是这种效果。非常感谢！
> > 另外，我还有一个疑问：每次标注之后，由于存在多个区域，会一次性生成很多个标签。此时，如果我想把所有标签都删除，需要一个标签单击选中一次，然后删除。非常繁琐。不知道有什么方法能一次同时删除多个标签。我曾经尝试了ctrl+A等方式，均不成功。
> 
> 最新的代码中中，添加了 多边形的批量选择与删除功能。
> 
> * 按下Ctrl，在画布上点选多边形
> * 按下Ctrl，在右侧标注栏中点选多边形
> * 按下Shift，在右侧标注栏中多选多边形
> * 在右侧标注栏中，Ctrl+A，全选多边形

看了代码仓库的commits，感谢作者专门增加的这个功能。万分感激！
