### ISSUE TITLE
图像分割格式是否支持ISTA转YOLO的txt格式

### ISSUE THREAD

**Issue by pcycccccc** [yatengLG/ISAT_with_segment_anything#96]
我看到大佬已经更新了YOLO的txt格式转ISAT格式，但还未实践，请问图像分割格式是否支持ISTA转YOLO的txt格式？？

**Comment by yatengLG** [comment]
目前，转换的脚本还未完善。

现在可以先尝试isat转labelme格式的json，然后labelme转yolo。

labelme转yolo的脚本，网上应该很好找。

**Comment by pcycccccc** [comment]
好的好的

**Comment by yatengLG** [comment]
更新了转换脚本，目前在utils目录下。

当前支持 ISAT <-> COCO, ISAT <-> YOLO, ISAT -> XML(目标检测)

**Comment by pcycccccc** [comment]
> 更新了转换脚本，目前在utils目录下。
> 
> 当前支持 ISAT <-> COCO， ISAT <-> YOLO， ISAT -> XML（目标检测）

谢谢大佬！！！
