### ISSUE TITLE
载入图片文件夹报错：RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 2 is not equal to len(dims) = 3

### ISSUE THREAD

**Issue by pcycccccc** [yatengLG/ISAT_with_segment_anything#97]
1、我先导入模型sam_hq_vit_q.pth，再导入图片文件夹（bmp格式），报错
2、我先导入图片文件夹（bmp格式），再导入模型报错，
![image](https://github.com/yatengLG/ISAT_with_segment_anything/assets/108455796/34eea6b0-ecb3-4e08-96e3-ea8a0fb40d59)
我测试了一下导入depth=3的图像文件（jpg），是可以用的，但是灰度图（bmp格式的）不支持，我在旧版的软件上是都可以支持的。

**Comment by yatengLG** [comment]
sam只支持三通道图片进行预测，这边建议先转换为三通道图片。

**Comment by pcycccccc** [comment]
> sam只支持三通道图片进行预测，这边建议先转换为三通道图片。

很感谢大佬的回答，你的软件也有帮助到我了，优化后的软件在速度上好像更快了，但是现在在很多工业项目上的采图都是以灰度图为主，前一个月用过ISAT_with_segment_anything，是可以支持灰度图，有点好奇为啥大佬会限制这个图片的通道数？

**Comment by yatengLG** [comment]
> > sam只支持三通道图片进行预测，这边建议先转换为三通道图片。
> 
> 很感谢大佬的回答，你的软件也有帮助到我了，优化后的软件在速度上好像更快了，但是现在在很多工业项目上的采图都是以灰度图为主，前一个月用过ISAT_with_segment_anything，是可以支持灰度图，有点好奇为啥大佬会限制这个图片的通道数？

这个主要是考虑到，用户输入的图像不止是三通道的，还有单通道以及四通道等各种格式。

如果软件内直接进行转换的话，难免会改变图片信息，如果因为这个给标注造成影响的话，就只能修改软件代码了，会非常不方便。

将图像的控制权交给用户，由用户来进行转换和处理，感觉比较好一些。

**Comment by pcycccccc** [comment]
> 是现在很多工业项目的采图都是以图上为主，前一个月用过ISAT_with_segment_anything，是可以支持灰度图，有点好奇为啥大佬会限制这张图片的通道数

晓得啦！！多谢大佬帮我答疑解惑
